import { DiplomaConfig } from "./LeadPortalDashboard";

// Configuration for all mini diploma portals — 3 lessons per diploma
export const DIPLOMA_CONFIGS: Record<string, DiplomaConfig> = {
    "functional-medicine-diploma": {
        slug: "functional-medicine-diploma",
        portalSlug: "functional-medicine",
        name: "Functional Medicine Certification",
        shortName: "Functional Medicine",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Functional Medicine Revolution", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Functional Medicine Practice", duration: "8 min" },
            ],
        }],
    },
    "womens-health-diploma": {
        slug: "womens-health-diploma",
        portalSlug: "womens-health",
        name: "Women's Health Certification",
        shortName: "Women's Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Female Hormonal Landscape", duration: "8 min" },
                { id: 2, title: "The B.L.O.O.M. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Women's Health Coaching Practice", duration: "8 min" },
            ],
        }],
    },
    "womens-hormone-health-diploma": {
        slug: "womens-hormone-health-diploma",
        portalSlug: "womens-hormone-health",
        name: "Women's Hormone Health Certification",
        shortName: "Women's Hormone Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Female Hormonal Landscape", duration: "8 min" },
                { id: 2, title: "The B.L.O.O.M. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Women's Health Coaching Practice", duration: "8 min" },
            ],
        }],
    },
    "gut-health-diploma": {
        slug: "gut-health-diploma",
        portalSlug: "gut-health",
        name: "Gut Health Certification",
        shortName: "Gut Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Gut Health Revolution", duration: "8 min" },
                { id: 2, title: "The R.E.S.E.T. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Gut Health Practice", duration: "8 min" },
            ],
        }],
    },
    "hormone-health-diploma": {
        slug: "hormone-health-diploma",
        portalSlug: "hormone-health",
        name: "Hormone Health Certification",
        shortName: "Hormone Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Understanding the Hormonal Symphony", duration: "8 min" },
                { id: 2, title: "The B.A.L.A.N.C.E. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Hormone Health Practice", duration: "8 min" },
            ],
        }],
    },
    "holistic-nutrition-diploma": {
        slug: "holistic-nutrition-diploma",
        portalSlug: "holistic-nutrition",
        name: "Holistic Nutrition Certification",
        shortName: "Holistic Nutrition",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Holistic Nutrition Revolution", duration: "8 min" },
                { id: 2, title: "The W.H.O.L.E. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Holistic Nutrition Practice", duration: "8 min" },
            ],
        }],
    },
    "nurse-coach-diploma": {
        slug: "nurse-coach-diploma",
        portalSlug: "nurse-coach",
        name: "Nurse Coach Certification",
        shortName: "Nurse Coach",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "From Bedside to Beyond", duration: "8 min" },
                { id: 2, title: "The C.A.R.E.S. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Nurse Coaching Business", duration: "8 min" },
            ],
        }],
    },
    "health-coach-diploma": {
        slug: "health-coach-diploma",
        portalSlug: "health-coach",
        name: "Health Coach Certification",
        shortName: "Health Coaching",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Health Coaching Revolution", duration: "8 min" },
                { id: 2, title: "The T.H.R.I.V.E. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Health Coaching Practice", duration: "8 min" },
            ],
        }],
    },
    "energy-healing-diploma": {
        slug: "energy-healing-diploma",
        portalSlug: "energy-healing",
        name: "Energy Healing Certification",
        shortName: "Energy Healing",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Science of Energy Healing", duration: "8 min" },
                { id: 2, title: "The F.L.O.W. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Energy Healing Practice", duration: "8 min" },
            ],
        }],
    },
    "christian-coaching-diploma": {
        slug: "christian-coaching-diploma",
        portalSlug: "christian-coaching",
        name: "Christian Life Coach Certification",
        shortName: "Christian Coaching",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Call to Christian Coaching", duration: "8 min" },
                { id: 2, title: "The G.R.A.C.E. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Faith-Based Coaching Practice", duration: "8 min" },
            ],
        }],
    },
    "reiki-healing-diploma": {
        slug: "reiki-healing-diploma",
        portalSlug: "reiki-healing",
        name: "Reiki Practitioner Certification",
        shortName: "Reiki Healing",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Art of Reiki Healing", duration: "8 min" },
                { id: 2, title: "The L.I.G.H.T. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Reiki Healing Practice", duration: "8 min" },
            ],
        }],
    },
    "adhd-coaching-diploma": {
        slug: "adhd-coaching-diploma",
        portalSlug: "adhd-coaching",
        name: "ADHD Coach Certification",
        shortName: "ADHD Coaching",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Understanding ADHD Beyond the Label", duration: "8 min" },
                { id: 2, title: "The F.O.C.U.S. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your ADHD Coaching Practice", duration: "8 min" },
            ],
        }],
    },
    "pet-nutrition-diploma": {
        slug: "pet-nutrition-diploma",
        portalSlug: "pet-nutrition",
        name: "Pet Nutrition Specialist Certification",
        shortName: "Pet Nutrition",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Pet Nutrition Crisis", duration: "8 min" },
                { id: 2, title: "The P.A.W.S. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Pet Nutrition Business", duration: "8 min" },
            ],
        }],
    },
    "spiritual-healing-diploma": {
        slug: "spiritual-healing-diploma",
        portalSlug: "spiritual-healing",
        name: "Spiritual Healing Certification",
        shortName: "Spiritual Healing",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Spiritual Healing Awakening", duration: "8 min" },
                { id: 2, title: "The S.A.C.R.E.D. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Spiritual Healing Practice", duration: "8 min" },
            ],
        }],
    },
    "integrative-health-diploma": {
        slug: "integrative-health-diploma",
        portalSlug: "integrative-health",
        name: "Integrative Health Certification",
        shortName: "Integrative Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Integrative Health Revolution", duration: "8 min" },
                { id: 2, title: "The B.R.I.D.G.E. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building Your Integrative Health Practice", duration: "8 min" },
            ],
        }],
    },
    "life-coaching-diploma": {
        slug: "life-coaching-diploma",
        portalSlug: "life-coaching",
        name: "Life Coach Certification",
        shortName: "Life Coaching",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "The Art & Science of Life Coaching", duration: "8 min" },
                { id: 2, title: "The S.H.I.F.T. Method™ in Practice", duration: "8 min" },
                { id: 3, title: "Building a Profitable Coaching Business", duration: "8 min" },
            ],
        }],
    },
};
