import { DiplomaConfig } from "./LeadPortalDashboard";

// Configuration for all mini diploma portals — 3 lessons per diploma
export const DIPLOMA_CONFIGS: Record<string, DiplomaConfig> = {
    "functional-medicine-diploma": {
        slug: "functional-medicine-diploma",
        portalSlug: "functional-medicine",
        name: "Functional Medicine Certification",
        shortName: "Functional Medicine",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Functional Medicine Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "womens-health-diploma": {
        slug: "womens-health-diploma",
        portalSlug: "womens-health",
        name: "Women's Health Certification",
        shortName: "Women's Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Women's Health Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "womens-hormone-health-diploma": {
        slug: "womens-hormone-health-diploma",
        portalSlug: "womens-hormone-health",
        name: "Women's Hormone Health Certification",
        shortName: "Women's Hormone Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Women's Hormone Health Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "gut-health-diploma": {
        slug: "gut-health-diploma",
        portalSlug: "gut-health",
        name: "Gut Health Certification",
        shortName: "Gut Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Gut Health Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "hormone-health-diploma": {
        slug: "hormone-health-diploma",
        portalSlug: "hormone-health",
        name: "Hormone Health Certification",
        shortName: "Hormone Health",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Hormone Health Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "holistic-nutrition-diploma": {
        slug: "holistic-nutrition-diploma",
        portalSlug: "holistic-nutrition",
        name: "Holistic Nutrition Certification",
        shortName: "Holistic Nutrition",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Holistic Nutrition Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "nurse-coach-diploma": {
        slug: "nurse-coach-diploma",
        portalSlug: "nurse-coach",
        name: "Nurse Coach Certification",
        shortName: "Nurse Coach",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Nurse Coach Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "health-coach-diploma": {
        slug: "health-coach-diploma",
        portalSlug: "health-coach",
        name: "Health Coach Certification",
        shortName: "Health Coaching",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Health Coaching Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "energy-healing-diploma": {
        slug: "energy-healing-diploma",
        portalSlug: "energy-healing",
        name: "Energy Healing Certification",
        shortName: "Energy Healing",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Energy Healing Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "christian-coaching-diploma": {
        slug: "christian-coaching-diploma",
        portalSlug: "christian-coaching",
        name: "Christian Life Coach Certification",
        shortName: "Christian Coaching",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Christian Coaching Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "reiki-healing-diploma": {
        slug: "reiki-healing-diploma",
        portalSlug: "reiki-healing",
        name: "Reiki Practitioner Certification",
        shortName: "Reiki Healing",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Reiki Healing Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "adhd-coaching-diploma": {
        slug: "adhd-coaching-diploma",
        portalSlug: "adhd-coaching",
        name: "ADHD Coach Certification",
        shortName: "ADHD Coaching",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "ADHD Coaching Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "pet-nutrition-diploma": {
        slug: "pet-nutrition-diploma",
        portalSlug: "pet-nutrition",
        name: "Pet Nutrition Specialist Certification",
        shortName: "Pet Nutrition",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Pet Nutrition Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
    "spiritual-healing-diploma": {
        slug: "spiritual-healing-diploma",
        portalSlug: "spiritual-healing",
        name: "Spiritual Healing Certification",
        shortName: "Spiritual Healing",
        coachName: "Sarah",
        coachImage: "/coaches/sarah-coach.webp",
        modules: [{
            id: 1,
            title: "Foundation Course",
            description: "Your path to certification",
            icon: "BookOpen",
            lessons: [
                { id: 1, title: "Spiritual Healing Foundation", duration: "8 min" },
                { id: 2, title: "The D.E.P.T.H. Method\u2122", duration: "8 min" },
                { id: 3, title: "How To Get Your First Clients", duration: "8 min" },
            ],
        }],
    },
};
