// Top 10 Functional Medicine Specializations
// Ranked by market demand, income potential, and career growth

export const FM_SPECIALIZATIONS = [
  {
    rank: 1,
    id: "functional-nutrition",
    title: "Functional Nutrition",
    shortTitle: "Nutrition",
    badge: "CORE",
    description: "The foundation of all functional medicine. Every practitioner needs nutrition expertise.",
    marketDemand: "Very High",
    incomeRange: "$60K - $150K",
    targetClients: "General wellness seekers, chronic disease prevention",
    keyTopics: ["Elimination diets", "Blood sugar optimization", "Phytonutrient protocols", "Food sensitivity testing"],
    icon: "Apple",
    color: "emerald",
    gradient: "from-emerald-500 to-emerald-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    textColor: "text-emerald-700",
  },
  {
    rank: 2,
    id: "gut-health",
    title: "Gut Health & Microbiome",
    shortTitle: "Gut Health",
    badge: "HIGH DEMAND",
    description: "The root of 80% of chronic conditions. Massive client demand and strong outcomes.",
    marketDemand: "Very High",
    incomeRange: "$70K - $180K",
    targetClients: "IBS, SIBO, autoimmune, skin issues",
    keyTopics: ["5R Protocol", "Microbiome testing", "SIBO management", "Leaky gut repair"],
    icon: "Leaf",
    color: "green",
    gradient: "from-green-500 to-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    textColor: "text-green-700",
  },
  {
    rank: 3,
    id: "womens-hormones",
    title: "Women's Hormones",
    shortTitle: "Hormones",
    badge: "TRENDING",
    description: "Massive market with underserved women. PMS, PCOS, fertility, perimenopause.",
    marketDemand: "Very High",
    incomeRange: "$80K - $200K",
    targetClients: "Women 25-55 with hormonal imbalances",
    keyTopics: ["Menstrual cycle mapping", "PCOS protocols", "Perimenopause support", "Fertility optimization"],
    icon: "Heart",
    color: "pink",
    gradient: "from-pink-500 to-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    textColor: "text-pink-700",
  },
  {
    rank: 4,
    id: "stress-nervous-system",
    title: "Stress & Nervous System",
    shortTitle: "Stress/HPA",
    badge: "GROWING",
    description: "Burnout epidemic driving massive demand. HPA axis, cortisol, adrenal support.",
    marketDemand: "High",
    incomeRange: "$60K - $140K",
    targetClients: "Professionals, executives, chronic fatigue",
    keyTopics: ["HPA axis restoration", "Cortisol patterns", "Burnout recovery", "Adaptogen protocols"],
    icon: "Brain",
    color: "purple",
    gradient: "from-purple-500 to-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    textColor: "text-purple-700",
  },
  {
    rank: 5,
    id: "thyroid-metabolism",
    title: "Thyroid & Metabolism",
    shortTitle: "Thyroid",
    badge: "EVERGREEN",
    description: "Millions with undiagnosed thyroid issues. Hashimoto's, conversion issues, weight.",
    marketDemand: "High",
    incomeRange: "$65K - $160K",
    targetClients: "Hashimoto's, hypothyroid, weight resistance",
    keyTopics: ["Full thyroid panel interpretation", "Autoimmune thyroid", "T4 to T3 conversion", "Nutrient cofactors"],
    icon: "Zap",
    color: "amber",
    gradient: "from-amber-500 to-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    textColor: "text-amber-700",
  },
  {
    rank: 6,
    id: "blood-sugar-weight",
    title: "Blood Sugar & Weight Resistance",
    shortTitle: "Metabolic",
    badge: "HIGH VOLUME",
    description: "Obesity epidemic = endless clients. Insulin resistance, metabolic syndrome.",
    marketDemand: "Very High",
    incomeRange: "$55K - $130K",
    targetClients: "Pre-diabetic, metabolic syndrome, weight loss seekers",
    keyTopics: ["Insulin resistance reversal", "Metabolic flexibility", "Weight plateau solutions", "CGM interpretation"],
    icon: "TrendingUp",
    color: "orange",
    gradient: "from-orange-500 to-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    textColor: "text-orange-700",
  },
  {
    rank: 7,
    id: "autoimmune-inflammation",
    title: "Autoimmune & Chronic Inflammation",
    shortTitle: "Autoimmune",
    badge: "SPECIALIST",
    description: "Complex cases, premium rates. Growing autoimmune epidemic needs specialists.",
    marketDemand: "Medium-High",
    incomeRange: "$80K - $200K",
    targetClients: "Autoimmune conditions, chronic inflammation",
    keyTopics: ["Autoimmune triggers", "AIP protocol", "Inflammation pathways", "Immune modulation"],
    icon: "Shield",
    color: "red",
    gradient: "from-red-500 to-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    textColor: "text-red-700",
  },
  {
    rank: 8,
    id: "mental-health-brain",
    title: "Mental Health & Brain Health",
    shortTitle: "Brain Health",
    badge: "EMERGING",
    description: "Gut-brain axis, depression, anxiety, cognitive decline. Underserved market.",
    marketDemand: "Growing",
    incomeRange: "$70K - $170K",
    targetClients: "Anxiety, depression, brain fog, cognitive issues",
    keyTopics: ["Gut-brain axis", "Neurotransmitter support", "Brain inflammation", "Cognitive protocols"],
    icon: "Brain",
    color: "indigo",
    gradient: "from-indigo-500 to-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    textColor: "text-indigo-700",
  },
  {
    rank: 9,
    id: "sleep-circadian",
    title: "Sleep & Circadian Health",
    shortTitle: "Sleep",
    badge: "NICHE",
    description: "Sleep epidemic affecting millions. Circadian rhythm, insomnia, energy optimization.",
    marketDemand: "Medium",
    incomeRange: "$50K - $120K",
    targetClients: "Insomnia, shift workers, energy issues",
    keyTopics: ["Sleep architecture", "Circadian optimization", "Light therapy", "Sleep hygiene protocols"],
    icon: "Moon",
    color: "blue",
    gradient: "from-blue-500 to-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    textColor: "text-blue-700",
  },
  {
    rank: 10,
    id: "detox-environmental",
    title: "Detoxification & Environmental Health",
    shortTitle: "Detox",
    badge: "ADVANCED",
    description: "Toxin exposure increasing. Mold, heavy metals, environmental toxins.",
    marketDemand: "Growing",
    incomeRange: "$75K - $180K",
    targetClients: "Toxic exposure, mold illness, chemical sensitivity",
    keyTopics: ["Biotransformation pathways", "Heavy metal detox", "Mold illness", "Environmental toxin reduction"],
    icon: "Droplets",
    color: "teal",
    gradient: "from-teal-500 to-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    textColor: "text-teal-700",
  },
];

// Career paths with specializations
export const CAREER_PATHS_BY_SPECIALIZATION = {
  "general-practitioner": {
    title: "General FM Practitioner",
    recommendedSpecs: ["functional-nutrition", "gut-health", "stress-nervous-system"],
    description: "Broad foundation serving diverse clients",
  },
  "womens-health-specialist": {
    title: "Women's Health Specialist",
    recommendedSpecs: ["womens-hormones", "thyroid-metabolism", "stress-nervous-system"],
    description: "Focus on female hormones, fertility, and lifecycle transitions",
  },
  "gut-specialist": {
    title: "Gut Health Specialist",
    recommendedSpecs: ["gut-health", "autoimmune-inflammation", "functional-nutrition"],
    description: "Deep expertise in digestive health and microbiome",
  },
  "metabolic-specialist": {
    title: "Metabolic Health Specialist",
    recommendedSpecs: ["blood-sugar-weight", "thyroid-metabolism", "functional-nutrition"],
    description: "Weight loss, diabetes prevention, metabolic optimization",
  },
  "complex-cases": {
    title: "Complex Case Specialist",
    recommendedSpecs: ["autoimmune-inflammation", "detox-environmental", "mental-health-brain"],
    description: "Advanced practitioner handling challenging multi-system cases",
  },
};

// Get specialization by ID
export function getSpecialization(id: string) {
  return FM_SPECIALIZATIONS.find(s => s.id === id);
}

// Get top specializations
export function getTopSpecializations(count: number = 5) {
  return FM_SPECIALIZATIONS.slice(0, count);
}
