'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';
export default function Lesson2Page() {
  const [currentSection, setCurrentSection] = useState(0);
  const [completedSections, setCompletedSections] = useState<number[]>([]);
  const [quickCheckAnswers, setQuickCheckAnswers] = useState<{ [key: number]: string | null }>({});
  const [showAnswers, setShowAnswers] = useState<number[]>([]);
  const [notes, setNotes] = useState('');
  const [showNotes, setShowNotes] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [newMessage, setNewMessage] = useState('');
  const lessonNumber = 2;
  const brandColor = '#2D5A4A';
  const accentColor = '#D4AF37';
  const title = 'Your Clinical Advantage Assessment';
  useEffect(() => { const n = localStorage.getItem('roots-lesson-2-notes'); if (n) setNotes(n); }, []);
  const handleNotesChange = (v: string) => { setNotes(v); localStorage.setItem('roots-lesson-2-notes', v); };
  const sections = [
    { id: 0, type: 'content', title: 'Your Unique Position', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Why Healthcare Workers Have the Edge</h3><p>Before we dive into the R.O.O.T.S. Method, let's assess the <strong style={{ color: brandColor }}>massive advantages</strong> you already have:</p><div style={{ display: 'grid', gap: 12, margin: '20px 0' }}>{['Clinical Assessment: You can evaluate patients properly', 'Medical Literacy: You understand lab work and contraindications', 'Communication: You know how to talk to people who are suffering', 'Credibility: Clients trust healthcare professionals immediately', 'Crisis Management: You stay calm under pressure'].map((s, i) => (<div key={i} style={{ padding: 16, background: '#f8f9fa', borderRadius: 12, borderLeft: '4px solid ' + accentColor, display: 'flex', gap: 12, alignItems: 'center' }}><span style={{ color: accentColor, fontSize: 20 }}>✓</span><span>{s}</span></div>))}</div></>) },
    { id: 1, type: 'content', title: 'Skills Assessment', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Your Transferable Skills Inventory</h3><p>Rate yourself on these transferable skills (you'll be surprised):</p><div style={{ background: '#f8f9fa', padding: 20, borderRadius: 12, margin: '20px 0' }}>{['Patient history taking', 'Physical assessment basics', 'Lab result interpretation', 'Medication awareness', 'Client communication', 'Documentation skills'].map((skill, i) => (<div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 0', borderBottom: i < 5 ? '1px solid #e9ecef' : 'none' }}><span>{skill}</span><span style={{ color: brandColor, fontWeight: 600 }}>Expert</span></div>))}</div><p>You likely rated yourself "Expert" on most. <strong style={{ color: brandColor }}>These same skills are exactly what makes R.O.O.T.S. practitioners successful.</strong></p></>) },
    { id: 2, type: 'quickcheck', title: 'Quick Check', question: 'Which skill gives healthcare workers an immediate advantage with clients?', options: ['Social media marketing', 'Instant credibility and trust', 'Website design', 'Sales techniques'], correct: 'Instant credibility and trust', explanation: 'Healthcare professionals have instant credibility. Clients trust your training and experience immediately - something that takes non-clinical practitioners years to build.' },
    { id: 3, type: 'content', title: 'The Confidence Gap', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Why You Might Not See Your Own Strengths</h3><p>Many healthcare workers suffer from "imposter syndrome" when considering a new path. But consider:</p><div style={{ display: 'grid', gap: 8, margin: '20px 0' }}><div style={{ padding: 16, background: '#fee2e2', borderRadius: 8 }}><strong>What you think:</strong> "I only know hospital nursing"</div><div style={{ padding: 16, background: '#d1fae5', borderRadius: 8 }}><strong>Reality:</strong> You have 10+ years of patient care experience worth thousands in training</div></div><div style={{ background: brandColor, color: 'white', padding: 24, borderRadius: 12, margin: '20px 0' }}><p style={{ margin: 0, fontStyle: 'italic' }}>"I thought my ER experience wouldn't translate. Turns out, it was my biggest asset. I'd already seen every health condition imaginable."</p><p style={{ margin: '12px 0 0', fontSize: 14, opacity: 0.9 }}>— Maria K., ER Nurse → R.O.O.T.S. Practitioner</p></div></>) },
    { id: 4, type: 'content', title: 'Ready for R.O.O.T.S.', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>You're More Ready Than You Think</h3><p>Now that you've assessed your advantages, you're ready to learn the framework that will transform how you use them.</p><p style={{ marginTop: 16 }}>In the next lesson, you'll get a complete overview of the R.O.O.T.S. Method™ and how each component works together.</p><div style={{ background: 'linear-gradient(135deg, #f8f9fa, white)', border: '2px solid ' + accentColor, borderRadius: 16, padding: 24, textAlign: 'center', margin: '24px 0' }}><div style={{ fontSize: 24, marginBottom: 8 }}>🌱</div><div style={{ fontWeight: 600, color: brandColor }}>Coming Up: The R.O.O.T.S. Framework Overview</div><div style={{ fontSize: 14, color: '#666', marginTop: 8 }}>The complete system that changes everything</div></div></>) },
  ];
  const totalSections = sections.length;
  const progress = Math.round((completedSections.length / totalSections) * 100);
  const moduleProgress = Math.round((lessonNumber / 9) * 100);
  const handleContinue = () => { if (!completedSections.includes(currentSection)) setCompletedSections([...completedSections, currentSection]); if (currentSection < totalSections - 1) { setCurrentSection(currentSection + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); } };
  const handleQuickCheck = (id: number, a: string) => setQuickCheckAnswers({ ...quickCheckAnswers, [id]: a });
  const handleCheckAnswer = (id: number) => { if (!showAnswers.includes(id)) setShowAnswers([...showAnswers, id]); };
  const currentSectionData = sections[currentSection];
  const isLastSection = currentSection === totalSections - 1;
  const isQuickCheck = currentSectionData.type === 'quickcheck';
  const canContinue = isQuickCheck ? showAnswers.includes(currentSectionData.id) : true;
  return (
    <div style={{ minHeight: '100vh', background: '#fff', fontFamily: 'Georgia, serif' }}>
      <header style={{ background: 'linear-gradient(135deg, #1a1a2e, #16213e)', padding: '16px 24px', position: 'sticky', top: 0, zIndex: 100 }}><div style={{ maxWidth: 640, margin: '0 auto' }}><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}><span style={{ fontSize: 18 }}>🌱</span><span style={{ fontSize: 14, color: 'white', fontWeight: 600 }}>R.O.O.T.S. Method™</span><div style={{ flex: 1, height: 6, background: 'rgba(255,255,255,0.2)', borderRadius: 3, marginLeft: 12 }}><div style={{ height: '100%', width: moduleProgress + '%', background: accentColor, borderRadius: 3 }} /></div><span style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>{lessonNumber}/9</span></div><div style={{ display: 'flex', justifyContent: 'space-between', color: 'white' }}><span style={{ fontSize: 14 }}>Lesson {lessonNumber}</span><span style={{ fontSize: 12, opacity: 0.7 }}>5 min</span></div></div></header>
      <main style={{ maxWidth: 640, margin: '0 auto', padding: '32px 24px 140px' }}><h1 style={{ fontSize: 26, lineHeight: 1.3, marginBottom: 32, fontWeight: 600 }}>{title}</h1>{currentSectionData.type === 'content' ? (<div style={{ fontSize: 17, lineHeight: 1.9 }}>{currentSectionData.content}</div>) : (<div style={{ background: '#f8f9fa', border: '1px solid #e9ecef', borderRadius: 16, padding: 28 }}><p style={{ fontSize: 18, fontWeight: 500, marginBottom: 24 }}>{currentSectionData.question}</p><div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>{currentSectionData.options?.map((o: string) => { const sel = quickCheckAnswers[currentSectionData.id] === o; const cor = o === currentSectionData.correct; const show = showAnswers.includes(currentSectionData.id); return (<button key={o} onClick={() => !show && handleQuickCheck(currentSectionData.id, o)} style={{ padding: '16px', border: '2px solid', borderColor: show ? (cor ? '#10B981' : sel ? '#EF4444' : '#ddd') : (sel ? brandColor : '#ddd'), background: show && cor ? '#D1FAE5' : show && sel && !cor ? '#FEE2E2' : 'white', borderRadius: 10, textAlign: 'left', fontSize: 16 }}>{o}</button>); })}</div>{quickCheckAnswers[currentSectionData.id] && !showAnswers.includes(currentSectionData.id) && (<button onClick={() => handleCheckAnswer(currentSectionData.id)} style={{ marginTop: 20, padding: '16px', background: brandColor, color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, width: '100%', cursor: 'pointer' }}>Check Answer</button>)}{showAnswers.includes(currentSectionData.id) && (<div style={{ marginTop: 20, padding: 16, background: '#D1FAE5', borderRadius: 10 }}><p style={{ margin: 0 }}>{currentSectionData.explanation}</p></div>)}</div>)}<div style={{ marginTop: 40 }}>{!canContinue ? (<p style={{ color: '#888', textAlign: 'center' }}>Answer to continue</p>) : isLastSection ? (<Link href="/roots-method/lesson-3" style={{ display: 'block', padding: '18px', background: 'linear-gradient(135deg, ' + brandColor + ', #1a3a2e)', color: 'white', borderRadius: 10, fontSize: 16, fontWeight: 600, textAlign: 'center', textDecoration: 'none' }}>Continue to Lesson 3 →</Link>) : (<button onClick={handleContinue} style={{ width: '100%', padding: '18px', background: 'linear-gradient(135deg, ' + brandColor + ', #1a3a2e)', color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, cursor: 'pointer' }}>Continue →</button>)}</div></main>
      <div style={{ position: 'fixed', bottom: 24, right: 24, display: 'flex', flexDirection: 'column', gap: 12, zIndex: 100 }}><button onClick={() => setShowNotes(!showNotes)} style={{ width: 56, height: 56, borderRadius: '50%', background: showNotes ? brandColor : 'white', color: showNotes ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>📝</button><button onClick={() => setShowChat(!showChat)} style={{ width: 56, height: 56, borderRadius: '50%', background: showChat ? brandColor : 'white', color: showChat ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>💬</button></div>
      {showNotes && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 320, background: 'white', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100 }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0' }}><span>📝 Notes</span></div><div style={{ padding: 16 }}><textarea value={notes} onChange={(e) => handleNotesChange(e.target.value)} placeholder="Notes..." style={{ width: '100%', height: 200, border: '1px solid #ddd', borderRadius: 8, padding: 12 }} /></div></div>)}
      {showChat && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 340, height: 400, background: 'white', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100, display: 'flex', flexDirection: 'column' }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0', display: 'flex', alignItems: 'center', gap: 10 }}><Image src="/coaches/sarah-coach.webp" alt="Sarah" width={32} height={32} style={{ borderRadius: '50%' }} /><span>Chat with Sarah</span></div><div style={{ flex: 1, padding: 16 }}><div style={{ textAlign: 'center', color: '#888', padding: 40 }}>🌱 Ask me anything!</div></div><div style={{ padding: 12, borderTop: '1px solid #eee' }}><input value={newMessage} onChange={(e) => setNewMessage(e.target.value)} placeholder="Type..." style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 20 }} /></div></div>)}
    </div>
  );
}
