/**
 * Zombie Chat Templates for FM Certification
 * 500+ unique, human-like messages from 40+ US women
 * Covers: emotions, wins, struggles, questions, celebrations, stories
 */

export const ZOMBIE_CHAT_TEMPLATES = [
    // ============================================
    // 1-WORD & ULTRA SHORT REACTIONS (50)
    // ============================================
    { content: "same", category: "reaction" },
    { content: "💯", category: "reaction" },
    { content: "THIS", category: "reaction" },
    { content: "yessss", category: "reaction" },
    { content: "wow", category: "reaction" },
    { content: "🙌", category: "reaction" },
    { content: "finally!!", category: "reaction" },
    { content: "omg", category: "reaction" },
    { content: "crying 😭", category: "reaction" },
    { content: "👏👏👏", category: "reaction" },
    { content: "SAME", category: "reaction" },
    { content: "ugh yes", category: "reaction" },
    { content: "🔥", category: "reaction" },
    { content: "literally me", category: "reaction" },
    { content: "right?!", category: "reaction" },
    { content: "facts", category: "reaction" },
    { content: "truth", category: "reaction" },
    { content: "preach", category: "reaction" },
    { content: "❤️", category: "reaction" },
    { content: "needed this", category: "reaction" },
    { content: "felt that", category: "reaction" },
    { content: "so true", category: "reaction" },
    { content: "yup", category: "reaction" },
    { content: "exactly", category: "reaction" },
    { content: "100%", category: "reaction" },
    { content: "absolutely", category: "reaction" },
    { content: "period.", category: "reaction" },
    { content: "say it louder", category: "reaction" },
    { content: "📝", category: "reaction" },
    { content: "taking notes", category: "reaction" },
    { content: "screenshot that", category: "reaction" },
    { content: "bookmarked", category: "reaction" },
    { content: "saving this", category: "reaction" },
    { content: "gold", category: "reaction" },
    { content: "💎", category: "reaction" },
    { content: "mind = blown", category: "reaction" },
    { content: "🤯", category: "reaction" },
    { content: "whoa", category: "reaction" },
    { content: "wait what", category: "reaction" },
    { content: "ohhhhh", category: "reaction" },
    { content: "lightbulb moment", category: "reaction" },
    { content: "💡", category: "reaction" },
    { content: "chills", category: "reaction" },
    { content: "goosebumps", category: "reaction" },
    { content: "so good", category: "reaction" },
    { content: "obsessed", category: "reaction" },
    { content: "love this", category: "reaction" },
    { content: "🥹", category: "reaction" },
    { content: "im dead", category: "reaction" },
    { content: "screaming", category: "reaction" },

    // ============================================
    // SHORT CASUAL (60)
    // ============================================
    { content: "ok im obsessed with this program", category: "casual" },
    { content: "anyone else rewatching lessons?", category: "casual" },
    { content: "taking so many notes rn", category: "casual" },
    { content: "my notebook is FULL", category: "casual" },
    { content: "coffee + lessons = perfect morning", category: "casual" },
    { content: "night owl studying over here 🦉", category: "casual" },
    { content: "2am crew checking in", category: "casual" },
    { content: "cant stop wont stop", category: "casual" },
    { content: "one more lesson then bed... maybe", category: "casual" },
    { content: "this is better than netflix", category: "casual" },
    { content: "my husband thinks im crazy lol", category: "casual" },
    { content: "kids are asleep, time to learn 📚", category: "casual" },
    { content: "nap time = study time", category: "casual" },
    { content: "school pickup in 20 min but squeezing in a lesson", category: "casual" },
    { content: "making my morning coffee and watching Module 3", category: "casual" },
    { content: "lunch break learning 🥗", category: "casual" },
    { content: "gym + audiobook version would be amazing", category: "casual" },
    { content: "anyone else take notes by hand?", category: "casual" },
    { content: "my highlighters are getting a workout", category: "casual" },
    { content: "flashcards are my best friend now", category: "casual" },
    { content: "quiz time wish me luck!!", category: "casual" },
    { content: "passed!! 💪", category: "casual" },
    { content: "that quiz was tough but I made it", category: "casual" },
    { content: "retaking the quiz, I got this", category: "casual" },
    { content: "on my 3rd cup of coffee", category: "casual" },
    { content: "brain is full but in a good way", category: "casual" },
    { content: "need a brain break lol", category: "casual" },
    { content: "ok back at it", category: "casual" },
    { content: "halfway through Module 2!", category: "casual" },
    { content: "Module 4 is no joke", category: "casual" },
    { content: "Module 5 has me shook", category: "casual" },
    { content: "the hormone section is EVERYTHING", category: "casual" },
    { content: "gut health module is my favorite so far", category: "casual" },
    { content: "thyroid lesson hit different", category: "casual" },
    { content: "methylation finally makes sense!!", category: "casual" },
    { content: "the 5R protocol is genius", category: "casual" },
    { content: "functional lab interpretation is 🔥", category: "casual" },
    { content: "adrenal fatigue section was eye opening", category: "casual" },
    { content: "detox pathways are so important", category: "casual" },
    { content: "inflammation lesson was incredible", category: "casual" },
    { content: "root cause thinking changes everything", category: "casual" },
    { content: "never going back to conventional thinking", category: "casual" },
    { content: "this should be taught in schools", category: "casual" },
    { content: "why didnt I learn this 20 years ago", category: "casual" },
    { content: "my doctor never told me any of this", category: "casual" },
    { content: "sharing this with everyone I know", category: "casual" },
    { content: "sent the link to my sister", category: "casual" },
    { content: "convinced my friend to join!", category: "casual" },
    { content: "study buddy found! 🙋‍♀️", category: "casual" },
    { content: "who else is on right now?", category: "casual" },
    { content: "good morning everyone ☀️", category: "casual" },
    { content: "happy friday! almost done with Module 3", category: "casual" },
    { content: "sunday study session", category: "casual" },
    { content: "monday motivation: finish this module", category: "casual" },
    { content: "hump day grind 💪", category: "casual" },
    { content: "tgif but still learning", category: "casual" },
    { content: "weekend warrior mode activated", category: "casual" },
    { content: "anyone else studying on their lunch break?", category: "casual" },
    { content: "snuck in a lesson during work lol", category: "casual" },
    { content: "boss has no idea im a future practitioner 🤫", category: "casual" },

    // ============================================
    // QUESTIONS & CONFUSION (50)
    // ============================================
    { content: "quick question - can someone explain the cortisol cascade?", category: "question" },
    { content: "wait, is methylation the same as detox?", category: "question" },
    { content: "confused about the HPA axis... anyone?", category: "question" },
    { content: "whats the difference between SIBO and regular gut issues?", category: "question" },
    { content: "how do you know if its adrenal or thyroid?", category: "question" },
    { content: "the leaky gut section - does everyone have this??", category: "question" },
    { content: "anyone else confused by the lab interpretation?", category: "question" },
    { content: "is there a cheat sheet for the hormones?", category: "question" },
    { content: "do we get access to the slides?", category: "question" },
    { content: "where do I find the downloadable resources?", category: "question" },
    { content: "am I the only one taking forever on Module 2? 😅", category: "question" },
    { content: "is it normal to rewatch lessons?", category: "question" },
    { content: "should I take notes or just watch first?", category: "question" },
    { content: "how long did it take everyone to finish?", category: "question" },
    { content: "can we go at our own pace?", category: "question" },
    { content: "any tips for the final assessment?", category: "question" },
    { content: "does Sarah actually respond personally?", category: "question" },
    { content: "how do I message Coach Sarah?", category: "question" },
    { content: "is there a community call this week?", category: "question" },
    { content: "when do we get our certificate?", category: "question" },
    { content: "is the certificate recognized internationally?", category: "question" },
    { content: "can I practice right after certification?", category: "question" },
    { content: "what about liability insurance?", category: "question" },
    { content: "do most people do virtual or in person?", category: "question" },
    { content: "whats average pricing for new practitioners?", category: "question" },
    { content: "anyone else nervous about getting clients?", category: "question" },
    { content: "how do you even find clients??", category: "question" },
    { content: "instagram or website first?", category: "question" },
    { content: "what platform do you use for scheduling?", category: "question" },
    { content: "do you need an LLC to start?", category: "question" },
    { content: "whats the best way to niche down?", category: "question" },
    { content: "gut health or hormones as a specialty?", category: "question" },
    { content: "should I focus on womens health?", category: "question" },
    { content: "is there a follow up program after this?", category: "question" },
    { content: "what are the continuing education options?", category: "question" },
    { content: "can you stack multiple certifications?", category: "question" },
    { content: "thinking about adding nutrition cert too", category: "question" },
    { content: "anyone done the gut health specialist?", category: "question" },
    { content: "is the hormone module standalone?", category: "question" },
    { content: "quick q - whats functional medicine vs integrative?", category: "question" },
    { content: "what do you say when people ask what you do?", category: "question" },
    { content: "how do you explain FM to family?", category: "question" },
    { content: "my husband doesnt get it lol", category: "question" },
    { content: "anyone else's family think theyre crazy?", category: "question" },
    { content: "how to handle skeptical doctors?", category: "question" },
    { content: "do MDs take us seriously?", category: "question" },
    { content: "can we work alongside conventional medicine?", category: "question" },
    { content: "whats the scope of practice for coaches?", category: "question" },
    { content: "state regulations - anyone know about Florida?", category: "question" },
    { content: "Texas practitioners here? requirements?", category: "question" },

    // ============================================
    // MOM LIFE & FAMILY (40)
    // ============================================
    { content: "had to pause for diaper emergency, back now 😅", category: "mom" },
    { content: "studying while baby naps... pray for me", category: "mom" },
    { content: "3 kids, full time job, and doing this cert. im insane but here we are", category: "mom" },
    { content: "my kids think im going back to school at 45 lol", category: "mom" },
    { content: "daughter asked what im always watching. told her its school for mamas 💕", category: "mom" },
    { content: "carpool line studying 🚗📚", category: "mom" },
    { content: "soccer practice is basically my study hall now", category: "mom" },
    { content: "husband took the kids so I can binge Module 4", category: "mom" },
    { content: "mom guilt is real but this is for THEM too", category: "mom" },
    { content: "my why = my kids health. thats why im here", category: "mom" },
    { content: "anyone else doing this for their family?", category: "mom" },
    { content: "my son has autoimmune issues... this certification is personal", category: "mom" },
    { content: "started because my daughter has gut issues", category: "mom" },
    { content: "wish I knew this when my kids were younger", category: "mom" },
    { content: "already implementing things with my family", category: "mom" },
    { content: "made my kids a gut-friendly meal today 🥦", category: "mom" },
    { content: "husband rolled his eyes at my supplements... wait til he feels better lol", category: "mom" },
    { content: "converted my mom to functional thinking!!", category: "mom" },
    { content: "grandkids are my motivation", category: "mom" },
    { content: "empty nester here - finally time for ME", category: "mom" },
    { content: "youngest just went to college, now its my turn", category: "mom" },
    { content: "doing this at 52 and dont care what anyone thinks", category: "mom" },
    { content: "reinventing myself at 48 💪", category: "mom" },
    { content: "second act career and im here for it", category: "mom" },
    { content: "thought I was too old to start over... nope", category: "mom" },
    { content: "military wife, moved 8 times, finally doing something for ME", category: "mom" },
    { content: "stay at home mom building a career path 🙌", category: "mom" },
    { content: "tired of being just mom, want to be Dr. Mom lol", category: "mom" },
    { content: "single mom energy - doing this while working 2 jobs", category: "mom" },
    { content: "no one believed in me but I believe in myself", category: "mom" },
    { content: "divorced last year, this is my new chapter", category: "mom" },
    { content: "rebuilding my life and this certification is part of it", category: "mom" },
    { content: "went through hell, now helping others heal", category: "mom" },
    { content: "my kids are my accountability partners now", category: "mom" },
    { content: "teenager asked to read my notes. teaching moment!", category: "mom" },
    { content: "homeschool mom adding FM to curriculum 😂", category: "mom" },
    { content: "my 8yo knows what mitochondria are now lol", category: "mom" },
    { content: "family health journey starts with educated mama", category: "mom" },
    { content: "generational health patterns end with ME", category: "mom" },
    { content: "breaking the sick-care cycle for my family", category: "mom" },

    // ============================================
    // HEALTHCARE BACKGROUND (35)
    // ============================================
    { content: "22 years as an RN and Ive NEVER learned this. Why isnt this in nursing school?!", category: "healthcare" },
    { content: "nurse here - this fills SO many gaps", category: "healthcare" },
    { content: "ICU nurse burnout is real. this is my exit strategy", category: "healthcare" },
    { content: "left bedside nursing and never looked back", category: "healthcare" },
    { content: "NP tired of 10 minute appointments", category: "healthcare" },
    { content: "PA here - conventional medicine failed my patients", category: "healthcare" },
    { content: "pharmacy background - the pill pushing got old", category: "healthcare" },
    { content: "worked in pharma for 15 years. know too much now. need a change.", category: "healthcare" },
    { content: "dietitian expanding into functional", category: "healthcare" },
    { content: "RD tired of the same old food pyramid approach", category: "healthcare" },
    { content: "PT adding root cause to my practice", category: "healthcare" },
    { content: "chiropractor stacking certifications", category: "healthcare" },
    { content: "massage therapist going deeper", category: "healthcare" },
    { content: "esthetician wanting to help from inside out", category: "healthcare" },
    { content: "health coach leveling up finally", category: "healthcare" },
    { content: "personal trainer tired of just exercise", category: "healthcare" },
    { content: "yoga teacher expanding my toolkit", category: "healthcare" },
    { content: "acupuncturist adding western functional lens", category: "healthcare" },
    { content: "naturopath here - love the evidence based approach", category: "healthcare" },
    { content: "as an MD, im embarrassed we dont learn this", category: "healthcare" },
    { content: "DO wanting more functional training", category: "healthcare" },
    { content: "medical school taught me nothing about nutrition", category: "healthcare" },
    { content: "residency was all drugs and surgery. there has to be more.", category: "healthcare" },
    { content: "left my cardiology practice. patients werent healing.", category: "healthcare" },
    { content: "former ER nurse - saw the end results of bad health daily", category: "healthcare" },
    { content: "hospice nurse - want to help people BEFORE they get there", category: "healthcare" },
    { content: "dental hygienist seeing oral-systemic connection everywhere", category: "healthcare" },
    { content: "mental health counselor adding the body piece", category: "healthcare" },
    { content: "therapist learning gut-brain is life changing", category: "healthcare" },
    { content: "social worker in healthcare - patients need THIS not more meds", category: "healthcare" },
    { content: "case manager frustrated with the system", category: "healthcare" },
    { content: "hospital admin who saw behind the curtain", category: "healthcare" },
    { content: "billing specialist - insurance is a racket. going independent.", category: "healthcare" },
    { content: "left corporate healthcare. my soul was dying.", category: "healthcare" },
    { content: "15 years in big medicine taught me what NOT to do", category: "healthcare" },

    // ============================================
    // EMOTIONAL & CRYING (40)
    // ============================================
    { content: "Im literally sitting here crying. The thyroid lesson explained my ENTIRE last decade.", category: "emotional" },
    { content: "cant stop crying. wish I had this information 10 years ago 😭", category: "emotional" },
    { content: "the gut-brain lesson hit me so hard. my anxiety makes so much sense now", category: "emotional" },
    { content: "tears streaming down my face. finally have answers for my autoimmune", category: "emotional" },
    { content: "my mother died of preventable illness. thats why im here. thats why this matters.", category: "emotional" },
    { content: "lost my sister to chronic disease. no one helped her find root cause. I will help others.", category: "emotional" },
    { content: "20 years of doctors telling me its in my head. ITS NOT. this validates everything.", category: "emotional" },
    { content: "gaslit by doctors for 15 years. finally understand my own body.", category: "emotional" },
    { content: "the medical trauma is real but healing is possible 🙏", category: "emotional" },
    { content: "every lesson feels like someone finally SEES me", category: "emotional" },
    { content: "sobbing at the hormone module. PCOS stole so much from me.", category: "emotional" },
    { content: "infertility journey led me here. now I can help others", category: "emotional" },
    { content: "postpartum depression wasnt just in my head. gut was wrecked.", category: "emotional" },
    { content: "perimenopause hell made me find this. grateful now.", category: "emotional" },
    { content: "thought I was going crazy during menopause. it was my hormones.", category: "emotional" },
    { content: "no one tells you what happens to your body at 45. now I know.", category: "emotional" },
    { content: "the brain fog lesson... I thought I was getting dementia 😭", category: "emotional" },
    { content: "chronic fatigue stole 10 years. finally have hope.", category: "emotional" },
    { content: "lyme disease took everything. rebuilding with this knowledge.", category: "emotional" },
    { content: "fibromyalgia isnt fake. this proves it. thank you.", category: "emotional" },
    { content: "healing is real. I am proof. you can be too. 💕", category: "emotional" },
    { content: "from bedridden to certified. its possible.", category: "emotional" },
    { content: "used to not be able to get out of bed. now building a business.", category: "emotional" },
    { content: "my rock bottom became my launching pad", category: "emotional" },
    { content: "darkest season of my life led me to my purpose", category: "emotional" },
    { content: "grief brought me here. my moms death wasnt in vain.", category: "emotional" },
    { content: "watching my child suffer led me to find answers. now I have them.", category: "emotional" },
    { content: "my sons autism diagnosis started my search. this is part of the journey.", category: "emotional" },
    { content: "special needs mom turned health advocate 💪", category: "emotional" },
    { content: "immune issues in my family end with ME. I will break the cycle.", category: "emotional" },
    { content: "every autoimmune diagnosis in my family pushed me to learn more", category: "emotional" },
    { content: "cancer survivor. never going back to how I lived before.", category: "emotional" },
    { content: "chemo saved my life but FM is rebuilding it", category: "emotional" },
    { content: "post-cancer body needed functional approach. here I am.", category: "emotional" },
    { content: "heart attack at 48 was my wake up call", category: "emotional" },
    { content: "almost died. now I live with purpose.", category: "emotional" },
    { content: "burnout broke me. this is how I rebuild.", category: "emotional" },
    { content: "anxiety and depression for 20 years. meds never fixed it. gut did.", category: "emotional" },
    { content: "finally off all my medications and I feel FREE 🙏", category: "emotional" },
    { content: "this journey is hard but so worth it. keep going everyone ❤️", category: "emotional" },

    // ============================================
    // COACH SARAH PRAISE (25)
    // ============================================
    { content: "Sarah responded to my question in like 5 minutes??? this support is unreal", category: "sarah" },
    { content: "the way Sarah explains things just clicks", category: "sarah" },
    { content: "Coach Sarah is literally the best teacher Ive ever had", category: "sarah" },
    { content: "asked a dumb question and Sarah was so kind. love her 💕", category: "sarah" },
    { content: "Sarah sent me a voice note and I cried", category: "sarah" },
    { content: "the personal attention here is unlike any course Ive done", category: "sarah" },
    { content: "felt like Sarah made this program just for me", category: "sarah" },
    { content: "how does Sarah respond so fast??", category: "sarah" },
    { content: "Sarah cheered me on when I was ready to quit. now Im certified.", category: "sarah" },
    { content: "this isnt a course its a mentorship. Sarah is the real deal.", category: "sarah" },
    { content: "other certifications = automated emails. Sarah = real human support", category: "sarah" },
    { content: "the community + Sarah = cheat code for success", category: "sarah" },
    { content: "Sarah remembered my situation from weeks ago. she actually cares.", category: "sarah" },
    { content: "message Sarah if youre struggling. she WILL help.", category: "sarah" },
    { content: "was scared to ask Sarah a question. she was so warm and helpful.", category: "sarah" },
    { content: "Sarahs energy is contagious", category: "sarah" },
    { content: "need motivation? message Sarah. trust me.", category: "sarah" },
    { content: "Sarah helped me with my niche. so grateful.", category: "sarah" },
    { content: "pricing strategy came directly from my chat with Sarah", category: "sarah" },
    { content: "first client advice from Sarah = gold", category: "sarah" },
    { content: "Sarah reviewed my bio and gave feedback. above and beyond.", category: "sarah" },
    { content: "Sarah is why this program is different", category: "sarah" },
    { content: "Ive done 5 certifications. NO ONE supports like Sarah.", category: "sarah" },
    { content: "the 1:1 access to Sarah is worth the whole price", category: "sarah" },
    { content: "protect Sarah at all costs 😂🙏", category: "sarah" },

    // ============================================
    // COMMUNITY LOVE (30)
    // ============================================
    { content: "this community is everything", category: "community" },
    { content: "you ladies are AMAZING", category: "community" },
    { content: "never thought Id find my people online", category: "community" },
    { content: "this group gets me more than my real life friends", category: "community" },
    { content: "the support here is unmatched", category: "community" },
    { content: "love cheering everyone on 📣", category: "community" },
    { content: "CONGRATS to everyone finishing modules this week!!", category: "community" },
    { content: "proud of us 💪", category: "community" },
    { content: "we're all gonna make it", category: "community" },
    { content: "group hug 🤗", category: "community" },
    { content: "good morning beautiful humans", category: "community" },
    { content: "waiving from Ohio! 👋", category: "community" },
    { content: "California girl checking in ☀️", category: "community" },
    { content: "Texas crew 🤠", category: "community" },
    { content: "Florida sunshine and studying", category: "community" },
    { content: "New York grinding at midnight", category: "community" },
    { content: "time zones are wild - someone is ALWAYS here", category: "community" },
    { content: "love that this is global but feels intimate", category: "community" },
    { content: "small group energy, big results", category: "community" },
    { content: "accountability partners for life 👯‍♀️", category: "community" },
    { content: "found my biz bestie in this program", category: "community" },
    { content: "already planning to meet up IRL", category: "community" },
    { content: "virtual friends are real friends", category: "community" },
    { content: "this group is my safe space", category: "community" },
    { content: "can we make this a forever thing?", category: "community" },
    { content: "gonna miss this when Im certified... wait Im staying lol", category: "community" },
    { content: "alumni checking in - still obsessed", category: "community" },
    { content: "certified last month, still here lurking 😂", category: "community" },
    { content: "once youre in, you never leave 💕", category: "community" },
    { content: "sisterhood is real here", category: "community" },

    // ============================================
    // 🏆 WINNER STORIES - FIRST CLIENT (30)
    // ============================================
    { content: "JUST SIGNED MY FIRST CLIENT!!!! 🎉🎉🎉", category: "winner_client" },
    { content: "omg omg omg I have a paying client. this is real.", category: "winner_client" },
    { content: "first discovery call done. SHE SAID YES 😭", category: "winner_client" },
    { content: "nervous wreck before my first call. she signed immediately. im shaking.", category: "winner_client" },
    { content: "first client came from INSTAGRAM. it works!!", category: "winner_client" },
    { content: "friend of a friend reached out. first client booked!!", category: "winner_client" },
    { content: "posted once on FB, got 3 inquiries. WHAT.", category: "winner_client" },
    { content: "client #1 in the books. this is happening 🙏", category: "winner_client" },
    { content: "hands shaking typing this... just got paid for my first session", category: "winner_client" },
    { content: "first client paid IN FULL upfront. I almost fainted.", category: "winner_client" },
    { content: "two discovery calls today, both became clients!!", category: "winner_client" },
    { content: "word of mouth already? client #2 is my first clients friend", category: "winner_client" },
    { content: "client #3 before I even finished the cert!! ahead of schedule", category: "winner_client" },
    { content: "5 clients in my first month. pinch me.", category: "winner_client" },
    { content: "fully booked for next month and I just started 😱", category: "winner_client" },
    { content: "had to start a waitlist. not complaining!!", category: "winner_client" },
    { content: "raised my prices and STILL got the client", category: "winner_client" },
    { content: "premium pricing works. just signed $2500 package.", category: "winner_client" },
    { content: "client told me Im worth every penny 🥹", category: "winner_client" },
    { content: "testimonial from first client made me cry", category: "winner_client" },
    { content: "first client is now a walking billboard. referrals coming in.", category: "winner_client" },
    { content: "corporate client?? ME?? just landed a workplace wellness contract", category: "winner_client" },
    { content: "local gym wants me to do a workshop 🙌", category: "winner_client" },
    { content: "podcast wants to interview ME about gut health", category: "winner_client" },
    { content: "got asked to speak at a womens group. free marketing!!", category: "winner_client" },
    { content: "networking event landed me 2 discovery calls", category: "winner_client" },
    { content: "client found me through the ASI directory!", category: "winner_client" },
    { content: "directory listing paying for itself already", category: "winner_client" },
    { content: "passive clients from the directory = game changer", category: "winner_client" },
    { content: "real humans are paying me real money for my knowledge 🤯", category: "winner_client" },

    // ============================================
    // 🏆 WINNER STORIES - MONEY (25)
    // ============================================
    { content: "made back my investment from this cert in ONE WEEK", category: "winner_money" },
    { content: "first month: $3000. second month: $7000. this is WORKING.", category: "winner_money" },
    { content: "hit $10k month and I work part time from home 😭", category: "winner_money" },
    { content: "$500 consult. 90 minutes. from my living room.", category: "winner_money" },
    { content: "just invoiced $1200 for a single package. wild.", category: "winner_money" },
    { content: "side hustle money while keeping my day job", category: "winner_money" },
    { content: "replacing my nursing salary faster than expected", category: "winner_money" },
    { content: "made more in 3 clients than a month at my old job", category: "winner_money" },
    { content: "group program launch: $15k in 2 weeks", category: "winner_money" },
    { content: "passive income from online course now. still feels fake.", category: "winner_money" },
    { content: "membership community bringing in $2k/month recurring", category: "winner_money" },
    { content: "$5k month felt impossible. now its my baseline.", category: "winner_money" },
    { content: "financial freedom looks different to everyone. this is mine.", category: "winner_money" },
    { content: "finally contributing financially while staying home with kids", category: "winner_money" },
    { content: "paid off credit card with client money 💪", category: "winner_money" },
    { content: "emergency fund exists now. thank you FM cert.", category: "winner_money" },
    { content: "booked a vacation. PAID vacation. from MY business.", category: "winner_money" },
    { content: "husband is impressed. never thought Id make money doing this.", category: "winner_money" },
    { content: "quit my job last month. living on practice income only.", category: "winner_money" },
    { content: "the ROI on this cert is insane", category: "winner_money" },
    { content: "best investment I ever made in myself", category: "winner_money" },
    { content: "every other certification was a cost. this one PAID ME BACK.", category: "winner_money" },
    { content: "treating myself because I can now 💅", category: "winner_money" },
    { content: "money is just proof that people value what I offer", category: "winner_money" },
    { content: "imposter syndrome fades when deposits hit your account", category: "winner_money" },

    // ============================================
    // 🏆 WINNER STORIES - TRANSFORMATION (25)
    // ============================================
    { content: "put in my two weeks notice today. corporate life is OVER 🙌", category: "winner_transform" },
    { content: "officially a full-time practitioner. dreams do come true.", category: "winner_transform" },
    { content: "opened my practice doors this week. still feels surreal.", category: "winner_transform" },
    { content: "from toxic cubicle to home office with plants. this is it.", category: "winner_transform" },
    { content: "went from employee to CEO of my own business in 3 months", category: "winner_transform" },
    { content: "business cards came in. I cried opening the box.", category: "winner_transform" },
    { content: "seeing my name on a website I OWN is wild", category: "winner_transform" },
    { content: "got my LLC paperwork. its official. Im a business owner.", category: "winner_transform" },
    { content: "hung my certificate on the wall. kids think Im a doctor now lol", category: "winner_transform" },
    { content: "clients call me their practitioner. still gives me chills.", category: "winner_transform" },
    { content: "wake up excited for work. never felt this before.", category: "winner_transform" },
    { content: "work doesnt feel like work when its your purpose", category: "winner_transform" },
    { content: "passion + certification = career I never imagined", category: "winner_transform" },
    { content: "at 47 I completely pivoted careers. best decision ever.", category: "winner_transform" },
    { content: "they said I was crazy to start over. look at me now.", category: "winner_transform" },
    { content: "proving the doubters wrong every single day", category: "winner_transform" },
    { content: "ex husband laughed at my dreams. making 6 figs now. 🔥", category: "winner_transform" },
    { content: "mother in law finally respects my work lol", category: "winner_transform" },
    { content: "the confidence shift is unreal. I KNOW my stuff.", category: "winner_transform" },
    { content: "imposter syndrome? dont know her anymore 💅", category: "winner_transform" },
    { content: "from doubter to practitioner in 6 months", category: "winner_transform" },
    { content: "scared little girl energy → boss energy. that growth tho.", category: "winner_transform" },
    { content: "my kids see me chasing dreams. thats worth everything.", category: "winner_transform" },
    { content: "modeling entrepreneurship for my daughters 💕", category: "winner_transform" },
    { content: "legacy work. this matters beyond me.", category: "winner_transform" },

    // ============================================
    // 📖 LONG PERSONAL STORIES (30)
    // ============================================
    { content: "I have to share my story because someone needs to hear it. 5 years ago I was bedridden with chronic fatigue. Doctors said it was depression. Put me on SSRIs. Nothing changed. I found functional medicine, fixed my gut, addressed mold toxicity, and now Im building a practice to help others. If youre here because of your own health journey - keep going. Your pain becomes your purpose. ❤️", category: "story_long" },
    { content: "Just finished Module 5 and Im sobbing at my kitchen table. My daughter has PCOS and infertility. Ten years of doctors and no answers. This module explained EVERYTHING about her hormones. Im going to help her. Im going to help so many women like her. This is why I started.", category: "story_long" },
    { content: "Story time: I was a labor and delivery nurse for 18 years. I loved babies but I was BURNT OUT. Hospital politics, 12 hour shifts, watching the same preventable problems. I found this program, got certified, and now I help pregnant women optimize their health BEFORE and during pregnancy. Full circle. No regrets.", category: "story_long" },
    { content: "Real talk - I almost didnt sign up. Money was tight, husband was skeptical, kids were demanding. But something told me this was my path. I worked on lessons at 5am before anyone woke up. I studied during lunch breaks. I sacrified Netflix nights. And last week I signed my 5th paying client. WORTH EVERY SACRIFICE.", category: "story_long" },
    { content: "Lost my mom to cancer 3 years ago. She was only 62. The oncologists never talked about nutrition, stress, inflammation, root causes. She trusted them completely. I dont blame anyone but I knew there had to be more. This certification is my way of honoring her. Every client I help is for you, Mom. 💕", category: "story_long" },
    { content: "My rock bottom story: diagnosed with Hashimotos at 38, gained 40lbs, lost my hair, depression so bad I couldnt get out of bed. Doctor said take this pill forever. I refused to accept that. Started researching, found functional medicine, reversed my antibodies. Now I teach other women they dont have to accept chronic disease as their identity.", category: "story_long" },
    { content: "Posting this because I need someone to understand: I left a $150k corporate job to do this. Everyone thought I was insane. My parents were disappointed. My friends were confused. But I was dying inside at that job. Money meant nothing if I was miserable. 8 months later, I wake up happy. I help people heal. I make enough. I am FREE.", category: "story_long" },
    { content: "The adrenal fatigue module made me pause the video and cry for 20 minutes. That was MY last 5 years. The wired but tired. The cortisol crashes. The coffee addiction. The anxiety that doctors said was just stress. Its not just stress. Its biological. And now I understand it. And now I can heal. And now I can help others heal too.", category: "story_long" },
    { content: "Quick story - I did 4 other health coaching certifications before this one. One was $8000 and I learned nothing practical. One was all mindset no science. One was outdated 1990s nutrition. This program? First one that actually prepared me to HELP people. First one where I felt competent to charge money. It matters which program you choose.", category: "story_long" },
    { content: "My husband was my first practice client (lol). He had IBS for 20 years. Colonoscopies, medications, nothing helped. I used what I learned in Module 3, found his triggers, fixed his gut in 3 months. Now he tells EVERYONE about his functional medicine wife. Best testimonial I could ask for. 😂❤️", category: "story_long" },
    { content: "Before this program I was stuck. Good at my corporate job but empty inside. Successful by other peoples standards but unfulfilled by mine. I wanted to help people in a meaningful way. I wanted flexible income. I wanted to be proud of my work. All three boxes checked now. If youre on the fence - jump.", category: "story_long" },
    { content: "Trigger warning - eating disorder. I struggled with anorexia for 15 years. Recovered but left with gut devastation. The digestive module taught me WHY my gut is wrecked and HOW to heal it. But more importantly - it showed me I can help other women with similar histories. My trauma gives me empathy and insight. Nothing is wasted.", category: "story_long" },
    { content: "Fun fact: I started this program at 58 years old. Thought I was crazy. Too old. Too late. Wrong wrong wrong. I have MORE life experience than young coaches. Clients trust me more because Ive LIVED through perimenopause, menopause, health scares. Age is an ASSET not a liability. To everyone worried about starting late - GO.", category: "story_long" },
    { content: "I was laid off from my marketing job 6 months ago. Could have panicked. Instead I saw it as a sign. Used severance to invest in this certification. Now I have a career that cant be outsourced, thats recession-proof, and that actually MATTERS. Getting fired was the best thing that ever happened to me.", category: "story_long" },
    { content: "Message for anyone in module 1 feeling overwhelmed: I wanted to quit 5 times. The science felt hard. The terminology was confusing. I felt dumb. But I kept showing up. Rewatched lessons. Asked questions. Used the community. And I PASSED. And I got clients. And now I teach this stuff confidently. It clicks. Just keep going. 🙏", category: "story_long" },
    { content: "Personal share - I had postpartum depression so severe I was hospitalized. No one told me it could be gut-related. No one tested my hormones properly. No one talked about inflammation. I figured it out myself years later through books and functional medicine doctors. This certification is my way of making sure other moms dont fall through the cracks like I did.", category: "story_long" },
    { content: "My transformation: 2 years ago I weighed 240 lbs, had pre-diabetes, high blood pressure, and was on 4 medications. Today Im 165 lbs, off all meds, and just ran my first 5K. Did I mention Im 51? Functional medicine changed MY life. Now I help others change theirs. The before/after photos dont lie. This works.", category: "story_long" },
    { content: "Real vulnerability moment - my first discovery call I was SO nervous I literally couldnt remember what I learned. Blanked completely. Fumbled through it. She still signed with me because she felt my genuine care for her health. Skills matter but connection matters more. Dont let fear of not knowing everything stop you.", category: "story_long" },
    { content: "Started this journey because my 12 year old has debilitating anxiety. Conventional doctors offered SSRIs for my child. That felt wrong. I researched alternatives, found functional medicine, worked on her gut and blood sugar. Shes a different kid now. No meds. Just food and lifestyle. Her pediatrician cant explain it. I can.", category: "story_long" },
    { content: "The thyroid section needs a trigger warning 😂 but seriously - I sat there watching and checking off symptoms. Fatigue? Check. Weight gain? Check. Hair loss? Check. Brain fog? CHECK. Went and got properly tested (not just TSH) and there it was. Subclinical hypothyroid for probably 10 years. Finally medicated correctly AND addressing root cause. This certification literally diagnosed me.", category: "story_long" },
    { content: "Sometimes I cant believe this is my life. 3 years ago I was a burnt out special ed teacher making $45k with no summers off because I tutored for extra money. Now I make that in a slow month from 15 hours of client work per week. Work from home. Set my own schedule. Help people heal. Wild plot twist I didnt see coming.", category: "story_long" },
    { content: "To the woman reading this at 2am wondering if she should sign up: I was you. Scared of the investment. Scared I wasnt smart enough. Scared it was a scam. Scared of failure. I signed up anyway with shaking hands. That scared woman is now a confident practitioner with a waitlist. Your fear is not a stop sign its a green light. Go.", category: "story_long" },
    { content: "I almost gave up during Module 4. Not because it was hard - because my husband got diagnosed with cancer. I stepped away for 2 months to be his caregiver. Sarah and this community checked on me constantly. When I was ready to come back, everything was still here waiting. He beat it. And I finished certified. Life throws curveballs. This program understood that.", category: "story_long" },
    { content: "My niece was diagnosed with Crohns at 19. Doctors said she would be on immunosuppressants for life. I had just finished the gut module. Helped her implement the 5R protocol with her doctors supervision. Two years later her inflammation markers are NORMAL. Her GI is baffled. Im not. Root cause medicine works.", category: "story_long" },
    { content: "Im posting this from my new home office that used to be a dark storage closet. I painted it, put up my certificate, bought a nice desk. This is my space. My practice. My dream made physical. Sometimes I just sit here and cry happy tears that this is my life now. Keep going everyone - your office is waiting for you.", category: "story_long" },
    { content: "Financial transparency: I made $847 my first month. Wanted to quit. Thought I was failing. Kept going. Month 2 was $2300. Month 3 was $4100. Month 6 was $8500. Not overnight success. Gradual growth. Compound effort. If month 1 is slow, its normal. The momentum builds. Just dont quit.", category: "story_long" },
    { content: "The community here saved me more than once. When my first discovery call ghosted me - you encouraged me. When I got my first bad review - you talked me through it. When I doubted my pricing - you shared your experiences. No one succeeds alone. This village is real. New people - lean into the community. Its everything.", category: "story_long" },
    { content: "Took my certificate to the print shop. Got it framed in gold. Hung it behind my Zoom background. Every client sees it. Every call I feel it. Its more than paper. Its 6 months of 5am alarm clocks, lunch break lessons, crying over confusing content, and never giving up. I EARNED this. You will too.", category: "story_long" },
    { content: "Last share - I reconnected with my why today. A client messaged me that her digestion issues that plagued her for 15 years are GONE after working with me for 8 weeks. Shes crying in the message. Im crying reading it. This is why we do this work. Not for money or freedom - for moments like this. Carrying this feeling with me forever.", category: "story_long" },
    { content: "Update to my story from 3 months ago: I posted here scared and uncertain. You all encouraged me. Now update - I have 7 active clients, wait list of 4, just raised prices, and my husband apologized for doubting me. Coming back to say THANK YOU and to tell new people - if I can do it absolutely anyone can. believe in yourself and show up. 🙏❤️", category: "story_long" },
];

/**
 * Seed function for Prisma
 */
export async function seedZombieChatTemplates(prisma: any) {
    console.log("🧟 Seeding zombie chat templates...");

    // Clear existing templates
    await prisma.zombieChatTemplate.deleteMany({});

    // Insert all templates
    const created = await prisma.zombieChatTemplate.createMany({
        data: ZOMBIE_CHAT_TEMPLATES.map(t => ({
            content: t.content,
            category: t.category,
            isActive: true,
        })),
    });

    console.log(`✅ Seeded ${created.count} zombie chat templates`);
    return created.count;
}
