'use client';
import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import Image from 'next/image';
interface Message { id: string; content: string; senderId: string; receiverId: string; createdAt: string; }
export default function Lesson4Page() {
  const [currentSection, setCurrentSection] = useState(0);
  const [completedSections, setCompletedSections] = useState<number[]>([]);
  const [quickCheckAnswers, setQuickCheckAnswers] = useState<{ [key: number]: string | null }>({});
  const [showAnswers, setShowAnswers] = useState<number[]>([]);
  const [notes, setNotes] = useState('');
  const [showNotes, setShowNotes] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [coachId, setCoachId] = useState<string | null>(null);
  const [currentUserId, setCurrentUserId] = useState<string | null>(null);
  const [showLessonNav, setShowLessonNav] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const lessonData = { module: 1, lessonNumber: 4, totalLessons: 9, title: 'Root Cause vs Symptom Management', readTime: '6 min' };
  const brandColor = '#2D5A4A';
  useEffect(() => { const init = async () => { try { const s = await fetch('/api/auth/session'); const sd = await s.json(); if (sd?.user?.id) setCurrentUserId(sd.user.id); const c = await fetch('/api/coach/assigned'); const cd = await c.json(); if (cd?.coach?.id) setCoachId(cd.coach.id); } catch (e) {} }; init(); }, []);
  useEffect(() => { const n = localStorage.getItem('ih-lesson-4-notes'); if (n) setNotes(n); }, []);
  const handleNotesChange = (v: string) => { setNotes(v); localStorage.setItem('ih-lesson-4-notes', v); };
  const sections = [
    { id: 0, title: 'The Iceberg Analogy', type: 'content', content: (<><h3 style={{ fontSize: 20, color: '#1a1a1a', marginBottom: 16, fontWeight: 600 }}>What You See vs What is Really Happening</h3><p>Think of disease like an iceberg. <strong style={{ color: brandColor }}>Symptoms</strong> are just 10% - visible above the waterline.</p><div style={{ background: '#f0f7f4', padding: 24, borderRadius: 12, margin: '24px 0', textAlign: 'center' }}><div style={{ fontSize: 48 }}>🧊</div><div style={{ fontSize: 14, color: brandColor, marginTop: 8, fontWeight: 600 }}>Below: ROOT CAUSES</div><div style={{ fontSize: 13, color: '#666', marginTop: 8 }}>Inflammation • Toxins • Gut dysfunction • Stress • Nutrient deficiencies</div></div><p>Functional medicine dives deep to address what is below the surface.</p></>) },
    { id: 1, title: 'Case Example', type: 'content', content: (<><h3 style={{ fontSize: 20, color: '#1a1a1a', marginBottom: 16, fontWeight: 600 }}>Same Symptom, Different Causes</h3><p>Three patients with chronic migraines:</p><div style={{ display: 'grid', gap: 12, margin: '20px 0' }}><div style={{ padding: 12, background: '#f9f9f9', borderRadius: 8, borderLeft: '4px solid ' + brandColor }}><strong>Patient A:</strong> Food sensitivity to gluten</div><div style={{ padding: 12, background: '#f9f9f9', borderRadius: 8, borderLeft: '4px solid ' + brandColor }}><strong>Patient B:</strong> Magnesium deficiency</div><div style={{ padding: 12, background: '#f9f9f9', borderRadius: 8, borderLeft: '4px solid ' + brandColor }}><strong>Patient C:</strong> Hormonal imbalance</div></div><p>Conventional: Same prescription for all (pain meds). Functional: <strong style={{ color: brandColor }}>Three different treatment plans</strong>.</p></>) },
    { id: 2, title: 'Quick Check', type: 'quickcheck', question: 'In the iceberg analogy, symptoms represent about what percentage?', options: ['10%', '50%', '75%', '90%'], correct: '10%', explanation: 'Symptoms are just 10% - the tip of the iceberg. Root causes lie below.' },
    { id: 3, title: 'The 5 Whys', type: 'content', content: (<><h3 style={{ fontSize: 20, color: '#1a1a1a', marginBottom: 16, fontWeight: 600 }}>Uncovering Root Causes</h3><p>The 5 Whys technique traces symptoms back to origins:</p><div style={{ background: '#f0f7f4', padding: 20, borderRadius: 12, margin: '20px 0', fontSize: 15 }}><div style={{ marginBottom: 8 }}><strong>Why</strong> joint pain? → Inflammation</div><div style={{ marginBottom: 8 }}><strong>Why</strong> inflammation? → Leaky gut</div><div style={{ marginBottom: 8 }}><strong>Why</strong> leaky gut? → Gluten sensitivity</div><div style={{ marginBottom: 8 }}><strong>Why</strong> dysbiosis? → Multiple antibiotic courses</div><div><strong>Why</strong> antibiotics? → Recurrent UTIs from stress</div></div><p>Now we address the <strong style={{ color: brandColor }}>true origin</strong>: stress management and gut restoration.</p></>) },
    { id: 4, title: 'The Medication Cycle', type: 'content', content: (<><h3 style={{ fontSize: 20, color: '#1a1a1a', marginBottom: 16, fontWeight: 600 }}>When Treatments Create Problems</h3><p>You have seen this pattern:</p><ol style={{ paddingLeft: 20, margin: '20px 0' }}><li>Acid reflux → PPI prescribed</li><li>PPI causes nutrient deficiency → fatigue</li><li>Fatigue → stimulants → anxiety</li><li>Anxiety → benzos → sleep problems</li><li>Now on 4+ meds, original problem unsolved</li></ol><p>Root cause approach: Find <strong style={{ color: brandColor }}>why</strong> there was acid reflux in the first place.</p></>) },
    { id: 5, title: 'Quick Check', type: 'quickcheck', question: 'What technique helps uncover root causes by asking "why" repeatedly?', options: ['The 3 Steps', 'The 5 Whys', 'The 7 Systems', 'Root Analysis'], correct: 'The 5 Whys', explanation: 'The 5 Whys traces symptoms back to their true origins by asking why repeatedly.' },
  ];
  const totalSections = sections.length;
  const progress = Math.round((completedSections.length / totalSections) * 100);
  const moduleProgress = Math.round((lessonData.lessonNumber / lessonData.totalLessons) * 100);
  const handleContinue = () => { if (!completedSections.includes(currentSection)) setCompletedSections([...completedSections, currentSection]); if (currentSection < totalSections - 1) { setCurrentSection(currentSection + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); } };
  const handleQuickCheck = (id: number, a: string) => setQuickCheckAnswers({ ...quickCheckAnswers, [id]: a });
  const handleCheckAnswer = (id: number) => { if (!showAnswers.includes(id)) setShowAnswers([...showAnswers, id]); };
  const currentSectionData = sections[currentSection];
  const isLastSection = currentSection === totalSections - 1;
  const isQuickCheck = currentSectionData.type === 'quickcheck';
  const canContinue = isQuickCheck ? showAnswers.includes(currentSectionData.id) : true;
  return (
    <div style={{ minHeight: '100vh', background: '#fff', fontFamily: 'Georgia, serif', color: '#2d2d2d' }}>
      <header style={{ background: '#fff', borderBottom: '1px solid #e8e8e8', padding: '16px 24px', position: 'sticky', top: 0, zIndex: 100 }}><div style={{ maxWidth: 640, margin: '0 auto' }}><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}><div style={{ fontSize: 12, color: '#888' }}>Module 1</div><div style={{ flex: 1, height: 6, background: '#f0f0f0', borderRadius: 3 }}><div style={{ height: '100%', width: moduleProgress + '%', background: '#D4AF37', borderRadius: 3 }} /></div><div style={{ fontSize: 12, color: '#888' }}>{lessonData.lessonNumber}/9</div></div><div style={{ display: 'flex', justifyContent: 'space-between' }}><div style={{ fontSize: 15, fontWeight: 600 }}>Lesson {lessonData.lessonNumber}</div><div style={{ fontSize: 13, color: '#888' }}>{lessonData.readTime}</div></div><div style={{ marginTop: 12 }}><div style={{ height: 10, background: '#f0f0f0', borderRadius: 5 }}><div style={{ height: '100%', width: Math.max(progress, 3) + '%', background: brandColor, borderRadius: 5 }} /></div></div></div></header>
      <main style={{ maxWidth: 640, margin: '0 auto', padding: '32px 24px 140px' }}><h1 style={{ fontSize: 26, lineHeight: 1.3, color: '#1a1a1a', marginBottom: 32, fontWeight: 600 }}>{lessonData.title}</h1>{currentSectionData.type === 'content' ? (<div style={{ fontSize: 17, lineHeight: 1.9, color: '#333' }}>{currentSectionData.content}</div>) : (<div style={{ background: '#f0f7f4', border: '1px solid #d4e8df', borderRadius: 16, padding: 28 }}><p style={{ fontSize: 18, fontWeight: 500, marginBottom: 24 }}>{currentSectionData.question}</p><div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>{currentSectionData.options?.map((o: string) => { const sel = quickCheckAnswers[currentSectionData.id] === o; const cor = o === currentSectionData.correct; const show = showAnswers.includes(currentSectionData.id); return (<button key={o} onClick={() => !show && handleQuickCheck(currentSectionData.id, o)} style={{ padding: '16px', border: '2px solid', borderColor: show ? (cor ? '#10B981' : sel ? '#EF4444' : '#ddd') : (sel ? brandColor : '#ddd'), background: show && cor ? '#D1FAE5' : show && sel && !cor ? '#FEE2E2' : 'white', borderRadius: 10, textAlign: 'left', fontSize: 16 }}>{o}</button>); })}</div>{quickCheckAnswers[currentSectionData.id] && !showAnswers.includes(currentSectionData.id) && (<button onClick={() => handleCheckAnswer(currentSectionData.id)} style={{ marginTop: 20, padding: '16px', background: brandColor, color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, cursor: 'pointer', width: '100%' }}>Check Answer</button>)}{showAnswers.includes(currentSectionData.id) && (<div style={{ marginTop: 20, padding: 16, background: '#D1FAE5', borderRadius: 10 }}><p style={{ margin: 0 }}>{currentSectionData.explanation}</p></div>)}</div>)}<div style={{ marginTop: 40 }}>{!canContinue ? (<p style={{ color: '#888', textAlign: 'center' }}>Answer to continue</p>) : isLastSection ? (<Link href="/integrative-health-mini-diploma/lesson-5" style={{ display: 'block', padding: '18px', background: brandColor, color: 'white', borderRadius: 10, fontSize: 16, fontWeight: 600, textAlign: 'center', textDecoration: 'none' }}>Continue to Lesson 5 →</Link>) : (<button onClick={handleContinue} style={{ width: '100%', padding: '18px', background: brandColor, color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, cursor: 'pointer' }}>Continue →</button>)}</div></main>
      <div style={{ position: 'fixed', bottom: 24, right: 24, display: 'flex', flexDirection: 'column', gap: 12, zIndex: 100 }}><button onClick={() => setShowNotes(!showNotes)} style={{ width: 56, height: 56, borderRadius: '50%', background: showNotes ? brandColor : 'white', color: showNotes ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>📝</button><button onClick={() => setShowChat(!showChat)} style={{ width: 56, height: 56, borderRadius: '50%', background: showChat ? brandColor : 'white', color: showChat ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>💬</button></div>
      {showNotes && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 320, background: 'white', border: '1px solid #e8e8e8', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100 }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0', display: 'flex', justifyContent: 'space-between' }}><span>📝 Notes</span><button onClick={() => setShowNotes(false)} style={{ background: 'none', border: 'none', color: 'white', cursor: 'pointer' }}>×</button></div><div style={{ padding: 16 }}><textarea value={notes} onChange={(e) => handleNotesChange(e.target.value)} placeholder="Take notes..." style={{ width: '100%', height: 200, border: '1px solid #ddd', borderRadius: 8, padding: 12, fontSize: 15, resize: 'none' }} /></div></div>)}
      {showChat && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 340, height: 400, background: 'white', border: '1px solid #e8e8e8', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100, display: 'flex', flexDirection: 'column' }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><Image src="/coaches/sarah-coach.webp" alt="Sarah" width={32} height={32} style={{ borderRadius: '50%' }} /><span>Chat with Sarah</span></div><button onClick={() => setShowChat(false)} style={{ background: 'none', border: 'none', color: 'white', cursor: 'pointer' }}>×</button></div><div style={{ flex: 1, padding: 16, overflowY: 'auto' }}><div style={{ textAlign: 'center', color: '#888', padding: 40 }}>👋 Ask me anything!</div></div><div style={{ padding: 12, borderTop: '1px solid #eee' }}><input type="text" value={newMessage} onChange={(e) => setNewMessage(e.target.value)} placeholder="Type..." style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 20 }} /></div></div>)}
    </div>
  );
}
