import prisma from "../src/lib/prisma";

const FM_PRODUCTS = [
    // Core Programs
    {
        title: "FM 4-Week Jumpstart Program",
        slug: "fm-4-week-jumpstart",
        description: "A simple, fast, universal program that delivers quick wins for your clients. Perfect for intro offers, add-on programs, or getting new clients started on their functional medicine journey.",
        shortDescription: "Quick wins in just 4 weeks - perfect for intro offers",
        price: 397,
        compareAtPrice: 497,
        productType: "CORE_PROGRAM",
        category: "functional-medicine",
        duration: "4-Week",
        sessionsCount: 4,
        materialsCount: 15,
        isFeatured: true,
        isBestseller: false,
        sortOrder: 1,
        features: [
            "Week-by-week session guides",
            "4 complete session scripts (60-90 min each)",
            "Client intake form",
            "Food & mood journal template",
            "Shopping list template",
            "Daily habits tracker",
            "4 weekly client guides (PDFs)",
            "10 quick reference handouts",
            "Discovery call script",
            "Check-in question templates",
            "Graduation call script",
            "Sales page copy template",
            "3 social media promo posts",
            "Email sequence (3 emails)",
            "Program overview PDF",
        ],
        highlights: [
            "Ready to use immediately",
            "Perfect for new coaches",
            "High conversion intro offer",
            "Templates load into Coach Workspace",
        ],
    },
    {
        title: "FM 8-Week Complete Transformation",
        slug: "fm-8-week-transformation",
        description: "Your core coaching system - the complete 8-week functional medicine transformation program. Includes everything from detox prep to optimization, with full session scripts, client materials, and marketing bundle.",
        shortDescription: "The complete FM transformation - your core offer",
        price: 697,
        compareAtPrice: 897,
        productType: "CORE_PROGRAM",
        category: "functional-medicine",
        duration: "8-Week",
        sessionsCount: 8,
        materialsCount: 35,
        isFeatured: true,
        isBestseller: true,
        sortOrder: 2,
        features: [
            "Complete 8-week program curriculum",
            "8 session scripts (90 min each)",
            "Week 1-2: Assessment & Detox Prep",
            "Week 3-4: Elimination & Reset",
            "Week 5-6: Reintroduction & Testing",
            "Week 7-8: Optimization & Maintenance",
            "In-depth health history questionnaire",
            "Symptom assessment (before/during/after)",
            "Complete elimination diet guide",
            "Reintroduction protocol worksheet",
            "4-phase meal plans",
            "Recipe book (20+ recipes)",
            "Supplement guide",
            "Sleep optimization worksheet",
            "Stress management toolkit",
            "8 weekly client guide PDFs",
            "Progress photo tracker",
            "Mid-program check-in script",
            "Accountability framework",
            "Full sales page (long-form copy)",
            "Webinar script",
            "Case study template",
            "5-email nurture sequence",
            "15 social media posts with captions",
            "Lead magnet: '5 Signs You Need a Reset'",
            "Client contract template",
            "Pricing guide",
            "Payment plan template",
        ],
        highlights: [
            "Best-selling program format",
            "Proven transformation system",
            "Complete marketing included",
            "High-ticket conversion ready",
        ],
    },
    {
        title: "FM 12-Week Deep Transformation",
        slug: "fm-12-week-deep-dive",
        description: "The premium high-ticket program for serious clients. A comprehensive 12-week deep dive that covers advanced protocols, lab guidance, and complete business operations for charging premium prices.",
        shortDescription: "Premium high-ticket program for serious clients",
        price: 997,
        compareAtPrice: 1297,
        productType: "CORE_PROGRAM",
        category: "functional-medicine",
        duration: "12-Week",
        sessionsCount: 12,
        materialsCount: 50,
        isFeatured: true,
        isBestseller: false,
        sortOrder: 3,
        features: [
            "Complete 12-week program curriculum",
            "12 session scripts (90 min each)",
            "Phase 1 (Weeks 1-3): Deep Assessment & Prep",
            "Phase 2 (Weeks 4-6): Therapeutic Intervention",
            "Phase 3 (Weeks 7-9): Healing & Repair",
            "Phase 4 (Weeks 10-12): Integration & Sustainment",
            "Comprehensive lab work guide",
            "Functional testing recommendations",
            "15+ detailed protocol worksheets",
            "Complete meal plan library (4 weeks x 3 phases)",
            "Extended recipe book (50+ recipes)",
            "Supplement stacking protocols",
            "Advanced detox guides",
            "Gut healing protocol",
            "Hormone balancing worksheet",
            "Adrenal recovery protocol",
            "Monthly review templates",
            "Long-term maintenance guide",
            "Printable client success workbook",
            "VIP day structure template",
            "Crisis intervention scripts",
            "Partner/family education handout",
            "Doctor communication template",
            "Premium sales page copy",
            "Application form for clients",
            "Sales call script",
            "Objection handling guide",
            "10-email launch sequence",
            "Webinar slides + script",
            "30-day social media calendar",
            "3 different lead magnets",
            "Video testimonial request script",
            "VIP client contract",
            "Payment plan structure",
            "Client onboarding sequence",
            "Offboarding & referral sequence",
            "Feedback survey",
        ],
        highlights: [
            "Charge $2,000-$3,000 per client",
            "Complete high-ticket system",
            "Advanced protocols included",
            "Full business operations kit",
        ],
    },
    {
        title: "FM 6-Month Mastery System",
        slug: "fm-6-month-mastery",
        description: "Your flagship DFY coaching system - everything you need to run a complete functional medicine practice. Includes ALL programs (4, 8, 12-week), group program, VIP options, and full business operations.",
        shortDescription: "Complete practice system - everything included",
        price: 1997,
        compareAtPrice: 2997,
        productType: "CORE_PROGRAM",
        category: "functional-medicine",
        duration: "6-Month",
        sessionsCount: 24,
        materialsCount: 100,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 4,
        features: [
            "ALL 4-Week, 8-Week, 12-Week programs included",
            "Group program version (6-8 clients)",
            "VIP intensive (1-day deep dive)",
            "Maintenance program (monthly check-ins)",
            "3 quick win mini programs",
            "Complete assessment battery",
            "Advanced protocols library (20+ conditions)",
            "Practitioner resource library",
            "Case study database template",
            "Every session scenario covered",
            "Group call facilitation guide",
            "3 workshop templates",
            "Complete website copy (all pages)",
            "Full funnel: Lead Magnet → Nurture → Sales",
            "YouTube/podcast content calendar",
            "Speaking/guest expert pitch template",
            "Affiliate/referral program structure",
            "Complete operations manual",
            "System setup guide",
            "Hiring VA/support guide",
            "Client management SOP",
        ],
        highlights: [
            "EVERYTHING included",
            "Run your entire practice",
            "Multiple program formats",
            "Business systems included",
        ],
    },
    // Specialty Kits
    {
        title: "Detox & Elimination Kit",
        slug: "fm-detox-elimination-kit",
        description: "A focused specialty kit for detoxification and elimination protocols. Perfect as an add-on to your main program or standalone short-term offering.",
        shortDescription: "Comprehensive detox protocol kit",
        price: 147,
        compareAtPrice: 197,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "detox",
        sessionsCount: 2,
        materialsCount: 12,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 10,
        features: [
            "7-day detox protocol",
            "21-day elimination guide",
            "Detox food list",
            "Detox meal plan (7 days)",
            "Supplement recommendations",
            "Daily detox checklist",
            "Detox journal template",
            "Session script for detox coaching",
            "Client handout: What to Expect",
            "Post-detox reintroduction guide",
            "Marketing: 3 social posts",
            "Email promo sequence",
        ],
        highlights: [
            "Quick add-on offer",
            "High demand topic",
            "Easy to sell",
            "Complete protocol",
        ],
    },
    {
        title: "Gut Reset Kit",
        slug: "fm-gut-reset-kit",
        description: "Everything you need to offer a focused gut healing program to your clients. Includes the 4R protocol (Remove, Replace, Reinoculate, Repair) with complete materials.",
        shortDescription: "Complete 4R gut healing protocol",
        price: 247,
        compareAtPrice: 347,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "gut-health",
        sessionsCount: 4,
        materialsCount: 18,
        isFeatured: false,
        isBestseller: true,
        sortOrder: 11,
        features: [
            "Complete 4R Protocol Guide",
            "Phase 1: Remove (foods, pathogens)",
            "Phase 2: Replace (digestive support)",
            "Phase 3: Reinoculate (probiotics)",
            "Phase 4: Repair (gut lining)",
            "Gut healing meal plan",
            "Gut-friendly recipe collection",
            "Supplement protocol",
            "Gut symptom tracker",
            "Bristol stool chart guide",
            "Food sensitivity tracking sheet",
            "4 session scripts",
            "Gut health assessment form",
            "Client education handouts",
            "Marketing kit (5 posts, emails)",
            "Lead magnet: 'Is Your Gut Holding You Back?'",
            "Sales page section copy",
            "Pricing recommendations",
        ],
        highlights: [
            "Always in demand",
            "Complete 4R protocol",
            "Proven results",
            "High conversion kit",
        ],
    },
    {
        title: "Hormone Balance Kit",
        slug: "fm-hormone-balance-kit",
        description: "Focused hormone balancing kit for women experiencing PMS, perimenopause, or estrogen/progesterone imbalances. Complete with protocols and client materials.",
        shortDescription: "Women's hormone balancing protocols",
        price: 197,
        compareAtPrice: 297,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "hormones",
        sessionsCount: 3,
        materialsCount: 15,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 12,
        features: [
            "Hormone assessment questionnaire",
            "Cycle tracking guide",
            "Estrogen dominance protocol",
            "Progesterone support plan",
            "Hormone-balancing meal plan",
            "Seed cycling guide",
            "Supplement recommendations",
            "Lifestyle optimization checklist",
            "Sleep & stress impact handout",
            "3 session scripts",
            "Client tracking worksheets",
            "Marketing materials",
            "Lead magnet: 'Hormone Health Checklist'",
            "Sales copy snippet",
            "Testimonial request template",
        ],
        highlights: [
            "Growing demand",
            "Women's health focus",
            "Comprehensive protocols",
            "Easy to deliver",
        ],
    },
    {
        title: "Menopause Support Kit",
        slug: "fm-menopause-support-kit",
        description: "Specialized kit for supporting women through perimenopause and menopause with functional medicine approaches to symptoms, nutrition, and lifestyle.",
        shortDescription: "Complete menopause support system",
        price: 147,
        compareAtPrice: 197,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "menopause",
        sessionsCount: 2,
        materialsCount: 12,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 13,
        features: [
            "Menopause symptom assessment",
            "Nutrition for menopause guide",
            "Hot flash management protocol",
            "Sleep support strategies",
            "Bone health protocol",
            "Weight management guide",
            "Supplement recommendations",
            "Lifestyle modifications",
            "2 session scripts",
            "Client education materials",
            "Marketing kit",
            "Lead magnet template",
        ],
        highlights: [
            "Huge market",
            "Underserved niche",
            "Passionate audience",
            "Easy add-on sale",
        ],
    },
    {
        title: "Blood Sugar Balance Kit",
        slug: "fm-blood-sugar-kit",
        description: "Comprehensive blood sugar and insulin management kit with protocols, meal plans, and tracking tools for clients dealing with blood sugar dysregulation.",
        shortDescription: "Blood sugar & insulin protocols",
        price: 147,
        compareAtPrice: 197,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "blood-sugar",
        sessionsCount: 2,
        materialsCount: 10,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 14,
        features: [
            "Blood sugar assessment",
            "Glycemic index guide",
            "Low-glycemic meal plan",
            "Blood sugar tracking sheet",
            "Pre-diabetes prevention protocol",
            "Supplement recommendations",
            "Exercise recommendations",
            "2 session scripts",
            "Client handouts",
            "Marketing materials",
        ],
        highlights: [
            "Epidemic-level need",
            "Easy to explain",
            "Quick wins visible",
            "Upsell to full program",
        ],
    },
    {
        title: "Cortisol & Adrenal Recovery Kit",
        slug: "fm-adrenal-recovery-kit",
        description: "Specialized kit for adrenal fatigue and cortisol dysregulation. Complete with stress assessment, recovery protocols, and lifestyle interventions.",
        shortDescription: "Adrenal fatigue & stress recovery",
        price: 247,
        compareAtPrice: 347,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "adrenal",
        sessionsCount: 3,
        materialsCount: 14,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 15,
        features: [
            "Adrenal stress assessment",
            "HPA axis education guide",
            "Adrenal recovery protocol (3 phases)",
            "Stress management techniques",
            "Sleep optimization guide",
            "Adaptogen supplement guide",
            "Adrenal-supportive meal plan",
            "Nervous system exercises",
            "3 session scripts",
            "Tracking worksheets",
            "Client education materials",
            "Marketing kit",
            "Lead magnet: 'Are Your Adrenals Burned Out?'",
            "Sales copy snippet",
        ],
        highlights: [
            "Everyone relates to this",
            "Stress epidemic",
            "High engagement topic",
            "Great testimonial potential",
        ],
    },
    {
        title: "Nervous System Reset Kit",
        slug: "fm-nervous-system-kit",
        description: "Focus on vagal tone, polyvagal theory applications, and nervous system regulation for clients dealing with anxiety, chronic stress, or trauma responses.",
        shortDescription: "Vagal tone & nervous system regulation",
        price: 197,
        compareAtPrice: 247,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "nervous-system",
        sessionsCount: 2,
        materialsCount: 12,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 16,
        features: [
            "Nervous system assessment",
            "Polyvagal theory education",
            "Vagal tone exercises",
            "Breathing techniques guide",
            "Grounding exercises collection",
            "Daily nervous system reset routine",
            "Supplement support options",
            "2 session scripts",
            "Client practice worksheets",
            "Tracking journal",
            "Marketing materials",
            "Lead magnet template",
        ],
        highlights: [
            "Trending topic",
            "Unique offering",
            "Deep transformation",
            "Differentiates you",
        ],
    },
    {
        title: "Weight Loss FM Kit",
        slug: "fm-weight-loss-kit",
        description: "Evidence-based functional medicine approach to weight loss addressing root causes: hormones, gut health, inflammation, and metabolism - not just calories.",
        shortDescription: "Root-cause weight loss approach",
        price: 197,
        compareAtPrice: 297,
        productType: "SPECIALTY_KIT",
        category: "functional-medicine",
        specialty: "weight-loss",
        sessionsCount: 3,
        materialsCount: 15,
        isFeatured: false,
        isBestseller: false,
        sortOrder: 17,
        features: [
            "Weight loss assessment (root causes)",
            "Metabolic factors guide",
            "Anti-inflammatory meal plan",
            "Gut-weight connection protocol",
            "Hormone optimization for weight",
            "Stress-weight connection education",
            "Movement recommendations",
            "Sleep for weight loss guide",
            "3 session scripts",
            "Progress tracking worksheets",
            "Non-scale victories list",
            "Marketing kit",
            "Lead magnet: 'Why Diets Don't Work'",
            "Sales page section",
            "Testimonial request",
        ],
        highlights: [
            "Always in demand",
            "Differentiated approach",
            "Addresses root causes",
            "High conversion",
        ],
    },
];

async function seed() {
    console.log("🌱 Seeding DFY Products...");

    for (const product of FM_PRODUCTS) {
        const existing = await prisma.dFYProduct.findUnique({
            where: { slug: product.slug },
        });

        if (existing) {
            console.log(`  ⏭️  Skipping ${product.title} (already exists)`);
            continue;
        }

        await prisma.dFYProduct.create({
            data: {
                ...product,
                price: product.price,
                compareAtPrice: product.compareAtPrice,
            },
        });
        console.log(`  ✅ Created: ${product.title}`);
    }

    console.log("\n🎉 Seeding complete!");
    console.log(`   Created ${FM_PRODUCTS.length} Functional Medicine products`);
}

seed()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
