#!/usr/bin/env python3
"""
AccrediPro AI Thumbnail Generator v6 - V3 CRO Template Based
2-Step Pipeline: Anthropic (Claude) → WaveSpeed

All prompts generated by Claude AI using v3 CRO examples as reference.
Supports 4 certification levels: Certified, Advanced, Master, Practice

Usage:
    python generate_ai_thumbnails.py "Functional Medicine Practitioner" --level all
    python generate_ai_thumbnails.py "Gut Health Coach" --level certified
"""

import anthropic
import requests
import time
import os
import json
import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime

# =============================================================================
# API CONFIGURATION
# =============================================================================

ANTHROPIC_API_KEYS = [
    os.environ.get("ANTHROPIC_API_KEY_1", ""),
    os.environ.get("ANTHROPIC_API_KEY_2", ""),
]

WAVESPEED_API_KEYS = [
    os.environ.get("WAVESPEED_API_KEY_1", ""),
    os.environ.get("WAVESPEED_API_KEY_2", ""),
    os.environ.get("WAVESPEED_API_KEY_3", ""),
    os.environ.get("WAVESPEED_API_KEY_4", ""),
    os.environ.get("WAVESPEED_API_KEY_5", ""),
]

WAVESPEED_API_BASE = "https://api.wavespeed.ai/api/v3/google/nano-banana-pro/text-to-image"
WAVESPEED_RESULT_BASE = "https://api.wavespeed.ai/api/v3/predictions"

# =============================================================================
# V3 CRO EXAMPLE PROMPTS (From COURSE_THUMB_PROMPTS.md)
# =============================================================================

V3_CRO_EXAMPLES = """
## V3 CRO WINNING TEMPLATE EXAMPLES

These are the approved, high-converting thumbnail prompts. Use these as your reference model for generating new prompts.

### Example 1: Functional Medicine Practitioner
```
Premium course thumbnail. 16:9 aspect ratio. Deep navy blue and gold color palette with professional clinical light. Photorealistic image of confident professional woman in her late 40s, stethoscope, lab coat, intelligent approachable expression, medical credibility evident. Setting: modern functional medicine clinic with health charts, supplements visible, integrative medicine atmosphere. TEXT OVERLAYS: Top banner "INTERNATIONALLY ACCREDITED • 9 CERTIFYING BODIES". Center large elegant serif "CERTIFIED Functional Medicine Practitioner™". Below "$15,000/mo Practitioner Income • 100% Online" in gold. Bottom left corner gold star "★★★★★ 1,247 Reviews". Bottom right certificate corner with official gold seal visible. Medical authority integrative aesthetic with maximum credibility.
```

### Example 2: Christian Life Coach
```
Premium course thumbnail. 16:9 aspect ratio. Warm sunset gold and soft rose color palette with golden hour light. Photorealistic image of confident multiracial woman in her late 40s, professional but warm appearance, holding leather journal, encouraging smile, direct eye contact. Setting: modern church community room with natural wood elements, warm welcoming atmosphere. TEXT OVERLAYS: Top banner "INTERNATIONALLY ACCREDITED • 9 CERTIFYING BODIES". Center large elegant serif "CERTIFIED Christian Life Coach™". Below "$8,400/mo Coaching Income • 100% Online" in gold. Bottom left corner gold star "★★★★★ 743 Reviews". Bottom right certificate corner with official gold seal visible. Professional ministry-ready faith-based leadership aesthetic with maximum credibility.
```

### Example 3: Holistic Nutrition Coach
```
Premium course thumbnail. 16:9 aspect ratio. Fresh forest green and warm gold color palette with bright natural morning light. Photorealistic image of radiant woman in her 40s in bright airy kitchen, holding colorful smoothie bowl, genuine warm smile, glowing healthy skin. Setting: modern kitchen with fresh produce, herbs, natural wood elements, morning sunlight streaming in. TEXT OVERLAYS: Top banner "INTERNATIONALLY ACCREDITED • 9 CERTIFYING BODIES". Center large elegant serif "CERTIFIED Holistic Nutrition Coach™". Below "$12,200/mo Coaching Income • 100% Online" in gold. Bottom left corner gold star "★★★★★ 891 Reviews". Bottom right certificate corner with official gold seal visible. Fresh wellness transformation aesthetic with maximum credibility.
```

### Example 4: Energy Healing Practitioner
```
Premium course thumbnail. 16:9 aspect ratio. Soft purple and gold color palette with ethereal spiritual light. Photorealistic image of serene woman in her 40s, hands in healing position, peaceful expression, soft glowing energy around hands. Setting: calm meditation sanctuary with candles, crystals, soft fabrics, sacred healing space. TEXT OVERLAYS: Top banner "INTERNATIONALLY ACCREDITED • 9 CERTIFYING BODIES". Center large elegant serif "CERTIFIED Energy Healing Practitioner™". Below "$7,800/mo Practitioner Income • 100% Online" in gold. Bottom left corner gold star "★★★★★ 678 Reviews". Bottom right certificate corner with official gold seal visible. Spiritual transformative aesthetic with maximum credibility.
```
"""

# =============================================================================
# 4-LEVEL SYSTEM - HYBRID (Authentic style with subtle progression hints)
# =============================================================================

LEVEL_CONFIG = {
    "certified": {
        "prefix": "Certified",
        "income_multiplier": 1.0,
        "reviews_multiplier": 1.0,
        "hint": "woman in her 40s, warm approachable expression"
    },
    "advanced": {
        "prefix": "Advanced",
        "income_multiplier": 1.4,
        "reviews_multiplier": 1.3,
        "hint": "confident woman in her mid-40s, slightly more polished professional appearance"
    },
    "master": {
        "prefix": "Master",
        "income_multiplier": 1.8,
        "reviews_multiplier": 1.6,
        "hint": "distinguished woman in her late 40s, elegant professional blazer, quietly confident presence"
    },
    "practice": {
        "prefix": "Practice Director",
        "income_multiplier": 2.3,
        "reviews_multiplier": 2.0,
        "hint": "accomplished woman in her 50s, refined executive style, warm leadership presence"
    }
}

LEVEL_ORDER = ["certified", "advanced", "master", "practice"]

# =============================================================================
# MASTER TEMPLATE - HYBRID (Authentic style + subtle level hints)
# =============================================================================

MASTER_TEMPLATE = """You are an expert at creating high-converting course thumbnail image prompts.

{v3_examples}

## YOUR TASK

Generate a prompt for: **{level_prefix} {course_title}™**
- Income: ${income:,}/mo  
- Reviews: {reviews}
- Person hint: {hint}

## CRITICAL RULES:
1. Use EXACTLY the same structure as the examples above
2. Keep the same authentic, natural, photorealistic style
3. DO NOT make it look corporate or overly staged
4. Apply the person hint subtly - just slight touches, nothing extreme
5. Keep the same warm, professional, approachable vibe
6. The setting should still feel natural (NOT corporate boardrooms or executive suites)

Generate ONLY the prompt text. No markdown, no explanations."""


# =============================================================================
# PROMPT GENERATION
# =============================================================================

def generate_prompt(course_name: str, base_income: int, base_reviews: int, 
                    level: str, api_key: str) -> tuple:
    """Generate prompt using v3 CRO examples as reference"""
    
    config = LEVEL_CONFIG[level]
    
    income = int(base_income * config["income_multiplier"])
    reviews = int(base_reviews * config["reviews_multiplier"])
    
    system_prompt = MASTER_TEMPLATE.format(
        v3_examples=V3_CRO_EXAMPLES,
        course_title=course_name,
        level_prefix=config["prefix"],
        income=income,
        reviews=reviews,
        hint=config["hint"]
    )
    
    client = anthropic.Anthropic(api_key=api_key)
    
    try:
        response = client.messages.create(
            model="claude-sonnet-4-5-20250929",
            max_tokens=1000,
            messages=[{"role": "user", "content": system_prompt}]
        )
        prompt = response.content[0].text.strip()
        return prompt, income, reviews
    except Exception as e:
        print(f"❌ Claude API error: {e}")
        return None, income, reviews


# =============================================================================
# WAVESPEED IMAGE GENERATION
# =============================================================================

def submit_wavespeed_request(prompt: str, api_key: str, resolution: str = "2k") -> dict:
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }
    payload = {
        "aspect_ratio": "16:9",
        "enable_base64_output": False,
        "enable_sync_mode": False,
        "output_format": "png",
        "prompt": prompt,
        "resolution": resolution
    }
    response = requests.post(WAVESPEED_API_BASE, headers=headers, json=payload)
    return response.json()


def get_wavespeed_result(request_id: str, api_key: str, max_wait: int = 120) -> dict:
    headers = {"Authorization": f"Bearer {api_key}"}
    url = f"{WAVESPEED_RESULT_BASE}/{request_id}/result"
    
    start_time = time.time()
    while time.time() - start_time < max_wait:
        try:
            response = requests.get(url, headers=headers)
            result = response.json()
            status = result.get("data", {}).get("status", "")
            if status == "completed":
                return result
            elif status == "failed":
                return {"error": "Generation failed"}
            time.sleep(2)
        except:
            time.sleep(2)
    return {"error": "Timeout"}


def download_image(url: str, save_path: str) -> bool:
    try:
        response = requests.get(url, stream=True)
        if response.status_code == 200:
            with open(save_path, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
            return True
    except Exception as e:
        print(f"Download error: {e}")
    return False


# =============================================================================
# FULL PIPELINE
# =============================================================================

def generate_thumbnail(course_name: str, base_income: int, base_reviews: int,
                       level: str, output_dir: str, resolution: str = "2k",
                       anthropic_key: str = None, wavespeed_key: str = None,
                       version: int = 1) -> dict:
    """Generate thumbnail for a single level"""
    
    folder_name = course_name.lower().replace("/", "_").replace(" ", "_").replace("&", "and").strip("_")
    course_dir = os.path.join(output_dir, folder_name)
    os.makedirs(course_dir, exist_ok=True)
    
    config = LEVEL_CONFIG[level]
    
    result = {
        "course": course_name,
        "level": level,
        "folder": folder_name,
        "prompt": None,
        "image_path": None,
        "status": "pending",
        "income": 0,
        "reviews": 0,
        "time_ms": 0
    }
    
    start = time.time()
    
    # STEP 1: Generate prompt
    prompt, income, reviews = generate_prompt(course_name, base_income, base_reviews, level, anthropic_key)
    
    result["income"] = income
    result["reviews"] = reviews
    
    if not prompt:
        result["status"] = "failed"
        result["error"] = "Prompt generation failed"
        return result
    
    result["prompt"] = prompt
    
    # STEP 2: Generate image
    submit_response = submit_wavespeed_request(prompt, wavespeed_key, resolution)
    request_id = submit_response.get("data", {}).get("id")
    
    if not request_id:
        result["status"] = "failed"
        result["error"] = "WaveSpeed submit failed"
        return result
    
    completion = get_wavespeed_result(request_id, wavespeed_key)
    
    if "error" in completion:
        result["status"] = "failed"
        result["error"] = completion["error"]
        return result
    
    outputs = completion.get("data", {}).get("outputs", [])
    if not outputs:
        result["status"] = "failed"
        result["error"] = "No output"
        return result
    
    filename = f"{level}_{folder_name}_v{version}.png"
    save_path = os.path.join(course_dir, filename)
    
    if download_image(outputs[0], save_path):
        result["status"] = "success"
        result["image_path"] = save_path
        result["time_ms"] = int((time.time() - start) * 1000)
    else:
        result["status"] = "failed"
        result["error"] = "Download failed"
    
    return result


def generate_all_levels(course_name: str, base_income: int, base_reviews: int,
                        output_dir: str, resolution: str = "2k", version: int = 1) -> list:
    """Generate all 4 levels for a course IN PARALLEL"""
    
    print(f"\n📚 Generating 4 levels for: {course_name}")
    print(f"   Base: ${base_income:,}/mo | {base_reviews} reviews")
    print(f"   Using V3 CRO template as reference")
    print(f"   🚀 PARALLEL MODE: All 4 levels at once!")
    print("-" * 50)
    
    # Show what will be generated
    for i, level in enumerate(LEVEL_ORDER):
        config = LEVEL_CONFIG[level]
        income = int(base_income * config["income_multiplier"])
        reviews = int(base_reviews * config["reviews_multiplier"])
        print(f"🤖 [{i+1}/4] {level.upper()}: ${income:,}/mo | {reviews} reviews")
    
    print("-" * 50)
    print("⏳ Generating all 4 in parallel...")
    
    results = []
    start_time = time.time()
    
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = {}
        for i, level in enumerate(LEVEL_ORDER):
            anthropic_key = ANTHROPIC_API_KEYS[i % len(ANTHROPIC_API_KEYS)]
            wavespeed_key = WAVESPEED_API_KEYS[i % len(WAVESPEED_API_KEYS)]
            
            future = executor.submit(
                generate_thumbnail,
                course_name, base_income, base_reviews, level,
                output_dir, resolution, anthropic_key, wavespeed_key, version
            )
            futures[future] = level
        
        for i, future in enumerate(as_completed(futures), 1):
            level = futures[future]
            result = future.result()
            results.append(result)
            
            status_icon = "✅" if result["status"] == "success" else "❌"
            time_str = f" ({result['time_ms']}ms)" if result.get('time_ms') else ""
            print(f"   {status_icon} [{i}/4] {level}: {result['status']}{time_str}")
    
    elapsed = time.time() - start_time
    success_count = sum(1 for r in results if r["status"] == "success")
    print("-" * 50)
    print(f"⏱️  Total: {elapsed:.1f}s | ✅ {success_count}/4 success")
    
    return results


def batch_generate(courses: list, output_dir: str, levels: list,
                   resolution: str = "2k", max_parallel: int = 5, version: int = 1) -> list:
    """Batch generate for multiple courses"""
    
    os.makedirs(output_dir, exist_ok=True)
    total_jobs = len(courses) * len(levels)
    
    print(f"\n🚀 AccrediPro AI Thumbnail Generator v6 (V3 CRO Template)")
    print(f"📐 16:9 | Resolution: {resolution}")
    print(f"📁 Output: {output_dir}")
    print(f"🎯 {len(courses)} courses × {len(levels)} levels = {total_jobs} images")
    print("-" * 60)
    
    all_results = []
    start_time = time.time()
    completed = 0
    
    with ThreadPoolExecutor(max_workers=max_parallel) as executor:
        futures = {}
        job_idx = 0
        
        for course in courses:
            for level in levels:
                anthropic_key = ANTHROPIC_API_KEYS[job_idx % len(ANTHROPIC_API_KEYS)]
                wavespeed_key = WAVESPEED_API_KEYS[job_idx % len(WAVESPEED_API_KEYS)]
                
                future = executor.submit(
                    generate_thumbnail,
                    course["name"], course["income"], course["reviews"],
                    level, output_dir, resolution,
                    anthropic_key, wavespeed_key, version
                )
                futures[future] = (course["name"], level)
                job_idx += 1
        
        for future in as_completed(futures):
            course_name, level = futures[future]
            result = future.result()
            all_results.append(result)
            completed += 1
            
            status_icon = "✅" if result["status"] == "success" else "❌"
            time_str = f" ({result['time_ms']}ms)" if result.get('time_ms') else ""
            print(f"\n{status_icon} [{completed}/{total_jobs}] {level}_{result['folder']}: {result['status']}{time_str}")
    
    elapsed = time.time() - start_time
    success_count = sum(1 for r in all_results if r["status"] == "success")
    
    print("\n" + "-" * 60)
    print(f"⏱️  Completed in {elapsed:.1f}s")
    print(f"✅ Success: {success_count}/{total_jobs}")
    
    return all_results


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AI Thumbnail Generator v6 (V3 CRO Template)")
    parser.add_argument("course_name", nargs="?", default=None)
    parser.add_argument("--income", type=int, default=10000)
    parser.add_argument("--reviews", type=int, default=500)
    parser.add_argument("--level", default="all",
                        choices=["certified", "advanced", "master", "practice", "all"])
    parser.add_argument("--resolution", default="2k", choices=["1k", "2k"])
    parser.add_argument("--version", type=int, default=1)
    parser.add_argument("--batch", type=str, default=None)
    parser.add_argument("--category", type=str, default=None)
    parser.add_argument("--max-parallel", type=int, default=5)
    
    args = parser.parse_args()
    
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "generated_ai")
    
    if args.category:
        output_dir = os.path.join(output_dir, args.category)
    
    levels = LEVEL_ORDER if args.level == "all" else [args.level]
    
    if args.batch:
        with open(args.batch, 'r') as f:
            courses = json.load(f)
        results = batch_generate(courses, output_dir, levels, args.resolution, args.max_parallel, args.version)
        
    elif args.course_name:
        if args.level == "all":
            results = generate_all_levels(args.course_name, args.income, args.reviews, output_dir, args.resolution, args.version)
        else:
            result = generate_thumbnail(
                args.course_name, args.income, args.reviews, args.level,
                output_dir, args.resolution, ANTHROPIC_API_KEYS[0], WAVESPEED_API_KEYS[0], args.version
            )
            results = [result]
            status_icon = "✅" if result["status"] == "success" else "❌"
            print(f"\n{status_icon} {result['level']}_{result['folder']}: {result['status']}")
    else:
        print("Usage:")
        print("  python generate_ai_thumbnails.py 'Functional Medicine Practitioner' --level all")
        print("  python generate_ai_thumbnails.py --batch courses.json --level all")
        exit(1)
    
    # Save log
    log_path = os.path.join(output_dir, "generation_log.json")
    os.makedirs(output_dir, exist_ok=True)
    with open(log_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\n📋 Log saved: {log_path}")
