'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';
export default function Lesson9Page() {
  const [currentSection, setCurrentSection] = useState(0);
  const [completedSections, setCompletedSections] = useState<number[]>([]);
  const [quickCheckAnswers, setQuickCheckAnswers] = useState<{ [key: number]: string | null }>({});
  const [showAnswers, setShowAnswers] = useState<number[]>([]);
  const [notes, setNotes] = useState('');
  const [showNotes, setShowNotes] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [newMessage, setNewMessage] = useState('');
  const lessonNumber = 9;
  const brandColor = '#2D5A4A';
  const titles = ['', 'From Burnout to Purpose', 'Why Medicine Falls Short', 'Functional Medicine Model', 'Root Cause Analysis', 'The 5 Pillars', 'Your Clinical Advantage', 'Bridging Two Worlds', 'Case Study: ER to Practice', 'Your Transformation Roadmap'];
  const title = titles[9];
  useEffect(() => { const n = localStorage.getItem('ih-lesson-9-notes'); if (n) setNotes(n); }, []);
  const handleNotesChange = (v: string) => { setNotes(v); localStorage.setItem('ih-lesson-9-notes', v); };
  const content9 = {
    5: [
      { id: 0, type: 'content', title: 'The 5 Pillars Framework', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Foundation of Integrative Health</h3><p>Every successful integrative health intervention addresses these 5 key areas:</p><div style={{ display: 'grid', gap: 12, margin: '20px 0' }}>{['1. Nutrition - Food as medicine', '2. Movement - Exercise and activity', '3. Sleep - Recovery and repair', '4. Stress Management - Mind-body connection', '5. Environment - Toxins and exposures'].map((p, i) => (<div key={i} style={{ padding: 16, background: '#f0f7f4', borderRadius: 8, borderLeft: '4px solid #2D5A4A' }}>{p}</div>))}</div><p>When all 5 pillars are addressed, the body has what it needs to heal.</p></>) },
      { id: 1, type: 'quickcheck', title: 'Quick Check', question: 'How many pillars form the foundation of integrative health?', options: ['3', '5', '7', '10'], correct: '5', explanation: 'The 5 Pillars framework covers all key lifestyle factors.' },
      { id: 2, type: 'content', title: 'Why All 5 Matter', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>The Interconnected System</h3><p>You cannot out-supplement a bad diet. You cannot exercise away chronic stress. All pillars work together.</p><div style={{ background: brandColor, color: 'white', padding: 24, borderRadius: 12, margin: '20px 0' }}><p style={{ margin: 0, fontStyle: 'italic' }}>"When I finally addressed all 5 pillars together, not just nutrition, everything changed for my clients."</p><p style={{ margin: '12px 0 0', fontSize: 14, opacity: 0.9 }}>— Certified Practitioner</p></div></>) },
    ],
    6: [
      { id: 0, type: 'content', title: 'Your Healthcare Background', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Your Unique Advantage</h3><p>As a healthcare professional, you have skills that take others years to develop:</p><div style={{ display: 'grid', gap: 12, margin: '20px 0' }}>{['Clinical assessment expertise', 'Medical literacy and lab interpretation', 'Patient communication skills', 'Crisis management ability', 'Instant credibility with clients'].map((s, i) => (<div key={i} style={{ display: 'flex', gap: 12, padding: 12, background: '#f9f9f9', borderRadius: 8 }}><span style={{ color: brandColor, fontWeight: 600 }}>✓</span><span>{s}</span></div>))}</div></>) },
      { id: 1, type: 'quickcheck', title: 'Quick Check', question: 'What gives healthcare workers an advantage in integrative health?', options: ['Lower certification costs', 'Clinical assessment skills', 'Marketing experience', 'Tech knowledge'], correct: 'Clinical assessment skills', explanation: 'Your clinical training is a massive advantage - you already know how to evaluate patients.' },
      { id: 2, type: 'content', title: 'Transferable Skills', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Building on What You Know</h3><p>You are not starting from zero. You are adding new tools to an already impressive toolkit.</p><p style={{ marginTop: 16 }}>Your clinical experience means you can:</p><ul style={{ paddingLeft: 20 }}><li>Identify red flags that require referral</li><li>Read and interpret lab work</li><li>Communicate complex concepts simply</li><li>Build trust quickly with clients</li></ul></>) },
    ],
    7: [
      { id: 0, type: 'content', title: 'Integrating Both Worlds', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Conventional + Integrative</h3><p>The best practitioners do not reject conventional medicine - they enhance it. You will learn to:</p><div style={{ display: 'grid', gap: 12, margin: '20px 0' }}>{['Work alongside conventional providers', 'Know when to refer out', 'Complement medical treatments', 'Fill gaps in conventional care'].map((s, i) => (<div key={i} style={{ padding: 12, background: '#f0f7f4', borderRadius: 8, borderLeft: '4px solid ' + brandColor }}>{s}</div>))}</div></>) },
      { id: 1, type: 'quickcheck', title: 'Quick Check', question: 'How do integrative practitioners work with conventional medicine?', options: ['Replace it entirely', 'Ignore it', 'Enhance and complement it', 'Compete with it'], correct: 'Enhance and complement it', explanation: 'The best approach bridges both worlds - using the strengths of each.' },
      { id: 2, type: 'content', title: 'Building Referral Networks', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>The Healthcare Team</h3><p>Successful practitioners build networks:</p><ul style={{ paddingLeft: 20, margin: '20px 0' }}><li>Primary care physicians</li><li>Specialists who are open-minded</li><li>Other integrative practitioners</li><li>Mental health professionals</li></ul><p>Your healthcare background makes these relationships easier to build.</p></>) },
    ],
    8: [
      { id: 0, type: 'content', title: 'Meet Jennifer', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>From ER Nurse to Practitioner</h3><div style={{ background: '#f0f7f4', padding: 24, borderRadius: 12, margin: '20px 0' }}><p><strong>Background:</strong> 15 years as ER nurse, severe burnout</p><p><strong>Turning point:</strong> Started learning functional medicine for her own health issues</p><p><strong>Transition:</strong> Completed certification while still working part-time</p><p style={{ margin: 0 }}><strong>Now:</strong> Full practice, 25 clients/month, works from home, earns more than nursing salary</p></div></>) },
      { id: 1, type: 'content', title: 'The Journey', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Her Path</h3><div style={{ display: 'flex', flexDirection: 'column', gap: 12, margin: '20px 0' }}>{['Month 1-3: Started certification, kept nursing job', 'Month 4-6: Began seeing clients on weekends', 'Month 7-9: Reduced nursing hours as practice grew', 'Month 10-12: Transitioned full-time to practice'].map((s, i) => (<div key={i} style={{ display: 'flex', gap: 12, padding: 12, background: '#f9f9f9', borderRadius: 8 }}><span style={{ background: brandColor, color: 'white', borderRadius: '50%', width: 24, height: 24, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, flexShrink: 0 }}>{i+1}</span><span>{s}</span></div>))}</div></>) },
      { id: 2, type: 'quickcheck', title: 'Quick Check', question: 'How long did Jennifers transition take?', options: ['3 months', '6 months', '12 months', '24 months'], correct: '12 months', explanation: 'Many practitioners transition gradually over 12 months while maintaining income security.' },
    ],
    9: [
      { id: 0, type: 'content', title: 'Your Next Steps', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Congratulations!</h3><p>You have completed Module 1: Foundations of Integrative Health. You now understand:</p><div style={{ display: 'grid', gap: 8, margin: '20px 0' }}>{['Why conventional medicine struggles with chronic disease', 'The functional medicine model', 'Root cause vs symptom management', 'The 5 pillars of integrative health', 'Your unique clinical advantage', 'How to bridge both worlds'].map((s, i) => (<div key={i} style={{ display: 'flex', gap: 8, padding: 8 }}><span style={{ color: brandColor }}>✓</span><span>{s}</span></div>))}</div></>) },
      { id: 1, type: 'content', title: 'Your Certificate', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Claim Your Mini-Diploma</h3><div style={{ background: 'linear-gradient(135deg, #f0f7f4, white)', border: '2px solid ' + brandColor, padding: 32, borderRadius: 16, textAlign: 'center', margin: '20px 0' }}><div style={{ fontSize: 14, color: '#888', marginBottom: 8 }}>You have earned your</div><div style={{ fontSize: 24, fontWeight: 'bold', color: brandColor, marginBottom: 8 }}>Integrative Health Foundation Certificate</div><div style={{ fontSize: 14, color: '#666' }}>Ready for your full certification journey</div></div></>) },
      { id: 2, type: 'content', title: 'Full Certification', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>Ready for More?</h3><p>The full Integrative Health Practitioner Certification includes:</p><ul style={{ paddingLeft: 20, margin: '20px 0' }}><li>21 comprehensive modules</li><li>Advanced assessment techniques</li><li>Business and marketing training</li><li>Lifetime community access</li><li>9 accrediting bodies recognition</li></ul><div style={{ background: brandColor, color: 'white', padding: 24, borderRadius: 12, textAlign: 'center', margin: '20px 0' }}><div style={{ fontSize: 14, opacity: 0.9, marginBottom: 8 }}>Limited Time Offer</div><div style={{ fontSize: 28, fontWeight: 'bold' }}>Start Your Certification Today</div></div></>) },
    ],
  }[9] || [];
  const sections = content9;
  const totalSections = sections.length;
  const progress = Math.round((completedSections.length / totalSections) * 100);
  const moduleProgress = Math.round((lessonNumber / 9) * 100);
  const handleContinue = () => { if (!completedSections.includes(currentSection)) setCompletedSections([...completedSections, currentSection]); if (currentSection < totalSections - 1) { setCurrentSection(currentSection + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); } };
  const handleQuickCheck = (id: number, a: string) => setQuickCheckAnswers({ ...quickCheckAnswers, [id]: a });
  const handleCheckAnswer = (id: number) => { if (!showAnswers.includes(id)) setShowAnswers([...showAnswers, id]); };
  const currentSectionData = sections[currentSection] || { id: 0, type: 'content', content: <p>Loading...</p> };
  const isLastSection = currentSection === totalSections - 1;
  const isQuickCheck = currentSectionData.type === 'quickcheck';
  const canContinue = isQuickCheck ? showAnswers.includes(currentSectionData.id) : true;
  const nextLesson = lessonNumber < 9 ? '/integrative-health-mini-diploma/lesson-' + (lessonNumber + 1) : '/integrative-health-mini-diploma';
  return (
    <div style={{ minHeight: '100vh', background: '#fff', fontFamily: 'Georgia, serif', color: '#2d2d2d' }}>
      <header style={{ background: '#fff', borderBottom: '1px solid #e8e8e8', padding: '16px 24px', position: 'sticky', top: 0, zIndex: 100 }}><div style={{ maxWidth: 640, margin: '0 auto' }}><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}><div style={{ fontSize: 12, color: '#888' }}>Module 1</div><div style={{ flex: 1, height: 6, background: '#f0f0f0', borderRadius: 3 }}><div style={{ height: '100%', width: moduleProgress + '%', background: '#D4AF37', borderRadius: 3 }} /></div><div style={{ fontSize: 12, color: '#888' }}>{lessonNumber}/9</div></div><div style={{ display: 'flex', justifyContent: 'space-between' }}><div style={{ fontSize: 15, fontWeight: 600 }}>Lesson {lessonNumber}</div></div><div style={{ marginTop: 12 }}><div style={{ height: 10, background: '#f0f0f0', borderRadius: 5 }}><div style={{ height: '100%', width: Math.max(progress, 3) + '%', background: brandColor, borderRadius: 5 }} /></div></div></div></header>
      <main style={{ maxWidth: 640, margin: '0 auto', padding: '32px 24px 140px' }}><h1 style={{ fontSize: 26, lineHeight: 1.3, marginBottom: 32, fontWeight: 600 }}>{title}</h1>{currentSectionData.type === 'content' ? (<div style={{ fontSize: 17, lineHeight: 1.9 }}>{currentSectionData.content}</div>) : (<div style={{ background: '#f0f7f4', border: '1px solid #d4e8df', borderRadius: 16, padding: 28 }}><p style={{ fontSize: 18, fontWeight: 500, marginBottom: 24 }}>{currentSectionData.question}</p><div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>{currentSectionData.options?.map((o: string) => { const sel = quickCheckAnswers[currentSectionData.id] === o; const cor = o === currentSectionData.correct; const show = showAnswers.includes(currentSectionData.id); return (<button key={o} onClick={() => !show && handleQuickCheck(currentSectionData.id, o)} style={{ padding: '16px', border: '2px solid', borderColor: show ? (cor ? '#10B981' : sel ? '#EF4444' : '#ddd') : (sel ? brandColor : '#ddd'), background: show && cor ? '#D1FAE5' : show && sel && !cor ? '#FEE2E2' : 'white', borderRadius: 10, textAlign: 'left', fontSize: 16 }}>{o}</button>); })}</div>{quickCheckAnswers[currentSectionData.id] && !showAnswers.includes(currentSectionData.id) && (<button onClick={() => handleCheckAnswer(currentSectionData.id)} style={{ marginTop: 20, padding: '16px', background: brandColor, color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, cursor: 'pointer', width: '100%' }}>Check Answer</button>)}{showAnswers.includes(currentSectionData.id) && (<div style={{ marginTop: 20, padding: 16, background: '#D1FAE5', borderRadius: 10 }}><p style={{ margin: 0 }}>{currentSectionData.explanation}</p></div>)}</div>)}<div style={{ marginTop: 40 }}>{!canContinue ? (<p style={{ color: '#888', textAlign: 'center' }}>Answer to continue</p>) : isLastSection ? (<Link href={nextLesson} style={{ display: 'block', padding: '18px', background: brandColor, color: 'white', borderRadius: 10, fontSize: 16, fontWeight: 600, textAlign: 'center', textDecoration: 'none' }}>{lessonNumber === 9 ? 'Complete Mini-Diploma' : 'Continue to Lesson ' + (lessonNumber + 1) + ' →'}</Link>) : (<button onClick={handleContinue} style={{ width: '100%', padding: '18px', background: brandColor, color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, cursor: 'pointer' }}>Continue →</button>)}</div></main>
      <div style={{ position: 'fixed', bottom: 24, right: 24, display: 'flex', flexDirection: 'column', gap: 12, zIndex: 100 }}><button onClick={() => setShowNotes(!showNotes)} style={{ width: 56, height: 56, borderRadius: '50%', background: showNotes ? brandColor : 'white', color: showNotes ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>📝</button><button onClick={() => setShowChat(!showChat)} style={{ width: 56, height: 56, borderRadius: '50%', background: showChat ? brandColor : 'white', color: showChat ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>💬</button></div>
      {showNotes && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 320, background: 'white', border: '1px solid #e8e8e8', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100 }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0', display: 'flex', justifyContent: 'space-between' }}><span>📝 Notes</span><button onClick={() => setShowNotes(false)} style={{ background: 'none', border: 'none', color: 'white', cursor: 'pointer' }}>×</button></div><div style={{ padding: 16 }}><textarea value={notes} onChange={(e) => handleNotesChange(e.target.value)} placeholder="Notes..." style={{ width: '100%', height: 200, border: '1px solid #ddd', borderRadius: 8, padding: 12, fontSize: 15, resize: 'none' }} /></div></div>)}
      {showChat && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 340, height: 400, background: 'white', border: '1px solid #e8e8e8', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100, display: 'flex', flexDirection: 'column' }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><Image src="/coaches/sarah-coach.webp" alt="Sarah" width={32} height={32} style={{ borderRadius: '50%' }} /><span>Chat with Sarah</span></div><button onClick={() => setShowChat(false)} style={{ background: 'none', border: 'none', color: 'white', cursor: 'pointer' }}>×</button></div><div style={{ flex: 1, padding: 16, overflowY: 'auto' }}><div style={{ textAlign: 'center', color: '#888', padding: 40 }}>👋 Ask me anything!</div></div><div style={{ padding: 12, borderTop: '1px solid #eee' }}><input type="text" value={newMessage} onChange={(e) => setNewMessage(e.target.value)} placeholder="Type..." style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 20 }} /></div></div>)}
    </div>
  );
}
