'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';
export default function Lesson3Page() {
  const [currentSection, setCurrentSection] = useState(0);
  const [completedSections, setCompletedSections] = useState<number[]>([]);
  const [quickCheckAnswers, setQuickCheckAnswers] = useState<{ [key: number]: string | null }>({});
  const [showAnswers, setShowAnswers] = useState<number[]>([]);
  const [notes, setNotes] = useState('');
  const [showNotes, setShowNotes] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [newMessage, setNewMessage] = useState('');
  const lessonNumber = 3;
  const brandColor = '#2D5A4A';
  const accentColor = '#D4AF37';
  const title = 'The R.O.O.T.S. Framework Overview';
  useEffect(() => { const n = localStorage.getItem('roots-lesson-3-notes'); if (n) setNotes(n); }, []);
  const handleNotesChange = (v: string) => { setNotes(v); localStorage.setItem('roots-lesson-3-notes', v); };
  const sections = [
    { id: 0, type: 'content', title: 'The Complete Framework', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>R.O.O.T.S. — Your Complete System</h3><p>The R.O.O.T.S. Method™ is a <strong style={{ color: brandColor }}>proprietary 5-step framework</strong> for identifying and addressing root causes of chronic health issues.</p><div style={{ display: 'grid', gap: 16, margin: '24px 0' }}>{[{ letter: 'R', name: 'Recognize the Pattern', desc: 'See what conventional medicine misses in symptom clusters' }, { letter: 'O', name: 'Find the Origin', desc: 'Trace symptoms back to their true source using the 5 Whys' }, { letter: 'O', name: 'Optimize the Foundations', desc: 'Address the 5 pillars: nutrition, movement, sleep, stress, environment' }, { letter: 'T', name: 'Transform with Coaching', desc: 'Guide lasting behavioral change using proven frameworks' }, { letter: 'S', name: 'Scale Your Practice', desc: 'Build a profitable, sustainable business model' }].map((item, i) => (<div key={i} style={{ display: 'flex', gap: 16, padding: 20, background: '#f8f9fa', borderRadius: 12 }}><div style={{ width: 56, height: 56, borderRadius: 12, background: 'linear-gradient(135deg, ' + brandColor + ', ' + accentColor + ')', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 28, fontWeight: 'bold', flexShrink: 0 }}>{item.letter}</div><div><div style={{ fontWeight: 600, fontSize: 17, color: '#1a1a1a' }}>{item.name}</div><div style={{ fontSize: 14, color: '#666', marginTop: 4 }}>{item.desc}</div></div></div>))}</div></>) },
    { id: 1, type: 'content', title: 'Why This Works', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>The Science Behind R.O.O.T.S.</h3><p>Each letter represents a <strong style={{ color: brandColor }}>crucial step</strong> that most practitioners skip:</p><div style={{ display: 'grid', gap: 12, margin: '20px 0' }}><div style={{ display: 'flex', gap: 16, padding: 16, background: '#fee2e2', borderRadius: 8 }}><span style={{ fontSize: 20 }}>❌</span><div><strong>Without R.O.O.T.S.:</strong> Random supplements, generic protocols, frustrated clients who don't get better</div></div><div style={{ display: 'flex', gap: 16, padding: 16, background: '#d1fae5', borderRadius: 8 }}><span style={{ fontSize: 20 }}>✅</span><div><strong>With R.O.O.T.S.:</strong> Systematic approach, personalized plans, clients who achieve lasting results</div></div></div></>) },
    { id: 2, type: 'quickcheck', title: 'Quick Check', question: 'What does the first "O" in R.O.O.T.S. stand for?', options: ['Optimize', 'Origin', 'Organize', 'Overcome'], correct: 'Origin', explanation: 'The first "O" stands for "Find the Origin" — tracing symptoms back to their true source, not just managing them.' },
    { id: 3, type: 'content', title: 'The Flow', content: (<><h3 style={{ fontSize: 20, marginBottom: 16, fontWeight: 600 }}>How the Steps Connect</h3><p>R.O.O.T.S. is designed as a <strong style={{ color: brandColor }}>sequential process</strong>:</p><div style={{ background: '#f8f9fa', padding: 24, borderRadius: 12, margin: '20px 0' }}><div style={{ display: 'flex', alignItems: 'center', marginBottom: 12 }}><div style={{ width: 40, height: 40, borderRadius: '50%', background: brandColor, color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>R</div><div style={{ flex: 1, height: 2, background: accentColor, margin: '0 8px' }}></div><div style={{ width: 40, height: 40, borderRadius: '50%', background: brandColor, color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>O</div><div style={{ flex: 1, height: 2, background: accentColor, margin: '0 8px' }}></div><div style={{ width: 40, height: 40, borderRadius: '50%', background: brandColor, color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>O</div><div style={{ flex: 1, height: 2, background: accentColor, margin: '0 8px' }}></div><div style={{ width: 40, height: 40, borderRadius: '50%', background: brandColor, color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>T</div><div style={{ flex: 1, height: 2, background: accentColor, margin: '0 8px' }}></div><div style={{ width: 40, height: 40, borderRadius: '50%', background: brandColor, color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>S</div></div><p style={{ textAlign: 'center', margin: 0, fontSize: 14, color: '#666' }}>Each step builds on the previous one</p></div><p>In the next four lessons, we'll deep-dive into each letter of R.O.O.T.S.</p></>) },
  ];
  const totalSections = sections.length;
  const progress = Math.round((completedSections.length / totalSections) * 100);
  const moduleProgress = Math.round((lessonNumber / 9) * 100);
  const handleContinue = () => { if (!completedSections.includes(currentSection)) setCompletedSections([...completedSections, currentSection]); if (currentSection < totalSections - 1) { setCurrentSection(currentSection + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); } };
  const handleQuickCheck = (id: number, a: string) => setQuickCheckAnswers({ ...quickCheckAnswers, [id]: a });
  const handleCheckAnswer = (id: number) => { if (!showAnswers.includes(id)) setShowAnswers([...showAnswers, id]); };
  const currentSectionData = sections[currentSection];
  const isLastSection = currentSection === totalSections - 1;
  const isQuickCheck = currentSectionData.type === 'quickcheck';
  const canContinue = isQuickCheck ? showAnswers.includes(currentSectionData.id) : true;
  return (
    <div style={{ minHeight: '100vh', background: '#fff', fontFamily: 'Georgia, serif' }}>
      <header style={{ background: 'linear-gradient(135deg, #1a1a2e, #16213e)', padding: '16px 24px', position: 'sticky', top: 0, zIndex: 100 }}><div style={{ maxWidth: 640, margin: '0 auto' }}><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}><Image src="/accredipro-logo-full.jpg" alt="AccrediPro" width={32} height={32} style={{ borderRadius: 6 }} /><span style={{ fontSize: 14, color: 'white', fontWeight: 600 }}>R.O.O.T.S. Method™</span><div style={{ flex: 1, height: 6, background: 'rgba(255,255,255,0.2)', borderRadius: 3, marginLeft: 12 }}><div style={{ height: '100%', width: moduleProgress + '%', background: accentColor, borderRadius: 3 }} /></div><span style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>{lessonNumber}/9</span></div><div style={{ display: 'flex', justifyContent: 'space-between', color: 'white' }}><span style={{ fontSize: 14 }}>Lesson {lessonNumber}</span><span style={{ fontSize: 12, opacity: 0.7 }}>6 min</span></div></div></header>
      <main style={{ maxWidth: 640, margin: '0 auto', padding: '32px 24px 140px' }}><h1 style={{ fontSize: 26, lineHeight: 1.3, marginBottom: 32, fontWeight: 600 }}>{title}</h1>{currentSectionData.type === 'content' ? (<div style={{ fontSize: 17, lineHeight: 1.9 }}>{currentSectionData.content}</div>) : (<div style={{ background: '#f8f9fa', border: '1px solid #e9ecef', borderRadius: 16, padding: 28 }}><p style={{ fontSize: 18, fontWeight: 500, marginBottom: 24 }}>{currentSectionData.question}</p><div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>{currentSectionData.options?.map((o: string) => { const sel = quickCheckAnswers[currentSectionData.id] === o; const cor = o === currentSectionData.correct; const show = showAnswers.includes(currentSectionData.id); return (<button key={o} onClick={() => !show && handleQuickCheck(currentSectionData.id, o)} style={{ padding: '16px', border: '2px solid', borderColor: show ? (cor ? '#10B981' : sel ? '#EF4444' : '#ddd') : (sel ? brandColor : '#ddd'), background: show && cor ? '#D1FAE5' : show && sel && !cor ? '#FEE2E2' : 'white', borderRadius: 10, textAlign: 'left', fontSize: 16 }}>{o}</button>); })}</div>{quickCheckAnswers[currentSectionData.id] && !showAnswers.includes(currentSectionData.id) && (<button onClick={() => handleCheckAnswer(currentSectionData.id)} style={{ marginTop: 20, padding: '16px', background: brandColor, color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, width: '100%', cursor: 'pointer' }}>Check Answer</button>)}{showAnswers.includes(currentSectionData.id) && (<div style={{ marginTop: 20, padding: 16, background: '#D1FAE5', borderRadius: 10 }}><p style={{ margin: 0 }}>{currentSectionData.explanation}</p></div>)}</div>)}<div style={{ marginTop: 40 }}>{!canContinue ? (<p style={{ color: '#888', textAlign: 'center' }}>Answer to continue</p>) : isLastSection ? (<Link href="/roots-method/lesson-4" style={{ display: 'block', padding: '18px', background: 'linear-gradient(135deg, ' + brandColor + ', #1a3a2e)', color: 'white', borderRadius: 10, fontSize: 16, fontWeight: 600, textAlign: 'center', textDecoration: 'none' }}>Continue to Lesson 4: R — Recognize the Pattern →</Link>) : (<button onClick={handleContinue} style={{ width: '100%', padding: '18px', background: 'linear-gradient(135deg, ' + brandColor + ', #1a3a2e)', color: 'white', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 600, cursor: 'pointer' }}>Continue →</button>)}</div></main>
      <div style={{ position: 'fixed', bottom: 24, right: 24, display: 'flex', flexDirection: 'column', gap: 12, zIndex: 100 }}><button onClick={() => setShowNotes(!showNotes)} style={{ width: 56, height: 56, borderRadius: '50%', background: showNotes ? brandColor : 'white', color: showNotes ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>📝</button><button onClick={() => setShowChat(!showChat)} style={{ width: 56, height: 56, borderRadius: '50%', background: showChat ? brandColor : 'white', color: showChat ? 'white' : brandColor, border: '2px solid ' + brandColor, cursor: 'pointer', fontSize: 20 }}>💬</button></div>
      {showNotes && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 320, background: 'white', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100 }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0' }}>📝 Notes</div><div style={{ padding: 16 }}><textarea value={notes} onChange={(e) => handleNotesChange(e.target.value)} style={{ width: '100%', height: 200, border: '1px solid #ddd', borderRadius: 8, padding: 12 }} /></div></div>)}
      {showChat && (<div style={{ position: 'fixed', bottom: 100, right: 24, width: 340, height: 400, background: 'white', borderRadius: 16, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', zIndex: 100, display: 'flex', flexDirection: 'column' }}><div style={{ padding: 16, background: brandColor, color: 'white', borderRadius: '16px 16px 0 0', display: 'flex', alignItems: 'center', gap: 10 }}><Image src="/coaches/sarah-coach.webp" alt="Sarah" width={32} height={32} style={{ borderRadius: '50%' }} /><span>Chat with Sarah</span></div><div style={{ flex: 1, padding: 16, textAlign: 'center', color: '#888' }}>🌱 Ask me anything!</div><div style={{ padding: 12, borderTop: '1px solid #eee' }}><input value={newMessage} onChange={(e) => setNewMessage(e.target.value)} placeholder="Type..." style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 20 }} /></div></div>)}
    </div>
  );
}
