import prisma from "../src/lib/prisma";

/**
 * Import all FM Certification reviews from the Reviews_Main_Certification folder
 * Uses zombie profiles with avatars for realistic appearance
 */

const COURSE_SLUG = "functional-medicine-complete-certification";

// All 100 reviews parsed from the markdown files
const allReviews = [
  // Reviews 1-20 (from reviews_sample_20.md)
  { name: "Sarah Mitchell", title: "Life-changing investment in myself", content: "I was burned out after 12 years in the ER. I knew there had to be more to healthcare than just treating symptoms and sending patients home with prescriptions. This certification completely changed my trajectory. Within 3 months of completing the program, I opened my own functional medicine practice from home. The curriculum was thorough but accessible—I never felt lost even though biochemistry wasn't my strong suit. The real game-changer was learning how to actually help people heal, not just manage their conditions. Best investment I've ever made in myself.", rating: 5 },
  { name: "Marcus Johnson", title: "Filled every gap I had", content: "Listen, I was skeptical. Another online certification? But my PT clients kept asking about nutrition, gut health, hormones—stuff I couldn't answer. This course filled every gap I had. The science is legit but explained in a way that actually makes sense. I added functional medicine consultations to my training packages and raised my prices significantly. Nobody complained. In fact, I have a waitlist now. If you're on the fence, just do it.", rating: 5 },
  { name: "Jennifer Walsh", title: "Transformed patient outcomes", content: "As a chiropractor for 15 years, I thought I understood holistic health. This certification showed me how much I was missing. The functional medicine framework gave me the tools to address the root causes my patients were dealing with—not just their spinal issues. I've integrated functional assessments into my practice and it's transformed patient outcomes. The course was well-structured, the content was evidence-based, and the investment paid for itself within weeks.", rating: 5 },
  { name: "Amanda Foster", title: "Gave me purpose and income", content: "I have no medical background. Zero. I was just a mom trying to figure out why my daughter had constant stomach issues that doctors couldn't explain. I took this course thinking it would help me help her—and it did. But I never expected it would become my career. After completing the certification, I started helping other moms in my community. This program gave me purpose, income, and the knowledge to actually make a difference. Can't recommend it enough.", rating: 5 },
  { name: "Robert Chen", title: "Worth every penny", content: "Twenty years behind the pharmacy counter made me realize something was broken in our healthcare system. I was dispensing medications that masked symptoms while patients got sicker. This certification was my escape plan. The curriculum is comprehensive—everything from gut microbiome to mitochondrial function to hormone optimization. More importantly, I actually help people now instead of just handing them pills. Worth every penny.", rating: 5 },
  { name: "Michelle Torres", title: "Career transformation", content: "I never thought I'd be running a successful health practice, but here we are. My yoga students kept asking for nutrition and wellness advice that went beyond what I could offer. This certification filled that gap perfectly. The modules were easy to follow even for someone without a science background. The best part is seeing my clients transform. One woman reversed her prediabetes. Another got off three medications. This isn't just a certification, it's a complete career transformation.", rating: 5 },
  { name: "David Patterson", title: "Never been happier", content: "At 52, I left a corporate job because I was miserable. Everyone thought I was crazy. Took this certification not knowing what to expect. Now I have a thriving virtual practice helping executives like my former self deal with burnout, stress-related health issues, and metabolic dysfunction. I understand their lifestyle because I lived it. The course material is excellent and the business training alone was worth the investment. I've never been happier.", rating: 5 },
  { name: "Lisa Gonzalez", title: "My ticket out", content: "After 8 years as an MA, I was tired of being overlooked and underpaid. This certification was my ticket out. The content is seriously next-level—I learned more in this program than in years of working alongside doctors. Started offering consultations on the side while keeping my day job. Within 4 months, my side income matched my MA salary. The freedom to set my own hours and actually help people—that's what this certification gave me.", rating: 5 },
  { name: "Brian Williams", title: "Life-changing for first responders", content: "Weird background for functional medicine, right? But 20 years on the job wrecked my health, and going down the functional medicine rabbit hole to fix myself led me here. I got certified while still working. Started helping fellow firefighters and first responders with their health issues—sleep problems, stress, metabolic syndrome. Word spread through the department, then to other stations. Now I run workshops for first responders across the state.", rating: 5 },
  { name: "Katherine Brooks", title: "Took my practice to another level", content: "I thought my RD credential was enough. It wasn't. This certification took my practice to a completely different level. The functional medicine framework let me connect dots I never could before—why some patients respond to dietary changes while others don't, how to actually address the root cause instead of just recommending meal plans. Clients are getting off medications, losing weight, and feeling better than they have in decades. This certification separated me from every other dietitian in my city.", rating: 5 },
  { name: "James Ortega", title: "Best decision of my life", content: "Teaching for 18 years taught me patience, communication, and how to explain complex topics simply. Perfect skills for functional medicine, it turns out. I was dealing with my own chronic fatigue and discovered this field trying to heal myself. Took the certification over summer break. Started with a small practice helping teachers and educators—we're all burned out and sick. Put in my resignation last spring. Best decision of my life.", rating: 5 },
  { name: "Stephanie Adams", title: "Transformed how I practice", content: "I already had an NP license, but this certification transformed how I practice. The conventional approach I was trained in felt incomplete—always treating symptoms, never addressing why patients were sick in the first place. Now I run a cash-pay functional medicine practice and patients travel from other states to see me. The course content was rigorous and science-based. Exactly what I needed to practice with confidence.", rating: 5 },
  { name: "Tony Ramirez", title: "Complete game-changer", content: "People come to me for pain relief, but so many of them have underlying issues that massage can't fix. I took this certification to understand the bigger picture and offer more to my clients. Now I do wellness consultations alongside my massage practice. I actually understand what's happening in my clients' bodies now instead of just working on their muscles. Complete game-changer.", rating: 5 },
  { name: "Elizabeth Harper", title: "My redemption", content: "The irony isn't lost on me. I spent 15 years selling medications and now I help people get off them. This certification was my redemption. I saw the inside of the pharmaceutical industry and knew there had to be a better way. The functional medicine approach is everything I wish conventional medicine was. My sales skills translated perfectly to building a practice. If you have the drive, this certification gives you everything else.", rating: 5 },
  { name: "Sandra Kim", title: "Finally sustainable practice", content: "I've practiced Chinese medicine for 12 years. This certification helped me bridge Eastern and Western approaches in a way that resonates with American clients who want scientific explanations. My practice used to struggle with client retention—people would come for a few sessions and disappear. Now I offer comprehensive functional medicine programs alongside acupuncture. I finally have a sustainable, thriving practice.", rating: 5 },
  { name: "William Thompson", title: "Worth more than any paycheck", content: "After 25 years in the Army, I needed a new mission. My own health struggles with gut issues and chronic inflammation post-deployment led me to functional medicine. This certification gave me the structure and credibility to help other veterans. I specialize in working with military and first responders—we share similar traumas and health patterns. Seeing guys who've suffered for years finally find answers? That's worth more than any paycheck.", rating: 5 },
  { name: "Rachel Cooper", title: "The missing piece", content: "I had multiple health coaching certifications but kept hitting walls. Clients would improve to a point and then plateau. I couldn't figure out why. This functional medicine certification connected all the dots. Now I understand the biochemistry behind what I was seeing. My coaching became infinitely more effective. Results improved, referrals increased, and I raised my rates significantly. This certification is the missing piece for any health coach serious about getting clients real results.", rating: 5 },
  { name: "Michael Davis", title: "Crazy transformation but real", content: "Yeah, I was a software developer. Zero healthcare experience. But I spent years researching functional medicine for my own autoimmune issues and eventually knew more than most providers I saw. This certification formalized that knowledge and gave me credibility. Hit consistent income within 10 months. Now I make more than I did in tech, I work from home, and I actually help people instead of debugging code. Crazy transformation but very real.", rating: 5 },
  { name: "Danielle Wright", title: "Expanded my scope dramatically", content: "Physical therapy is rewarding but limited. Patients come in with pain, but so often that pain is connected to inflammation, gut issues, hormone imbalances—things I couldn't address. This certification expanded my scope dramatically. I opened a separate functional medicine practice alongside my PT work. The course content was excellent—challenging enough to be credible but accessible enough to complete while working full-time.", rating: 5 },
  { name: "Carlos Mendez", title: "My second chance", content: "Running restaurants for 20 years destroyed my health. When I finally fixed myself through functional medicine, I became obsessed. Took this certification at 48 years old. Everyone thought I was having a midlife crisis. Two years later, I have a thriving practice helping busy professionals and business owners—people who run themselves into the ground like I did. I work when I want, never miss my kids' events anymore, and I'm in the best health of my life. This certification was my second chance.", rating: 5 },

  // Reviews 21-40 (from reviews_21_to_40.md)
  { name: "Nicole Evans", title: "Set me apart from every esthetician", content: "I was treating skin issues from the outside for years, but I knew the real problem was internal. This course taught me the gut-skin connection in a way that completely changed my approach. I now understand how inflammation, food sensitivities, and hormone imbalances show up on the skin. I started offering 'Inner Skin Health' packages alongside my regular services. Clients who tried everything else are finally seeing clear skin. The module on the microbiome was particularly eye-opening.", rating: 5 },
  { name: "Dr. Richard Hayes", title: "ROI in the first month", content: "A dentist doing functional medicine might sound unusual, but hear me out. Periodontal disease is fundamentally an inflammatory condition. I saw systemic inflammation in my patients' mouths every single day. This certification gave me the language and the science to look at the whole body. Now I run a wellness clinic attached to my dental practice. The return on investment for this course was achieved literally in the first month of implementing the new protocols.", rating: 5 },
  { name: "Christine Moore", title: "The real win is recovery", content: "I worked in mental health for over a decade. The disconnect between brain and body in our system drove me absolutely crazy. I would see clients whose anxiety and depression were clearly linked to diet and lifestyle. This certification was the bridge I needed. I now have a private practice that combines counseling with functional nutrition and mood support. But the real win is seeing clients actually recover, not just manage symptoms.", rating: 5 },
  { name: "James Clarke", title: "Elevated my credibility", content: "I've been a personal trainer in London for 15 years. The market is completely saturated. I desperately needed something to distinguish myself. This certification was exactly that. It's not just 'eat your veggies and drink water'—it's deep, scientific, actionable stuff about how the body actually works. I rebranded as a Functional Health Performance Coach and immediately raised my rates. The module on mitochondria and energy production alone was worth the entire course fee.", rating: 5 },
  { name: "Emily Richardson", title: "Professional identity on my terms", content: "I left my accounting career to raise my kids and honestly felt like I completely lost my professional identity. When my son developed severe allergies that doctors couldn't explain, I went into full research mode. That led me to functional medicine. I finished the course in about six months, mostly during nap times. I started a consultation business specifically for moms dealing with kids who have food sensitivities. This certification gave me my professional identity back, but on my own terms.", rating: 5 },
  { name: "Marcus Rodriguez", title: "If I can do it, anyone can", content: "Shift work is a killer. I'm not exaggerating. I watched my buddies die early of heart attacks and strokes. I took this course honestly just to save my own life. But then I started helping guys at the precinct. Simple stuff at first—better hydration, basic sleep hacks, what to eat when you're working nights. The results were undeniable. If a guy like me—no medical background, no fancy degrees—can learn this stuff and build a business out of it, anyone can.", rating: 5 },
  { name: "Sophia Anderson", title: "Perfect for nomadic lifestyle", content: "I live in Bali and run yoga retreats for people from all over the world. This certification allowed me to include comprehensive functional health assessments as part of my retreat packages. I've been able to raise my retreat prices significantly because of the added value. The certification being completely online was perfect for my nomadic lifestyle. I could study from cafes anywhere. The support team was super responsive even with the massive time zone difference.", rating: 5 },
  { name: "Dr. Benjamin Park", title: "Clinical outcomes ten times better", content: "Behavior change is incredibly difficult when your biology is working against you. My patients couldn't 'think' their way out of brain fog or chronic fatigue. I started integrating functional medicine principles to support their physiology so we could actually work on the psychology. When you optimize someone's biochemistry—fix their gut, balance their blood sugar—suddenly the talk therapy becomes ten times more effective. Revenue is up, but the clinical outcomes are what keep me excited.", rating: 5 },
  { name: "Maria Gonzalez", title: "Genuinely internationalized my career", content: "I practice in Mexico City and I wanted a certification that was globally recognized, rigorous, and respected. This program exceeded every expectation. I've successfully treated clients with complex autoimmune conditions that other doctors had given up on. Using the functional medicine approach, I've helped people get their lives back. My reputation has grown significantly, and I now have clients from the United States and Europe. It's genuinely internationalized my career.", rating: 5 },
  { name: "Tyler Mason", title: "Most rewarding work I've ever done", content: "I'm a guy's guy. I work in construction, surrounded by hard hats and heavy machinery all day. But I was sick—overweight, high blood pressure, pre-diabetic. I found this course and decided to take control of my own health. I healed myself, lost 50 pounds, and completely fixed my blood work. Then I started helping other men in the trades. There's a huge need and almost no one serving this market. This is the most rewarding work I've ever done.", rating: 5 },
  { name: "Jessica Williams", title: "Confidence to monetize properly", content: "I had a large following in the wellness space, but I suffered from serious imposter syndrome. I didn't want to just share smoothie recipes; I wanted to be a real authority. This certification gave me both the credentials and the deep knowledge I was missing. My engagement has skyrocketed because I'm sharing real science now, not just trends. I launched a group coaching program that did incredibly well—something I never could have done before. This course gave me the confidence to monetize my audience in a real, meaningful, helpful way.", rating: 5 },
  { name: "Ahmed Hassan", title: "Business is booming", content: "The future of medicine is functional medicine. I saw the trends clearly. In Dubai, clients expect the absolute best—they want cutting-edge, they want luxury, they want results. I took this certification specifically to build a high-end wellness clinic. We now offer IV therapy, genetic testing, comprehensive functional protocols. Business is booming because we're offering something different. The certification gave me the foundational knowledge to build this entire business from scratch.", rating: 5 },
  { name: "Patricia Nelson", title: "Empowering parents to change trajectories", content: "I see sick kids all day long. Allergies, ADHD, asthma—conditions that just keep getting worse despite all the medications they're on. I took this course because I wanted to see if there was something more I could do. Now I run workshops teaching parents how to feed their kids for focus and calm, how to identify food sensitivities. More than the money, I love empowering parents to actually change their children's health trajectories.", rating: 5 },
  { name: "Steven Roberts", title: "Freedom is real", content: "I was stuck trading time for money. Eight hours a day on the gym floor, completely exhausted by the end of it. This certification allowed me to pivot my entire business model. I transitioned to online coaching, managing clients remotely, handling both their fitness and their functional health. I work from coffee shops, from my home office, from wherever I want. I make double what I did grinding on the gym floor. The freedom is real.", rating: 5 },
  { name: "Daniel Kim", title: "ROI was instantaneous", content: "I'm a biohacker at heart. I love data, I love optimization, I love understanding systems. This course is incredibly data-driven, which I loved immediately. I didn't take it to change careers initially—I just wanted to optimize my own performance. But friends at work kept asking me for advice. Eventually I started consulting for tech startups on optimizing employee biology for productivity. The ROI on this course for me was basically instantaneous.", rating: 5 },
  { name: "Margaret Thompson", title: "Never too old to learn", content: "I'm 68 years old. Most people my age are winding down, but I picked up a new career instead. I got interested in longevity and wanted to understand how to age as healthfully as possible. This course was perfect—I took it partly to keep my brain sharp, and it absolutely did. But I ended up loving it so much that I started coaching other seniors. You're never too old to learn this stuff, and you're never too old to help others.", rating: 5 },
  { name: "Laura Mitchell", title: "Extended my career by decades", content: "I was hitting a physical ceiling as a massage therapist. My hands hurt constantly, my wrists were getting worse. But massage was all I knew. This certification allowed me to completely reinvent my career without starting from scratch. I now do 50% massage and 50% functional wellness coaching. My income is up and my body hurts so much less. This course essentially extended my career in the healing arts by decades.", rating: 5 },
  { name: "Dr. Sarah Chen", title: "Unexpected crossover practice", content: "Yes, I'm a vet. I know that might seem strange for a functional medicine certification. But mammals are mammals. The fundamental principles of metabolism, inflammation, and healing apply across species. I took this course initially to understand health better for myself, but I've applied many concepts to my animal patients with remarkable success. And here's the unexpected bonus: pet owners trust me with their own health too. It's become a unique crossover practice.", rating: 5 },
  { name: "Jason Taylor", title: "Alternative path into healthcare", content: "I'm 22 years old. Everyone at my age is either drowning in student loan debt trying to become a doctor, or completely lost about what career to pursue. I didn't want to spend a decade in school. This certification was my alternative path into healthcare. I'm building a practice focused specifically on Gen Z health—anxiety, gut issues, the stress of modern life. I'm already making more than friends with four-year degrees, and I have zero student loans.", rating: 5 },
  { name: "Christine Adams", title: "Impact inside corporate America", content: "I work in human resources for a mid-size company. Every year I watch our health insurance premiums go up because our employees are getting sicker. I convinced my company to pay for this certification so I could become our internal Wellness Officer. Now I run health and wellness programs for our employees. The company saved money and I got a promotion. You don't have to become a practitioner with your own clients to use this knowledge.", rating: 5 },

  // Reviews 41-60 (from reviews_41_to_60.md)
  { name: "Raj Patel", title: "Works everywhere", content: "I took this course from Bangalore. The content is truly global—the principles work everywhere, regardless of healthcare system or culture. I've started a functional telemedicine practice serving clients across India and the Middle East. The demand is massive because people are desperate for answers that conventional medicine isn't giving them. The course platform was stable, the video quality was excellent, and the support team was responsive.", rating: 5 },
  { name: "Angela Martinez", title: "Added income with zero extra marketing", content: "Hair tells you everything about someone's health. Thinning, brittle, dry, falling out—I was the first line of defense but didn't know what to say. This course taught me the connections between hormones, thyroid, nutrition, and hair health. Now I offer 'Inner Beauty' consultations right in the salon chair. Added significant income last year with zero extra marketing. Clients trust me because I already have a relationship with them.", rating: 5 },
  { name: "Pierre Dubois", title: "Gold mine for any chef", content: "I know food. I've been a chef for 25 years. But I didn't actually know nutrition—the science behind why certain foods heal and others harm. This course taught me everything from blood sugar management to anti-inflammatory protocols. Now I run a Functional Meal Prep service cooking for people with autoimmune conditions. We're sold out every single week. This is a gold mine for any chef who wants to do more than just feed people.", rating: 5 },
  { name: "Emma Wilson", title: "Gratitude from new mothers", content: "New mums are completely depleted. Their hormones are chaotic, they're exhausted, and conventional care just says 'this is normal.' Functional medicine says 'let's actually fix this.' I now support postpartum mothers with targeted nutrition, testing, and personalized protocols. The recovery rates are incredible compared to standard care. The gratitude I receive from new mothers who finally feel like themselves again is worth more than any paycheck.", rating: 5 },
  { name: "Mike Johnson", title: "If I can do it, anyone can", content: "Unhealthiest job on earth—truck driving. Sitting 14 hours a day, eating garbage at truck stops. I listened to the course lectures while driving across the country. Changed my diet, fixed my blood sugar, reversed my diabetes. Lost 40 pounds. Now I coach other truckers over the phone while we're on the road. 'Trucker Health' is my side hustle. If I can do this job and still be healthy, anyone can.", rating: 5 },
  { name: "Yuki Tanaka", title: "Connecting strongly with my market", content: "I translated sections of the course for myself as I learned. The depth is incredible—I was constantly looking up terminology and deepening my understanding. I've started introducing these concepts to the Japanese market, which is very traditional but slowly opening up to functional approaches. My focus is overworked office workers who are burning out. It's connecting strongly.", rating: 5 },
  { name: "Ashley Brooks", title: "Science to back up experience", content: "Your body is your instrument. When I got sick and couldn't sing—reflux destroying my vocal cords—I was terrified I'd lose my career. Functional medicine saved my voice by fixing the silent reflux and systemic inflammation. Now I coach other performers. We deal with voice issues, energy on stage, recovering from tours. This course gave me the science to back up my personal experience.", rating: 5 },
  { name: "Robert Miller", title: "Distinguishes my firm", content: "Health is wealth—literally. I manage money for high-net-worth individuals, and the smartest ones know that longevity matters more than portfolio returns if you're not alive to enjoy it. I added 'Health Wealth' coaching to my financial planning services. We talk about optimizing their income AND their lifespan. It distinguishes my firm from every other generic advisor out there.", rating: 5 },
  { name: "Natasha Petrova", title: "Number one destination", content: "I focus on athlete recovery. This course helped me understand inflammation and tissue repair at a cellular level. My dancers recover faster, have fewer injuries, and can train harder without breaking down. It made my studio the number one destination for serious dancers in my city.", rating: 5 },
  { name: "Dr. Kevin Wong", title: "Rigorous enough for an MD", content: "I save lives in the ER. It's meaningful work. But I don't create health—I catch people at the bottom of the cliff after they've already fallen. I started doing functional medicine consultations on the side, and it keeps me sane. Now I help prevent the heart attacks and strokes instead of just responding to them. The course is rigorous enough for an MD to respect.", rating: 5 },
  { name: "Madison Clark", title: "Don't let anyone tell you to wait", content: "Everyone says you're 'too young' to be a practitioner at 21. I disagree. I'm passionate about health, I understand my generation, and I started a blog about Functional Health for Gen Z that absolutely blew up. Now I sell digital guides and do group coaching. I'm paying my way through college with this money—no student loans. If you're young and feel drawn to this, don't let anyone tell you to wait.", rating: 5 },
  { name: "Chris Anderson", title: "Gave me a real future", content: "I make coffee. I talk to tired, stressed people all day long. I took this course because I wanted to do something more meaningful. Started giving little tips to my regulars. They started coming back saying it worked. Now I have a side business doing weekend consultations. I'm saving up to open a healthy café. This course gave me a real future.", rating: 5 },
  { name: "Dorothy Phillips", title: "Purpose in retirement", content: "Retirement was honestly boring. I needed a project, something to keep my mind active. I've always been interested in vitamins and health, but my knowledge was scattered. This course organized everything. Now I help other seniors at my community center with what I call 'Aging with Vitality.' The cognitive health lectures were particularly fantastic.", rating: 5 },
  { name: "Brandon Lewis", title: "Win-win situation", content: "Real estate is high stress, high burnout. I watched my colleagues crash and burn—heart problems, divorces, health scares. I took this course purely to optimize my own performance, to get an edge. It worked so well—more energy, better focus—that I started coaching other agents. My sales went up because I have more energy, AND I have a side income from coaching. Win-win situation.", rating: 5 },
  { name: "Vanessa Moore", title: "Doubled my revenue per client", content: "Beauty is skin deep, but health is internal. I was covering up problems every day—acne, rosacea, dark circles—and clients would ask me how to fix them. I didn't have answers. This certification taught me about gut health, hormones, and inflammation. Now I offer 'Glow from Within' consultations. My clients don't just look better with makeup on; they look better with it off. Doubled my revenue per client.", rating: 5 },
  { name: "Dr. David Chen", title: "Actually healing people", content: "I was prescribing SSRIs and anti-anxiety medications by the bucketload. Effectiveness was mediocre at best. I knew there had to be more to mental health than neurotransmitter reuptake. This course gave me the functional protocols to address the biology of depression—gut health, inflammation, methylation, blood sugar. My patient outcomes have improved dramatically. I'm not just writing prescriptions anymore; I'm actually healing people.", rating: 5 },
  { name: "Jennifer White", title: "Mobile, flexible, profitable", content: "Jet lag, radiation exposure, terrible airplane food, disrupted sleep cycles—my health was falling apart. I took this course just to survive my job as a flight attendant. Learned about circadian rhythm optimization, adrenal support, and detox protocols. Completely healed my digestion and energy levels. Now I coach other flight crew. 'The Healthy Flyer.' It's a huge niche that no one else is serving. Mobile, flexible, profitable.", rating: 5 },
  { name: "Andrew Jackson", title: "Taking off", content: "SaaS sales is a grind. The pressure, the quotas, the endless Zoom calls. I wanted out but didn't know what else to do. I'd been biohacking my own health for years. This certification was the stamp of approval I needed to actually help others. Started consulting for other tech sales guys on maintaining energy, avoiding burnout, staying sharp without endless caffeine. It's taking off.", rating: 5 },
  { name: "Katarina Novak", title: "Unique role I created", content: "Professional musicians are essentially elite athletes. We burn out, we get repetitive strain injuries, we experience crippling performance anxiety. I suffered from inflammation in my fingers and terrible stage fright. Functional medicine addressed both—anti-inflammatory protocols and nervous system support. Now I work with the orchestra as an unofficial wellness advisor. It's a unique role I created thanks entirely to this course.", rating: 5 },
  { name: "John Peterson", title: "Whole new income stream", content: "I grow food. I understand soil health—the microbes, the mineral balance, the importance of diversity. Turns out gut health is basically the same thing. The parallels are incredible. This course made complete sense to me because I already understood the concepts from farming. Now I teach 'Farm to Gut' workshops, connecting the food we grow to how we feel when we eat it. It adds value to my farm products and creates a whole new income stream.", rating: 5 },

  // Reviews 61-80 (from reviews_61_to_100.md)
  { name: "Barbara Thompson", title: "Best money I've ever spent", content: "I have twelve grandchildren. I want to see every single one of them grow up, graduate, get married. That's my motivation. I took this course to become the 'Health Guardian' of my family. Since then, I've helped fix my husband's cholesterol levels without statins, supported my daughter through her thyroid issues, and taught my grandkids about real food versus processed junk. We're a healthier, happier family because of what I learned here. It's the best money I've ever spent.", rating: 5 },
  { name: "Viktor Kozlov", title: "Premium results", content: "Brain function is everything in chess. Mental clarity, focus, memory recall—it all determines who wins. I learned about nootropics, brain-supporting nutrients, and cognitive optimization. Started applying it to my own training first, then to my students. They're winning more tournaments now. I charge a premium for what I call 'Neuro-Performance Chess Coaching.' Parents are happy to pay because they see the results.", rating: 5 },
  { name: "Samantha Reed", title: "Set my business apart", content: "Brides want to look their absolute best on their wedding day. Unfortunately, many resort to crash diets and unhealthy tactics. I wanted to offer a better way. Now I include 'Wedding Wellness' packages—gut healing, hormone balancing, skin-glowing protocols starting six months before the big day. My brides are calmer, happier, and look genuinely radiant, not just thin and stressed. It's set my business apart from every other planner.", rating: 5 },
  { name: "Marcus Williams", title: "Rewarding to give back", content: "The stress, the bad precinct food, the irregular hours—I felt like garbage all the time as a detective. Took this course expecting to just learn a few tips. Ended up losing 40 pounds and completely transforming my energy. Now I'm the 'Health Guy' at the precinct, helping fellow officers pass their physicals and avoid the health problems that take so many of us down early. It's rewarding to give back to the brotherhood.", rating: 5 },
  { name: "Eleanor MacKenzie", title: "Nice quiet side income", content: "I love research. Always have. This course provides deep, properly cited research—not just opinions and trends. I loved digging into the studies and understanding the evidence behind every protocol. Started a blog summarizing health research for regular people who don't want to read scientific papers. It has a small but loyal following now. Nice quiet side income that perfectly suits my personality.", rating: 5 },
  { name: "Billy Ray Thompson", title: "Whole movement growing", content: "I heard about this from another driver on the CB radio who had completely transformed his health. It's genuinely life-changing. I cook in my truck cab now, make better choices at rest stops, lost 60 pounds. I stay awake naturally without energy drinks. I'm starting to help other truckers too. There's a whole movement growing among us. If you drive for a living, this is essential.", rating: 5 },
  { name: "Dr. Amanda Foster", title: "Women have been underserved", content: "PCOS, endometriosis, fibroids, infertility—my conventional tools are limited to birth control pills and surgery. That's it. I knew there had to be more. Functional medicine offers real solutions for women's hormonal health. My practice is now about 50% functional consultations, and women are traveling from other states specifically to see me. There's a desperate need for this kind of care. Women have been underserved for too long.", rating: 5 },
  { name: "Min-Jun Park", title: "Literally my dream job", content: "Professional gaming sounds glamorous, but players burn out by age 20. Eye strain, wrist injuries, cognitive fatigue, sleep disorders from competing across time zones. I focus on what I call 'Gamer Longevity'—keeping players healthy so they can compete longer. This course gave me the science behind eye health, inflammation reduction, brain endurance, and circadian rhythm optimization. I coach pro teams now. It's literally my dream job.", rating: 5 },
  { name: "Isabelle Dumont", title: "Completely new market", content: "Environment affects health more than most people realize. Toxins in furniture, poor lighting disrupting circadian rhythms, mold in buildings. Learned about environmental medicine in this course and now I design what I call 'Wellness Homes.' Low-toxin materials, circadian-supportive lighting, proper ventilation. Wealthy clients pay premium prices for a home that actually supports their health instead of undermining it. It's a completely new market.", rating: 5 },
  { name: "Jack Murphy", title: "It works", content: "The human body is just a machine. Inputs, outputs, filters, combustion. I understood the analogy immediately as an auto mechanic. This course made perfect sense to me because I already think in systems. Fixed my own heart issues through diet and lifestyle changes. Now I help buddies at the shop. We trade car fixes for health fixes—I'll look at your carburetor if you let me look at your cholesterol. It works.", rating: 5 },
  { name: "Camila Santos", title: "Booked nine months in advance", content: "Supporting birth is sacred work, but mothers are completely depleted afterward. I use functional nutrition to build them up before and during pregnancy, then support their recovery postpartum. The difference in outcomes is remarkable—faster recovery, better milk supply, less postpartum depression. My doula practice is now booked nine months in advance.", rating: 5 },
  { name: "Derek Stone", title: "Business is booming", content: "I see the effects of alcohol, late nights, and poor choices every single shift as a bartender in Vegas. It made me want to be healthier myself. This course was my path out. Now I run a 'Detox and Recovery' service for tourists and locals who partied too hard. IV therapy, supplement protocols, recovery plans. Business is booming in a city that runs on excess.", rating: 5 },
  { name: "Michelle Torres", title: "There's a better way", content: "I argue for a living as an attorney. I needed evidence, real science I could defend. This course is completely evidence-based—no woo-woo, no unsubstantiated claims. I used it first to heal my own severe adrenal fatigue from years of 80-hour weeks. Now I coach other female lawyers on what I call 'Sustainable Success.' You don't have to burn out to make partner. There's a better way.", rating: 5 },
  { name: "Dylan Cooper", title: "Pays for my surf trips", content: "I want to surf until I'm 90. That's not a joke—I genuinely want to be out there on the waves as an old man. Joint health, inflammation control, recovery optimization—that's my focus. I created a 'Surfer's Health' coaching program based on what I learned here. Helps me pay for my surf trips around the world.", rating: 5 },
  { name: "Dr. Wei Zhang", title: "Very helpful for Western clients", content: "I wanted to understand the Western scientific perspective on what I do with needles and meridians. This course integrated perfectly with my acupuncture practice. It gave me new language to explain concepts like Qi and blood stagnation using terms like blood sugar dysregulation, inflammation, and autonomic nervous system imbalance. Very helpful for working with Western clients who want scientific explanations.", rating: 5 },
  { name: "Hans Mueller", title: "Sales tripled", content: "I love bread. It's my passion, my heritage, my craft. But gluten has become a problem for so many people. Learned about sourdough fermentation and gut health—how properly fermented grains are much easier to digest. Changed my entire bakery to focus on 'Gut-Friendly Fermented Grains.' Sales tripled. People who couldn't eat bread before can now enjoy my products without bloating.", rating: 5 },
  { name: "Alexis Jordan", title: "Someone needs to protect these girls", content: "The fashion industry is toxic. Eating disorders are rampant, drug use is normalized, and the pressure is relentless. I wanted to be thin AND healthy as a model—everyone told me that was impossible. This course taught me about hormones, metabolism, and sustainable nutrition. Now I coach young models on how to maintain their careers without destroying their bodies. Someone needs to protect these girls.", rating: 5 },
  { name: "Oliver Smith", title: "Noticeably better", content: "Sitting destroys your health. I learned that in this course—sitting is basically smoking. Started what I call the 'Healthy Cabbie' initiative as a taxi driver in London. Simple exercises we can do in the cab between fares, healthy snacks to keep in the glovebox, stretches for tight hips. It's a small movement, but the drivers in my network are feeling noticeably better.", rating: 5 },
  { name: "Sister Maria", title: "Health honors the body as a gift", content: "Yes, even in the convent we have health issues. Age-related decline, digestive problems, low energy. I took this course to learn how to cook better for my sisters. We've seen visible improvements in energy, mood, and overall vitality throughout our community. Health is a way to honor the body as a gift. This knowledge serves that purpose beautifully.", rating: 4 },
  { name: "Travis Austin", title: "Coolest job I've ever had", content: "Tour life is incredibly hard on the body. Bad venue food, no sleep, different cities every night, constant travel. I was a complete mess physically. This course straightened me out. Now I'm the 'Tour Wellness' guy—bands actually hire me to travel with them and keep everyone healthy on the road. I've worked with some big names. Coolest job I've ever had.", rating: 5 },

  // Reviews 81-100 (from reviews_61_to_100.md continued)
  { name: "Elena Rodriguez", title: "Tools beyond medication", content: "I work with children diagnosed with ADHD. I saw the sugar, the artificial dyes, the processed foods they were eating. It seemed so obvious that diet was part of the problem. Took this course to learn more, and now I run workshops for parents called 'Feeding the Brain.' They're so grateful to finally have tools beyond medication.", rating: 5 },
  { name: "Connor MacLeod", title: "Giving them knowledge I wish I had", content: "Recovery is everything in professional sports. I extended my playing career by at least three years using what I learned here—anti-inflammatory nutrition, sleep optimization, targeted supplementation. Now that I've retired from playing hockey, I coach junior players on the same principles. Giving them the knowledge I wish I'd had at their age.", rating: 5 },
  { name: "Anna van der Berg", title: "Beautiful addition to my shop", content: "I work with nature every day. Plants, flowers, herbs. This course deepened my understanding of botanical medicine and how plants can be used therapeutically. Now I sell what I call 'Healing Bouquets'—flower arrangements paired with herbal teas and medicinal herb information. It's a beautiful addition to my florist shop that sets me apart.", rating: 5 },
  { name: "Dr. Arun Sharma", title: "Results often better than medication", content: "Heart disease is fundamentally a lifestyle disease. We all know this, yet we don't treat it that way in conventional cardiology. I changed my approach. My 'reversal program' is now famous in my city—we use food, stress management, supplements, and lifestyle modification to actually reverse cardiovascular disease, not just manage it with statins. The results are often better than medication alone.", rating: 5 },
  { name: "Sophie Williams", title: "Works for both ends of the leash", content: "Animals are developing the same chronic diseases as humans now. Diabetes in cats, obesity in dogs, cancer everywhere. It's clearly diet and lifestyle related. I apply functional medicine principles to the pets I see as a vet technician, and I've started counseling the owners too. The holistic approach works for both ends of the leash.", rating: 5 },
  { name: "Lucas Silva", title: "Fixing my own chronic back pain", content: "I design structures as an architect. Buildings, bridges, systems. The body is also a structure—tensegrity, fascia, load distribution. I loved the modules on structural integrity, fascia, and how inflammation affects tissue repair. Used the knowledge to fix my own chronic back pain. Now I help colleagues in my firm who spend too much time hunched over drafting tables.", rating: 5 },
  { name: "Zinhle Ndlovu", title: "Dancing better than ten years ago", content: "Energy is my currency. I need to perform multiple shows a week with full intensity. I was constantly exhausted and couldn't figure out why—doctors said I was 'fine.' This course taught me about optimal ranges versus normal ranges. Found my root cause—subclinical thyroid and iron issues—fixed it, and I'm dancing better now than I did ten years ago.", rating: 5 },
  { name: "Ivan Petrov", title: "Success from combining hard work with smart biology", content: "Strength requires recovery. You don't build muscle in the gym—you build it during rest. I use functional medicine to maximize my recovery and my athletes' recovery. Clients are breaking personal records. Success comes from combining hard work with smart biology.", rating: 5 },
  { name: "Dr. Fatima Hassan", title: "Science is solid and accurate", content: "I understand molecules as a chemist. Biochemistry is my language. I was skeptical that an online course could be rigorous enough for someone with my background. I was wrong. The science here is solid, properly cited, and accurate. Now I use what I learned to formulate my own skincare and supplement line.", rating: 5 },
  { name: "Captain James Richardson", title: "Feel much safer flying now", content: "Radiation exposure at altitude is a real occupational hazard that nobody talks about as a commercial pilot. I learned about mitigation strategies—antioxidants, detox support, protective nutrients. I feel much safer flying now, knowing I'm actively protecting my cells from the accumulated radiation exposure.", rating: 5 },
  { name: "Pierre Laurent", title: "Popular workshop", content: "Wine is my life as a sommelier. But liver health matters when you're tasting wine professionally every day. I now teach what I call 'Mindful Drinking and Liver Support.' You can enjoy wine and maintain your health if you understand how to support your detoxification pathways. It's a popular workshop for wine enthusiasts who don't want to give up their passion.", rating: 5 },
  { name: "Priya Krishnan", title: "Scientific validation for ancient wisdom", content: "Ayurveda and Functional Medicine are sister disciplines. The principles overlap beautifully—individualized approaches, root cause thinking, food as medicine. This course helped me bridge traditions. My Western students especially appreciate getting the scientific validation for ancient wisdom.", rating: 5 },
  { name: "Max Schneider", title: "Coaching wealthy clients", content: "Cold exposure and high altitude demand specific nutritional support as a ski instructor. I optimize my body for the mountain environment—fat adaptation for endurance, altitude supplements for oxygen utilization, recovery protocols for back-to-back ski days. Now I coach wealthy clients on nutrition for alpine performance.", rating: 5 },
  { name: "Roberto Fuentes", title: "Making a real difference", content: "We eat fish here in Chile. Omega-3s are abundant in our traditional diet. This course taught me WHY our ancestral foods are so healthy. I'm helping my community understand the value of returning to traditional eating patterns instead of adopting Western processed foods. It's making a real difference.", rating: 5 },
  { name: "Catherine Hayes", title: "No fluff, no pseudoscience", content: "I investigate stories for a living as a journalist. I'm naturally skeptical. I dug into the science behind this course expecting to find problems. Instead, I found solid research and evidence-based protocols. This is the real deal. No fluff, no pseudoscience. Just practical, well-researched health optimization.", rating: 5 },
  { name: "Kenji Yamamoto", title: "Booked months in advance", content: "Japanese cuisine respects umami—the fifth taste. But nutrient density matters even more. I created a 'Functional Kaiseki' menu based on what I learned about therapeutic foods. It's now booked months in advance. Food as medicine is an ancient Japanese concept, and this course helped me modernize it.", rating: 5 },
  { name: "Erik Larsson", title: "Beautiful combination", content: "Nature heals, but we need to support our bodies to fully enjoy it. I help older hikers prepare for challenging mountain treks using functional nutrition—building stamina, protecting joints, optimizing energy. We walk and we talk about health. It's a beautiful combination.", rating: 5 },
  { name: "Amélie Moreau", title: "Completely new market", content: "Scent is a chemical signal that directly impacts the emotional brain. I learned about essential oils and limbic system activation. Now I create what I call 'Functional Fragrances'—scents specifically designed for stress relief, focus, or relaxation. It's a completely new market that combines my perfumery skills with health knowledge.", rating: 5 },
  { name: "Anastasia Volkov", title: "Careers can last", content: "Flexibility and strength require tissue health. Inflammation destroys both. I coach young gymnasts on anti-inflammatory nutrition and recovery protocols. They perform better, train harder, and most importantly, they stay injury-free longer. Their careers can last instead of ending at 20.", rating: 5 },
  { name: "Dr. James Wright", title: "Healthier overall, not just orally", content: "The mouth is connected to the entire body. Mercury fillings, oral microbiome disruption, chronic gum inflammation—these affect systemic health. My dental practice is now fully holistic. We look at the whole picture, not just teeth. Patients are healthier overall, not just orally.", rating: 5 },
];

async function importFMReviews() {
  console.log("🌱 Importing all FM Certification Reviews...\n");

  // Find the FM Certification course
  const course = await prisma.course.findFirst({
    where: { slug: COURSE_SLUG },
    select: { id: true, title: true },
  });

  if (!course) {
    console.error(`❌ Course not found: ${COURSE_SLUG}`);
    process.exit(1);
  }

  console.log(`📚 Found course: ${course.title} (${course.id})`);
  console.log(`📝 Total reviews to import: ${allReviews.length}\n`);

  // Get zombie profiles with avatars
  const zombieProfiles = await prisma.user.findMany({
    where: {
      isFakeProfile: true,
      avatar: { not: null },
    },
    select: { id: true, firstName: true, lastName: true, avatar: true },
  });

  console.log(`👤 Found ${zombieProfiles.length} zombie profiles with avatars\n`);

  if (zombieProfiles.length < allReviews.length) {
    console.log(`⚠️ Not enough zombie profiles (${zombieProfiles.length}) for all reviews (${allReviews.length})`);
    console.log(`   Will reuse profiles as needed.\n`);
  }

  // Delete existing reviews for this course
  const deleted = await prisma.courseReview.deleteMany({
    where: { courseId: course.id },
  });
  console.log(`🗑️  Deleted ${deleted.count} existing reviews\n`);

  // Shuffle profiles
  const shuffledProfiles = [...zombieProfiles].sort(() => Math.random() - 0.5);

  // Create reviews
  let totalRating = 0;
  let created = 0;
  let fiveStarCount = 0;
  let fourStarCount = 0;

  for (let i = 0; i < allReviews.length; i++) {
    const profile = shuffledProfiles[i % shuffledProfiles.length];
    const reviewData = allReviews[i];

    // Random date within last 12 months
    const daysAgo = Math.floor(Math.random() * 365);
    const createdAt = new Date();
    createdAt.setDate(createdAt.getDate() - daysAgo);

    try {
      await prisma.courseReview.create({
        data: {
          courseId: course.id,
          userId: profile.id,
          rating: reviewData.rating,
          title: reviewData.title,
          content: reviewData.content,
          isVerified: true,
          isPublic: true,
          createdAt,
        },
      });

      totalRating += reviewData.rating;
      created++;

      if (reviewData.rating === 5) fiveStarCount++;
      else if (reviewData.rating === 4) fourStarCount++;

      if (created % 20 === 0) {
        console.log(`✅ Imported ${created}/${allReviews.length} reviews...`);
      }
    } catch (error) {
      console.error(`❌ Error creating review ${i + 1}:`, error);
    }
  }

  const avgRating = totalRating / created;
  console.log(`\n📊 Import Summary:`);
  console.log(`   Total reviews created: ${created}`);
  console.log(`   5-star reviews: ${fiveStarCount}`);
  console.log(`   4-star reviews: ${fourStarCount}`);
  console.log(`   Average rating: ${avgRating.toFixed(2)}`);

  // Update or create course analytics
  const existingAnalytics = await prisma.courseAnalytics.findUnique({
    where: { courseId: course.id },
  });

  if (existingAnalytics) {
    await prisma.courseAnalytics.update({
      where: { courseId: course.id },
      data: { avgRating },
    });
  } else {
    await prisma.courseAnalytics.create({
      data: {
        courseId: course.id,
        avgRating,
        totalEnrolled: 1447,
      },
    });
  }

  console.log("\n✨ FM Certification Reviews imported successfully!");
}

importFMReviews()
  .catch((e) => {
    console.error("Error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
