# New courses data - Batch 3: Luna, Emma, Bella
NEW_LUNA_SPIRITUAL = [
    ("Certified Akashic Records Practitioner™", "akashic-records"),
    ("Certified Past Life Regression Therapist™", "past-life-regression"),
    ("Certified Soul Retrieval Practitioner™", "soul-retrieval"),
    ("Certified Shamanic Journey Facilitator™", "shamanic-journey"),
    ("Certified Medicine Wheel Practitioner™", "medicine-wheel"),
    ("Certified Sacred Geometry Healer™", "sacred-geometry"),
    ("Certified Sound Bath Facilitator™", "sound-bath"),
    ("Certified Singing Bowl Practitioner™", "singing-bowl"),
    ("Certified Tuning Fork Therapist™", "tuning-fork"),
    ("Certified Crystal Grid Specialist™", "crystal-grid"),
    ("Certified Pendulum Practitioner™", "pendulum"),
    ("Certified Dowsing Specialist™", "dowsing"),
    ("Certified Aura Reading Practitioner™", "aura-reading"),
    ("Certified Mediumship Development Practitioner™", "mediumship"),
    ("Certified Trance Channeling Practitioner™", "trance-channeling"),
    ("Certified Automatic Writing Practitioner™", "automatic-writing"),
    ("Certified Spirit Release Practitioner™", "spirit-release"),
    ("Certified House Cleansing Specialist™", "house-cleansing"),
    ("Certified Land Energy Healing Practitioner™", "land-energy"),
    ("Certified Ley Line Practitioner™", "ley-line"),
    ("Certified Feng Shui Consultant™", "feng-shui"),
    ("Certified Vedic Astrology Practitioner™", "vedic-astrology"),
    ("Certified Evolutionary Astrology Practitioner™", "evolutionary-astrology"),
    ("Certified Astrocartography Specialist™", "astrocartography"),
    ("Certified Gene Keys Practitioner™", "gene-keys"),
    ("Certified I Ching Practitioner™", "i-ching"),
    ("Certified Numerology Life Path Practitioner™", "numerology-life-path"),
    ("Certified Palmistry Practitioner™", "palmistry"),
    ("Certified Face Reading Specialist™", "face-reading"),
    ("Certified Theta Healing Practitioner™", "theta-healing"),
    ("Certified Access Bars Practitioner™", "access-bars"),
    ("Certified Quantum Healing Practitioner™", "quantum-healing"),
    ("Certified Pranic Healing Practitioner™", "pranic-healing"),
    ("Certified Angelic Reiki Practitioner™", "angelic-reiki"),
]

NEW_EMMA_PARENTING = [
    ("Certified Montessori Parent Coach™", "montessori-parent"),
    ("Certified RIE Parenting Coach™", "rie-parenting"),
    ("Certified Waldorf Parenting Coach™", "waldorf-parenting"),
    ("Certified Unschooling Coach™", "unschooling"),
    ("Certified Homeschool Learning Coach™", "homeschool-coach"),
    ("Certified Peaceful Parenting Coach™", "peaceful-parenting"),
    ("Certified No-Drama Discipline Coach™", "no-drama-discipline"),
    ("Certified Sibling Rivalry Coach™", "sibling-rivalry"),
    ("Certified Only Child Development Coach™", "only-child"),
    ("Certified Blended Family Coach™", "blended-family"),
    ("Certified Adoptive Family Coach™", "adoptive-family"),
    ("Certified Foster Parent Coach™", "foster-parent"),
    ("Certified Kinship Care Coach™", "kinship-care"),
    ("Certified Special Needs Parenting Coach™", "special-needs-parent"),
    ("Certified Sensory Processing Parent Coach™", "sensory-processing-parent"),
    ("Certified Selective Mutism Coach™", "selective-mutism"),
    ("Certified School Refusal Specialist™", "school-refusal"),
    ("Certified Teen Substance Prevention Coach™", "teen-substance"),
    ("Certified Teen Mental Health First Aid Coach™", "teen-mental-health"),
    ("Certified College Prep & Launch Coach™", "college-prep"),
    ("Certified Empty Nest Transition Coach™", "empty-nest"),
    ("Certified Grandparent Coach™", "grandparent-coach"),
    ("Certified Digital Parenting Coach™", "digital-parenting"),
    ("Certified Screen Time Coach™", "screen-time"),
]

NEW_BELLA_PETS = [
    ("Certified Raw Feeding Dog Specialist™", "raw-feeding-dog"),
    ("Certified Species-Appropriate Cat Diet Specialist™", "cat-diet"),
    ("Certified Pet Allergy Specialist™", "pet-allergy"),
    ("Certified Pet Cancer Support Specialist™", "pet-cancer"),
    ("Certified Senior Pet Wellness Specialist™", "senior-pet"),
    ("Certified Pet CBD & Hemp Specialist™", "pet-cbd"),
    ("Certified Pet Separation Anxiety Specialist™", "pet-separation-anxiety"),
    ("Certified Reactive Dog Specialist™", "reactive-dog"),
    ("Certified Fear-Free Pet Handling Specialist™", "fear-free-pet"),
    ("Certified Pet End-of-Life Doula™", "pet-end-of-life"),
    ("Certified Pet Loss Grief Coach™", "pet-loss-grief"),
    ("Certified Cat Enrichment Specialist™", "cat-enrichment"),
    ("Certified Small Animal Wellness Specialist™", "small-animal"),
    ("Certified Rabbit & Guinea Pig Specialist™", "rabbit-guinea-pig"),
    ("Certified Exotic Pet Nutrition Specialist™", "exotic-pet"),
    ("Certified Bird Wellness Specialist™", "bird-wellness"),
    ("Certified Multi-Pet Household Specialist™", "multi-pet"),
    ("Certified Pet & Baby Safety Specialist™", "pet-baby-safety"),
    ("Certified Service Dog Handler Coach™", "service-dog"),
]
