# New courses data - Batch 1: Sarah Clinical & Health
NEW_SARAH_FM = [
    # Clinical Conditions
    ("Certified Clinical Hashimoto's Thyroiditis Specialist™", "hashimotos-specialist"),
    ("Certified Chronic Fatigue Recovery Practitioner™", "chronic-fatigue-recovery"),
    ("Certified Fibromyalgia Wellness Specialist™", "fibromyalgia-specialist"),
    ("Certified Ehlers-Danlos Syndrome Specialist™", "eds-specialist"),
    ("Certified Clinical SIBO Specialist™", "sibo-specialist"),
    ("Certified Candida Overgrowth Practitioner™", "candida-practitioner"),
    ("Certified POTS & Dysautonomia Specialist™", "pots-dysautonomia"),
    ("Certified MCAS (Mast Cell) Specialist™", "mcas-specialist"),
    ("Certified Interstitial Cystitis Specialist™", "interstitial-cystitis"),
    ("Certified IBS Recovery Specialist™", "ibs-specialist"),
    ("Certified Celiac & Gluten-Free Specialist™", "celiac-specialist"),
    ("Certified Crohn's & Colitis Practitioner™", "crohns-colitis"),
    ("Certified Migraine Management Specialist™", "migraine-specialist"),
    ("Certified TMJ & Jaw Health Specialist™", "tmj-specialist"),
    ("Certified Tinnitus Relief Specialist™", "tinnitus-specialist"),
    ("Certified Vertigo & Balance Specialist™", "vertigo-specialist"),
    ("Certified Chronic Pain Practitioner™", "chronic-pain-practitioner"),
    ("Certified Neuropathy Support Specialist™", "neuropathy-specialist"),
    ("Certified Restless Leg Syndrome Specialist™", "rls-specialist"),
    ("Certified Raynaud's & Circulation Specialist™", "raynauds-specialist"),
    ("Certified Graves Disease Specialist™", "graves-disease"),
    ("Certified Lupus Support Practitioner™", "lupus-practitioner"),
    ("Certified Rheumatoid Arthritis Specialist™", "ra-specialist"),
    ("Certified Multiple Sclerosis Wellness Practitioner™", "ms-practitioner"),
    ("Certified Psoriasis & Psoriatic Arthritis Specialist™", "psoriasis-specialist"),
    ("Certified Sjogren's Syndrome Specialist™", "sjogrens-specialist"),
    ("Certified Ankylosing Spondylitis Specialist™", "ankylosing-specialist"),
    ("Certified H. Pylori Recovery Specialist™", "h-pylori-specialist"),
    ("Certified Leaky Gut Restoration Practitioner™", "leaky-gut-practitioner"),
    ("Certified GERD & Acid Reflux Specialist™", "gerd-specialist"),
    ("Certified Gastroparesis Specialist™", "gastroparesis-specialist"),
    ("Certified Diverticulitis Specialist™", "diverticulitis-specialist"),
    ("Certified Bile Acid Malabsorption Specialist™", "bile-acid-specialist"),
    ("Certified Histamine Intolerance Specialist™", "histamine-specialist"),
    ("Certified Oxalate Sensitivity Specialist™", "oxalate-specialist"),
    ("Certified Salicylate Sensitivity Specialist™", "salicylate-specialist"),
    ("Certified Central Sensitization Specialist™", "central-sensitization"),
    ("Certified Trigeminal Neuralgia Specialist™", "trigeminal-specialist"),
    ("Certified Pudendal Neuralgia Specialist™", "pudendal-specialist"),
    # Testing & Labs
    ("Certified Organic Acids Test (OAT) Specialist™", "oat-specialist"),
    ("Certified Comprehensive Stool Analysis Specialist™", "stool-analysis-specialist"),
    ("Certified Food Sensitivity Testing Specialist™", "food-sensitivity-specialist"),
    ("Certified SIBO Breath Test Specialist™", "sibo-breath-specialist"),
    ("Certified Hormone Panel Interpretation Specialist™", "hormone-panel-specialist"),
    ("Certified Thyroid Panel Specialist™", "thyroid-panel-specialist"),
    ("Certified Micronutrient Testing Specialist™", "micronutrient-specialist"),
    ("Certified Adrenal Testing (DUTCH) Specialist™", "dutch-specialist"),
    ("Certified Genetic SNP Analysis Specialist™", "genetic-snp-specialist"),
    ("Certified Environmental Toxin Testing Specialist™", "toxin-testing-specialist"),
    ("Certified Hair Tissue Mineral Analysis Specialist™", "htma-specialist"),
    ("Certified Inflammatory Marker Specialist™", "inflammatory-marker-specialist"),
    ("Certified Mycotoxin Testing Specialist™", "mycotoxin-specialist"),
    ("Certified Heavy Metal Testing Specialist™", "heavy-metal-testing"),
    ("Certified Microbiome Analysis Specialist™", "microbiome-specialist"),
    # Biohacking & Longevity
    ("Certified NAD+ Therapy Practitioner™", "nad-therapy"),
    ("Certified Stem Cell Wellness Practitioner™", "stem-cell-wellness"),
    ("Certified Exosome Therapy Practitioner™", "exosome-therapy"),
    ("Certified Hyperbaric Oxygen Practitioner™", "hyperbaric-oxygen"),
    ("Certified IV Vitamin Therapy Practitioner™", "iv-vitamin-therapy"),
    ("Certified Ozone Therapy Practitioner™", "ozone-therapy"),
    ("Certified Infrared Sauna Specialist™", "infrared-sauna"),
    ("Certified EMF Protection Specialist™", "emf-protection"),
    ("Certified Blue Light & Circadian Specialist™", "blue-light-circadian"),
    ("Certified Grounding & Earthing Specialist™", "grounding-earthing"),
    ("Certified Telomere Health Specialist™", "telomere-health"),
    ("Certified Cellular Health Practitioner™", "cellular-health"),
    ("Certified Mitochondrial Health Specialist™", "mitochondrial-health"),
    # Diet Protocols
    ("Certified AIP (Autoimmune Protocol) Specialist™", "aip-specialist"),
    ("Certified Low-FODMAP Diet Specialist™", "low-fodmap-specialist"),
    ("Certified Low-Histamine Diet Specialist™", "low-histamine-specialist"),
    ("Certified Low-Oxalate Diet Specialist™", "low-oxalate-specialist"),
    ("Certified Anti-Candida Diet Specialist™", "anti-candida-specialist"),
    ("Certified Wahls Protocol Specialist™", "wahls-protocol"),
    ("Certified Mediterranean Diet Specialist™", "mediterranean-specialist"),
    ("Certified GAPS Diet Specialist™", "gaps-specialist"),
    ("Certified Specific Carbohydrate Diet Specialist™", "scd-specialist"),
    ("Certified Plant-Based Whole Foods Specialist™", "plant-based-specialist"),
    ("Certified Raw Food Specialist™", "raw-food-specialist"),
    ("Certified Macrobiotic Diet Specialist™", "macrobiotic-specialist"),
    ("Certified Paleo Autoimmune Specialist™", "paleo-autoimmune"),
    ("Certified Lion Diet Specialist™", "lion-diet-specialist"),
    # Environmental & Toxicity
    ("Certified Mold Illness Recovery Practitioner™", "mold-illness"),
    ("Certified Biotoxin Illness Specialist™", "biotoxin-specialist"),
    ("Certified Environmental Toxin Detox Practitioner™", "environmental-detox"),
    ("Certified Heavy Metal Detox Practitioner™", "heavy-metal-detox"),
    ("Certified Chemical Sensitivity Specialist™", "chemical-sensitivity"),
    ("Certified Multiple Chemical Sensitivity Specialist™", "mcs-specialist"),
    ("Certified Sick Building Syndrome Specialist™", "sick-building"),
    ("Certified Home Detox Specialist™", "home-detox"),
    ("Certified Non-Toxic Living Specialist™", "non-toxic-living"),
    ("Certified Clean Beauty Specialist™", "clean-beauty"),
    ("Certified Endocrine Disruptor Specialist™", "endocrine-disruptor"),
    # Aging & Longevity
    ("Certified Healthy Aging Practitioner™", "healthy-aging"),
    ("Certified Brain Health & Dementia Prevention Specialist™", "brain-health"),
    ("Certified Alzheimer's Prevention Specialist™", "alzheimers-prevention"),
    ("Certified Cognitive Decline Prevention Specialist™", "cognitive-decline"),
    ("Certified Memory Enhancement Specialist™", "memory-enhancement"),
    ("Certified Bone Health & Osteoporosis Specialist™", "bone-health"),
    ("Certified Sarcopenia Prevention Specialist™", "sarcopenia-prevention"),
    ("Certified Frailty Prevention Specialist™", "frailty-prevention"),
    ("Certified Hearing Health Specialist™", "hearing-health"),
    ("Certified Vision Health Specialist™", "vision-health"),
    ("Certified Anti-Aging Lifestyle Practitioner™", "anti-aging-lifestyle"),
    # Sleep
    ("Certified Sleep Optimization Specialist™", "sleep-optimization"),
    ("Certified Insomnia Recovery Specialist™", "insomnia-specialist"),
    ("Certified Sleep Apnea Lifestyle Specialist™", "sleep-apnea"),
    ("Certified Circadian Rhythm Specialist™", "circadian-rhythm"),
    ("Certified Shift Worker Sleep Specialist™", "shift-worker-sleep"),
    ("Certified Parent Sleep Specialist™", "parent-sleep"),
    ("Certified Menopause Sleep Specialist™", "menopause-sleep"),
]

NEW_SARAH_WH = [
    ("Certified Cycle Tracking & Fertility Awareness Specialist™", "cycle-tracking"),
    ("Certified Ovarian Reserve Health Specialist™", "ovarian-reserve"),
    ("Certified Egg Quality Optimization Specialist™", "egg-quality"),
    ("Certified Endocrine Disruptor Detox Specialist™", "endocrine-detox"),
    ("Certified Birth Control Transition Specialist™", "birth-control-transition"),
    ("Certified Post-Birth Control Syndrome Specialist™", "post-birth-control"),
    ("Certified Premature Ovarian Failure Specialist™", "premature-ovarian"),
    ("Certified Hypothalamic Amenorrhea Specialist™", "hypothalamic-amenorrhea"),
    ("Certified PMDD Specialist™", "pmdd-specialist"),
    ("Certified Fibroids & Cyst Wellness Specialist™", "fibroids-cysts"),
    ("Certified Adenomyosis Support Specialist™", "adenomyosis"),
    ("Certified Vulvodynia & Pelvic Pain Specialist™", "vulvodynia"),
    ("Certified Vaginal Microbiome Specialist™", "vaginal-microbiome"),
    ("Certified Sexual Pain Specialist™", "sexual-pain"),
    ("Certified Hormone-Friendly Skincare Specialist™", "hormone-skincare"),
    ("Certified Menopausal Brain Fog Specialist™", "menopause-brain-fog"),
    ("Certified Hot Flash Management Specialist™", "hot-flash"),
    ("Certified Breast Implant Illness Specialist™", "breast-implant-illness"),
    ("Certified Hysterectomy Recovery Specialist™", "hysterectomy-recovery"),
]
