# New courses data - Batch 2: Olivia Mental Health
NEW_OLIVIA_TRAUMA = [
    ("Certified Complex PTSD Specialist™", "complex-ptsd"),
    ("Certified Developmental Trauma Specialist™", "developmental-trauma"),
    ("Certified Medical Trauma Specialist™", "medical-trauma"),
    ("Certified Birth Trauma Specialist™", "birth-trauma"),
    ("Certified Sexual Trauma Recovery Specialist™", "sexual-trauma"),
    ("Certified Religious Trauma Specialist™", "religious-trauma"),
    ("Certified Cult Recovery Specialist™", "cult-recovery"),
    ("Certified Generational Trauma Specialist™", "generational-trauma"),
    ("Certified Racial Trauma Specialist™", "racial-trauma"),
    ("Certified First Responder Trauma Specialist™", "first-responder-trauma"),
    ("Certified Covert Narcissism Specialist™", "covert-narcissism"),
    ("Certified Flying Monkey Recognition Specialist™", "flying-monkey"),
    ("Certified Grey Rock Method Specialist™", "grey-rock"),
    ("Certified No Contact Specialist™", "no-contact"),
    ("Certified Hoovering Prevention Specialist™", "hoovering-prevention"),
    ("Certified Trauma Bond Breaking Specialist™", "trauma-bond"),
    ("Certified Love Bombing Recovery Specialist™", "love-bombing"),
    ("Certified Financial Abuse Recovery Specialist™", "financial-abuse"),
    ("Certified Parental Alienation Specialist™", "parental-alienation"),
    ("Certified High-Conflict Divorce Specialist™", "high-conflict-divorce"),
    ("Certified Inner Child Healing Therapist™", "inner-child"),
    ("Certified Shadow Work Facilitator™", "shadow-work"),
]

NEW_OLIVIA_NEURO = [
    ("Certified Autism Level 1 Support Specialist™", "autism-level-1"),
    ("Certified Masking & Burnout Specialist™", "masking-burnout"),
    ("Certified PDA (Pathological Demand Avoidance) Specialist™", "pda-specialist"),
    ("Certified Auditory Processing Disorder Specialist™", "auditory-processing"),
    ("Certified Dyspraxia Support Specialist™", "dyspraxia"),
    ("Certified Dyscalculia Specialist™", "dyscalculia"),
    ("Certified Tourette's Support Specialist™", "tourettes"),
    ("Certified OCD Recovery Specialist™", "ocd-recovery"),
    ("Certified Rejection Sensitive Dysphoria Specialist™", "rsd-specialist"),
    ("Certified Time Blindness Specialist™", "time-blindness"),
    ("Certified Executive Function Specialist™", "executive-function"),
    ("Certified Twice Exceptional (2e) Specialist™", "twice-exceptional"),
    ("Certified Health Anxiety Specialist™", "health-anxiety"),
    ("Certified Social Anxiety Specialist™", "social-anxiety"),
    ("Certified Panic Attack Recovery Specialist™", "panic-attack"),
    ("Certified Agoraphobia Specialist™", "agoraphobia"),
    ("Certified Phobia Release Specialist™", "phobia-release"),
    ("Certified Emetophobia Specialist™", "emetophobia"),
    ("Certified Dental Anxiety Specialist™", "dental-anxiety"),
    ("Certified Medical Procedure Anxiety Specialist™", "medical-anxiety"),
    ("Certified Performance Anxiety Specialist™", "performance-anxiety"),
    ("Certified Seasonal Affective Disorder Specialist™", "sad-specialist"),
    ("Certified Postpartum Depression Specialist™", "postpartum-depression"),
    ("Certified Perimenopause Mood Specialist™", "perimenopause-mood"),
    ("Certified Anhedonia Recovery Specialist™", "anhedonia"),
    ("Certified Emotional Numbness Specialist™", "emotional-numbness"),
    ("Certified Pure O (Pure Obsessional OCD) Specialist™", "pure-o"),
    ("Certified Relationship OCD Specialist™", "relationship-ocd"),
    ("Certified Health OCD Specialist™", "health-ocd"),
    ("Certified Hoarding Recovery Specialist™", "hoarding-recovery"),
    ("Certified Dermatillomania Specialist™", "dermatillomania"),
    ("Certified Trichotillomania Specialist™", "trichotillomania"),
    ("Certified Body-Focused Repetitive Behavior Specialist™", "bfrb"),
    ("Certified Intuitive Eating Specialist™", "intuitive-eating"),
    ("Certified Mindful Eating Specialist™", "mindful-eating"),
    ("Certified Emotional Eating Recovery Specialist™", "emotional-eating"),
    ("Certified Binge Eating Recovery Specialist™", "binge-eating"),
    ("Certified Orthorexia Recovery Specialist™", "orthorexia"),
    ("Certified Diet Trauma Recovery Specialist™", "diet-trauma"),
    ("Certified Body Dysmorphia Specialist™", "body-dysmorphia"),
    ("Certified Body Neutrality Specialist™", "body-neutrality"),
]

NEW_OLIVIA_ADDICTION = [
    ("Certified Alcohol-Free Living Specialist™", "alcohol-free"),
    ("Certified Porn Addiction Recovery Specialist™", "porn-addiction"),
    ("Certified Food Addiction Specialist™", "food-addiction"),
    ("Certified Shopping Addiction Specialist™", "shopping-addiction"),
    ("Certified Social Media Addiction Specialist™", "social-media-addiction"),
    ("Certified Gaming Addiction Specialist™", "gaming-addiction"),
    ("Certified Workaholism Recovery Specialist™", "workaholism"),
    ("Certified Love & Relationship Addiction Specialist™", "love-addiction"),
    ("Certified Cross-Addiction Specialist™", "cross-addiction"),
]
